package com.xsz.customs.mapper;

import com.xsz.customs.model.dcLog;
import com.xsz.customs.model.dcLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface dcLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_log
     *
     * @mbg.generated Thu Dec 31 12:45:20 CST 2020
     */
    long countByExample(dcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_log
     *
     * @mbg.generated Thu Dec 31 12:45:20 CST 2020
     */
    int deleteByExample(dcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_log
     *
     * @mbg.generated Thu Dec 31 12:45:20 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_log
     *
     * @mbg.generated Thu Dec 31 12:45:20 CST 2020
     */
    int insert(dcLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_log
     *
     * @mbg.generated Thu Dec 31 12:45:20 CST 2020
     */
    int insertSelective(dcLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_log
     *
     * @mbg.generated Thu Dec 31 12:45:20 CST 2020
     */
    List<dcLog> selectByExample(dcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_log
     *
     * @mbg.generated Thu Dec 31 12:45:20 CST 2020
     */
    dcLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_log
     *
     * @mbg.generated Thu Dec 31 12:45:20 CST 2020
     */
    int updateByExampleSelective(@Param("record") dcLog record, @Param("example") dcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_log
     *
     * @mbg.generated Thu Dec 31 12:45:20 CST 2020
     */
    int updateByExample(@Param("record") dcLog record, @Param("example") dcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_log
     *
     * @mbg.generated Thu Dec 31 12:45:20 CST 2020
     */
    int updateByPrimaryKeySelective(dcLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_log
     *
     * @mbg.generated Thu Dec 31 12:45:20 CST 2020
     */
    int updateByPrimaryKey(dcLog record);
}