package com.xsz.customs.mapper;

import com.xsz.customs.model.dcUser;
import com.xsz.customs.model.dcUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface dcUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    long countByExample(dcUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    int deleteByExample(dcUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    int insert(dcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    int insertSelective(dcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    List<dcUser> selectByExample(dcUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    dcUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    int updateByExampleSelective(@Param("record") dcUser record, @Param("example") dcUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    int updateByExample(@Param("record") dcUser record, @Param("example") dcUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    int updateByPrimaryKeySelective(dcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    int updateByPrimaryKey(dcUser record);
}