package com.xsz.customs.mapper;

import com.xsz.customs.model.djLblx;
import com.xsz.customs.model.djLblxExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface djLblxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    long countByExample(djLblxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    int deleteByExample(djLblxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    int insert(djLblx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    int insertSelective(djLblx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    List<djLblx> selectByExample(djLblxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    djLblx selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    int updateByExampleSelective(@Param("record") djLblx record, @Param("example") djLblxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    int updateByExample(@Param("record") djLblx record, @Param("example") djLblxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    int updateByPrimaryKeySelective(djLblx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    int updateByPrimaryKey(djLblx record);
}