package com.xsz.customs.mapper;

import com.xsz.customs.model.zjLblx;
import com.xsz.customs.model.zjLblxExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface zjLblxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    long countByExample(zjLblxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    int deleteByExample(zjLblxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    int insert(zjLblx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    int insertSelective(zjLblx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    List<zjLblx> selectByExample(zjLblxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    zjLblx selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    int updateByExampleSelective(@Param("record") zjLblx record, @Param("example") zjLblxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    int updateByExample(@Param("record") zjLblx record, @Param("example") zjLblxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    int updateByPrimaryKeySelective(zjLblx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    int updateByPrimaryKey(zjLblx record);
}