package com.xsz.customs.model;

public class dcDcrw {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_dcrw.Id
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_dcrw.dc_renwumc
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    private String dcRenwumc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_dcrw.dc_renwuxh
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    private Integer dcRenwuxh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_dcrw.dc_renwugqdm
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    private String dcRenwugqdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_dcrw.dc_renwugqname
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    private String dcRenwugqname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_dcrw.dc_dcbname
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    private String dcDcbname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_dcrw.dc_dcbtj
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    private Integer dcDcbtj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_dcrw.dc_dcbzt
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    private String dcDcbzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_dcrw.dc_by1
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    private String dcBy1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_dcrw.dc_by2
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    private String dcBy2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_dcrw.dc_by3
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    private String dcBy3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_dcrw.Id
     *
     * @return the value of dc_dcrw.Id
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_dcrw.Id
     *
     * @param id the value for dc_dcrw.Id
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_dcrw.dc_renwumc
     *
     * @return the value of dc_dcrw.dc_renwumc
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    public String getDcRenwumc() {
        return dcRenwumc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_dcrw.dc_renwumc
     *
     * @param dcRenwumc the value for dc_dcrw.dc_renwumc
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    public void setDcRenwumc(String dcRenwumc) {
        this.dcRenwumc = dcRenwumc == null ? null : dcRenwumc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_dcrw.dc_renwuxh
     *
     * @return the value of dc_dcrw.dc_renwuxh
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    public Integer getDcRenwuxh() {
        return dcRenwuxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_dcrw.dc_renwuxh
     *
     * @param dcRenwuxh the value for dc_dcrw.dc_renwuxh
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    public void setDcRenwuxh(Integer dcRenwuxh) {
        this.dcRenwuxh = dcRenwuxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_dcrw.dc_renwugqdm
     *
     * @return the value of dc_dcrw.dc_renwugqdm
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    public String getDcRenwugqdm() {
        return dcRenwugqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_dcrw.dc_renwugqdm
     *
     * @param dcRenwugqdm the value for dc_dcrw.dc_renwugqdm
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    public void setDcRenwugqdm(String dcRenwugqdm) {
        this.dcRenwugqdm = dcRenwugqdm == null ? null : dcRenwugqdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_dcrw.dc_renwugqname
     *
     * @return the value of dc_dcrw.dc_renwugqname
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    public String getDcRenwugqname() {
        return dcRenwugqname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_dcrw.dc_renwugqname
     *
     * @param dcRenwugqname the value for dc_dcrw.dc_renwugqname
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    public void setDcRenwugqname(String dcRenwugqname) {
        this.dcRenwugqname = dcRenwugqname == null ? null : dcRenwugqname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_dcrw.dc_dcbname
     *
     * @return the value of dc_dcrw.dc_dcbname
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    public String getDcDcbname() {
        return dcDcbname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_dcrw.dc_dcbname
     *
     * @param dcDcbname the value for dc_dcrw.dc_dcbname
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    public void setDcDcbname(String dcDcbname) {
        this.dcDcbname = dcDcbname == null ? null : dcDcbname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_dcrw.dc_dcbtj
     *
     * @return the value of dc_dcrw.dc_dcbtj
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    public Integer getDcDcbtj() {
        return dcDcbtj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_dcrw.dc_dcbtj
     *
     * @param dcDcbtj the value for dc_dcrw.dc_dcbtj
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    public void setDcDcbtj(Integer dcDcbtj) {
        this.dcDcbtj = dcDcbtj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_dcrw.dc_dcbzt
     *
     * @return the value of dc_dcrw.dc_dcbzt
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    public String getDcDcbzt() {
        return dcDcbzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_dcrw.dc_dcbzt
     *
     * @param dcDcbzt the value for dc_dcrw.dc_dcbzt
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    public void setDcDcbzt(String dcDcbzt) {
        this.dcDcbzt = dcDcbzt == null ? null : dcDcbzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_dcrw.dc_by1
     *
     * @return the value of dc_dcrw.dc_by1
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    public String getDcBy1() {
        return dcBy1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_dcrw.dc_by1
     *
     * @param dcBy1 the value for dc_dcrw.dc_by1
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    public void setDcBy1(String dcBy1) {
        this.dcBy1 = dcBy1 == null ? null : dcBy1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_dcrw.dc_by2
     *
     * @return the value of dc_dcrw.dc_by2
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    public String getDcBy2() {
        return dcBy2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_dcrw.dc_by2
     *
     * @param dcBy2 the value for dc_dcrw.dc_by2
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    public void setDcBy2(String dcBy2) {
        this.dcBy2 = dcBy2 == null ? null : dcBy2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_dcrw.dc_by3
     *
     * @return the value of dc_dcrw.dc_by3
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    public String getDcBy3() {
        return dcBy3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_dcrw.dc_by3
     *
     * @param dcBy3 the value for dc_dcrw.dc_by3
     *
     * @mbg.generated Tue Dec 08 20:23:01 CST 2020
     */
    public void setDcBy3(String dcBy3) {
        this.dcBy3 = dcBy3 == null ? null : dcBy3.trim();
    }
}