package com.xsz.customs.model;

import java.util.ArrayList;
import java.util.List;

public class dcDwjyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dc_dwjy
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dc_dwjy
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dc_dwjy
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_dwjy
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public dcDwjyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_dwjy
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_dwjy
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_dwjy
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_dwjy
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_dwjy
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_dwjy
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_dwjy
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_dwjy
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_dwjy
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_dwjy
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dc_dwjy
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDcRenwumcIsNull() {
            addCriterion("dc_renwumc is null");
            return (Criteria) this;
        }

        public Criteria andDcRenwumcIsNotNull() {
            addCriterion("dc_renwumc is not null");
            return (Criteria) this;
        }

        public Criteria andDcRenwumcEqualTo(String value) {
            addCriterion("dc_renwumc =", value, "dcRenwumc");
            return (Criteria) this;
        }

        public Criteria andDcRenwumcNotEqualTo(String value) {
            addCriterion("dc_renwumc <>", value, "dcRenwumc");
            return (Criteria) this;
        }

        public Criteria andDcRenwumcGreaterThan(String value) {
            addCriterion("dc_renwumc >", value, "dcRenwumc");
            return (Criteria) this;
        }

        public Criteria andDcRenwumcGreaterThanOrEqualTo(String value) {
            addCriterion("dc_renwumc >=", value, "dcRenwumc");
            return (Criteria) this;
        }

        public Criteria andDcRenwumcLessThan(String value) {
            addCriterion("dc_renwumc <", value, "dcRenwumc");
            return (Criteria) this;
        }

        public Criteria andDcRenwumcLessThanOrEqualTo(String value) {
            addCriterion("dc_renwumc <=", value, "dcRenwumc");
            return (Criteria) this;
        }

        public Criteria andDcRenwumcLike(String value) {
            addCriterion("dc_renwumc like", value, "dcRenwumc");
            return (Criteria) this;
        }

        public Criteria andDcRenwumcNotLike(String value) {
            addCriterion("dc_renwumc not like", value, "dcRenwumc");
            return (Criteria) this;
        }

        public Criteria andDcRenwumcIn(List<String> values) {
            addCriterion("dc_renwumc in", values, "dcRenwumc");
            return (Criteria) this;
        }

        public Criteria andDcRenwumcNotIn(List<String> values) {
            addCriterion("dc_renwumc not in", values, "dcRenwumc");
            return (Criteria) this;
        }

        public Criteria andDcRenwumcBetween(String value1, String value2) {
            addCriterion("dc_renwumc between", value1, value2, "dcRenwumc");
            return (Criteria) this;
        }

        public Criteria andDcRenwumcNotBetween(String value1, String value2) {
            addCriterion("dc_renwumc not between", value1, value2, "dcRenwumc");
            return (Criteria) this;
        }

        public Criteria andDcRenwuidIsNull() {
            addCriterion("dc_renwuid is null");
            return (Criteria) this;
        }

        public Criteria andDcRenwuidIsNotNull() {
            addCriterion("dc_renwuid is not null");
            return (Criteria) this;
        }

        public Criteria andDcRenwuidEqualTo(Integer value) {
            addCriterion("dc_renwuid =", value, "dcRenwuid");
            return (Criteria) this;
        }

        public Criteria andDcRenwuidNotEqualTo(Integer value) {
            addCriterion("dc_renwuid <>", value, "dcRenwuid");
            return (Criteria) this;
        }

        public Criteria andDcRenwuidGreaterThan(Integer value) {
            addCriterion("dc_renwuid >", value, "dcRenwuid");
            return (Criteria) this;
        }

        public Criteria andDcRenwuidGreaterThanOrEqualTo(Integer value) {
            addCriterion("dc_renwuid >=", value, "dcRenwuid");
            return (Criteria) this;
        }

        public Criteria andDcRenwuidLessThan(Integer value) {
            addCriterion("dc_renwuid <", value, "dcRenwuid");
            return (Criteria) this;
        }

        public Criteria andDcRenwuidLessThanOrEqualTo(Integer value) {
            addCriterion("dc_renwuid <=", value, "dcRenwuid");
            return (Criteria) this;
        }

        public Criteria andDcRenwuidIn(List<Integer> values) {
            addCriterion("dc_renwuid in", values, "dcRenwuid");
            return (Criteria) this;
        }

        public Criteria andDcRenwuidNotIn(List<Integer> values) {
            addCriterion("dc_renwuid not in", values, "dcRenwuid");
            return (Criteria) this;
        }

        public Criteria andDcRenwuidBetween(Integer value1, Integer value2) {
            addCriterion("dc_renwuid between", value1, value2, "dcRenwuid");
            return (Criteria) this;
        }

        public Criteria andDcRenwuidNotBetween(Integer value1, Integer value2) {
            addCriterion("dc_renwuid not between", value1, value2, "dcRenwuid");
            return (Criteria) this;
        }

        public Criteria andDcRenwuxhIsNull() {
            addCriterion("dc_renwuxh is null");
            return (Criteria) this;
        }

        public Criteria andDcRenwuxhIsNotNull() {
            addCriterion("dc_renwuxh is not null");
            return (Criteria) this;
        }

        public Criteria andDcRenwuxhEqualTo(Integer value) {
            addCriterion("dc_renwuxh =", value, "dcRenwuxh");
            return (Criteria) this;
        }

        public Criteria andDcRenwuxhNotEqualTo(Integer value) {
            addCriterion("dc_renwuxh <>", value, "dcRenwuxh");
            return (Criteria) this;
        }

        public Criteria andDcRenwuxhGreaterThan(Integer value) {
            addCriterion("dc_renwuxh >", value, "dcRenwuxh");
            return (Criteria) this;
        }

        public Criteria andDcRenwuxhGreaterThanOrEqualTo(Integer value) {
            addCriterion("dc_renwuxh >=", value, "dcRenwuxh");
            return (Criteria) this;
        }

        public Criteria andDcRenwuxhLessThan(Integer value) {
            addCriterion("dc_renwuxh <", value, "dcRenwuxh");
            return (Criteria) this;
        }

        public Criteria andDcRenwuxhLessThanOrEqualTo(Integer value) {
            addCriterion("dc_renwuxh <=", value, "dcRenwuxh");
            return (Criteria) this;
        }

        public Criteria andDcRenwuxhIn(List<Integer> values) {
            addCriterion("dc_renwuxh in", values, "dcRenwuxh");
            return (Criteria) this;
        }

        public Criteria andDcRenwuxhNotIn(List<Integer> values) {
            addCriterion("dc_renwuxh not in", values, "dcRenwuxh");
            return (Criteria) this;
        }

        public Criteria andDcRenwuxhBetween(Integer value1, Integer value2) {
            addCriterion("dc_renwuxh between", value1, value2, "dcRenwuxh");
            return (Criteria) this;
        }

        public Criteria andDcRenwuxhNotBetween(Integer value1, Integer value2) {
            addCriterion("dc_renwuxh not between", value1, value2, "dcRenwuxh");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqdmIsNull() {
            addCriterion("dc_renwugqdm is null");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqdmIsNotNull() {
            addCriterion("dc_renwugqdm is not null");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqdmEqualTo(String value) {
            addCriterion("dc_renwugqdm =", value, "dcRenwugqdm");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqdmNotEqualTo(String value) {
            addCriterion("dc_renwugqdm <>", value, "dcRenwugqdm");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqdmGreaterThan(String value) {
            addCriterion("dc_renwugqdm >", value, "dcRenwugqdm");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqdmGreaterThanOrEqualTo(String value) {
            addCriterion("dc_renwugqdm >=", value, "dcRenwugqdm");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqdmLessThan(String value) {
            addCriterion("dc_renwugqdm <", value, "dcRenwugqdm");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqdmLessThanOrEqualTo(String value) {
            addCriterion("dc_renwugqdm <=", value, "dcRenwugqdm");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqdmLike(String value) {
            addCriterion("dc_renwugqdm like", value, "dcRenwugqdm");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqdmNotLike(String value) {
            addCriterion("dc_renwugqdm not like", value, "dcRenwugqdm");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqdmIn(List<String> values) {
            addCriterion("dc_renwugqdm in", values, "dcRenwugqdm");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqdmNotIn(List<String> values) {
            addCriterion("dc_renwugqdm not in", values, "dcRenwugqdm");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqdmBetween(String value1, String value2) {
            addCriterion("dc_renwugqdm between", value1, value2, "dcRenwugqdm");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqdmNotBetween(String value1, String value2) {
            addCriterion("dc_renwugqdm not between", value1, value2, "dcRenwugqdm");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqnameIsNull() {
            addCriterion("dc_renwugqname is null");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqnameIsNotNull() {
            addCriterion("dc_renwugqname is not null");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqnameEqualTo(String value) {
            addCriterion("dc_renwugqname =", value, "dcRenwugqname");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqnameNotEqualTo(String value) {
            addCriterion("dc_renwugqname <>", value, "dcRenwugqname");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqnameGreaterThan(String value) {
            addCriterion("dc_renwugqname >", value, "dcRenwugqname");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqnameGreaterThanOrEqualTo(String value) {
            addCriterion("dc_renwugqname >=", value, "dcRenwugqname");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqnameLessThan(String value) {
            addCriterion("dc_renwugqname <", value, "dcRenwugqname");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqnameLessThanOrEqualTo(String value) {
            addCriterion("dc_renwugqname <=", value, "dcRenwugqname");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqnameLike(String value) {
            addCriterion("dc_renwugqname like", value, "dcRenwugqname");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqnameNotLike(String value) {
            addCriterion("dc_renwugqname not like", value, "dcRenwugqname");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqnameIn(List<String> values) {
            addCriterion("dc_renwugqname in", values, "dcRenwugqname");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqnameNotIn(List<String> values) {
            addCriterion("dc_renwugqname not in", values, "dcRenwugqname");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqnameBetween(String value1, String value2) {
            addCriterion("dc_renwugqname between", value1, value2, "dcRenwugqname");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqnameNotBetween(String value1, String value2) {
            addCriterion("dc_renwugqname not between", value1, value2, "dcRenwugqname");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqdm2IsNull() {
            addCriterion("dc_renwugqdm2 is null");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqdm2IsNotNull() {
            addCriterion("dc_renwugqdm2 is not null");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqdm2EqualTo(String value) {
            addCriterion("dc_renwugqdm2 =", value, "dcRenwugqdm2");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqdm2NotEqualTo(String value) {
            addCriterion("dc_renwugqdm2 <>", value, "dcRenwugqdm2");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqdm2GreaterThan(String value) {
            addCriterion("dc_renwugqdm2 >", value, "dcRenwugqdm2");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqdm2GreaterThanOrEqualTo(String value) {
            addCriterion("dc_renwugqdm2 >=", value, "dcRenwugqdm2");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqdm2LessThan(String value) {
            addCriterion("dc_renwugqdm2 <", value, "dcRenwugqdm2");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqdm2LessThanOrEqualTo(String value) {
            addCriterion("dc_renwugqdm2 <=", value, "dcRenwugqdm2");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqdm2Like(String value) {
            addCriterion("dc_renwugqdm2 like", value, "dcRenwugqdm2");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqdm2NotLike(String value) {
            addCriterion("dc_renwugqdm2 not like", value, "dcRenwugqdm2");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqdm2In(List<String> values) {
            addCriterion("dc_renwugqdm2 in", values, "dcRenwugqdm2");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqdm2NotIn(List<String> values) {
            addCriterion("dc_renwugqdm2 not in", values, "dcRenwugqdm2");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqdm2Between(String value1, String value2) {
            addCriterion("dc_renwugqdm2 between", value1, value2, "dcRenwugqdm2");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqdm2NotBetween(String value1, String value2) {
            addCriterion("dc_renwugqdm2 not between", value1, value2, "dcRenwugqdm2");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqxhIsNull() {
            addCriterion("dc_renwugqxh is null");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqxhIsNotNull() {
            addCriterion("dc_renwugqxh is not null");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqxhEqualTo(Integer value) {
            addCriterion("dc_renwugqxh =", value, "dcRenwugqxh");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqxhNotEqualTo(Integer value) {
            addCriterion("dc_renwugqxh <>", value, "dcRenwugqxh");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqxhGreaterThan(Integer value) {
            addCriterion("dc_renwugqxh >", value, "dcRenwugqxh");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqxhGreaterThanOrEqualTo(Integer value) {
            addCriterion("dc_renwugqxh >=", value, "dcRenwugqxh");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqxhLessThan(Integer value) {
            addCriterion("dc_renwugqxh <", value, "dcRenwugqxh");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqxhLessThanOrEqualTo(Integer value) {
            addCriterion("dc_renwugqxh <=", value, "dcRenwugqxh");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqxhIn(List<Integer> values) {
            addCriterion("dc_renwugqxh in", values, "dcRenwugqxh");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqxhNotIn(List<Integer> values) {
            addCriterion("dc_renwugqxh not in", values, "dcRenwugqxh");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqxhBetween(Integer value1, Integer value2) {
            addCriterion("dc_renwugqxh between", value1, value2, "dcRenwugqxh");
            return (Criteria) this;
        }

        public Criteria andDcRenwugqxhNotBetween(Integer value1, Integer value2) {
            addCriterion("dc_renwugqxh not between", value1, value2, "dcRenwugqxh");
            return (Criteria) this;
        }

        public Criteria andDjYwlyIsNull() {
            addCriterion("dj_ywly is null");
            return (Criteria) this;
        }

        public Criteria andDjYwlyIsNotNull() {
            addCriterion("dj_ywly is not null");
            return (Criteria) this;
        }

        public Criteria andDjYwlyEqualTo(String value) {
            addCriterion("dj_ywly =", value, "djYwly");
            return (Criteria) this;
        }

        public Criteria andDjYwlyNotEqualTo(String value) {
            addCriterion("dj_ywly <>", value, "djYwly");
            return (Criteria) this;
        }

        public Criteria andDjYwlyGreaterThan(String value) {
            addCriterion("dj_ywly >", value, "djYwly");
            return (Criteria) this;
        }

        public Criteria andDjYwlyGreaterThanOrEqualTo(String value) {
            addCriterion("dj_ywly >=", value, "djYwly");
            return (Criteria) this;
        }

        public Criteria andDjYwlyLessThan(String value) {
            addCriterion("dj_ywly <", value, "djYwly");
            return (Criteria) this;
        }

        public Criteria andDjYwlyLessThanOrEqualTo(String value) {
            addCriterion("dj_ywly <=", value, "djYwly");
            return (Criteria) this;
        }

        public Criteria andDjYwlyLike(String value) {
            addCriterion("dj_ywly like", value, "djYwly");
            return (Criteria) this;
        }

        public Criteria andDjYwlyNotLike(String value) {
            addCriterion("dj_ywly not like", value, "djYwly");
            return (Criteria) this;
        }

        public Criteria andDjYwlyIn(List<String> values) {
            addCriterion("dj_ywly in", values, "djYwly");
            return (Criteria) this;
        }

        public Criteria andDjYwlyNotIn(List<String> values) {
            addCriterion("dj_ywly not in", values, "djYwly");
            return (Criteria) this;
        }

        public Criteria andDjYwlyBetween(String value1, String value2) {
            addCriterion("dj_ywly between", value1, value2, "djYwly");
            return (Criteria) this;
        }

        public Criteria andDjYwlyNotBetween(String value1, String value2) {
            addCriterion("dj_ywly not between", value1, value2, "djYwly");
            return (Criteria) this;
        }

        public Criteria andDjLbIsNull() {
            addCriterion("dj_lb is null");
            return (Criteria) this;
        }

        public Criteria andDjLbIsNotNull() {
            addCriterion("dj_lb is not null");
            return (Criteria) this;
        }

        public Criteria andDjLbEqualTo(String value) {
            addCriterion("dj_lb =", value, "djLb");
            return (Criteria) this;
        }

        public Criteria andDjLbNotEqualTo(String value) {
            addCriterion("dj_lb <>", value, "djLb");
            return (Criteria) this;
        }

        public Criteria andDjLbGreaterThan(String value) {
            addCriterion("dj_lb >", value, "djLb");
            return (Criteria) this;
        }

        public Criteria andDjLbGreaterThanOrEqualTo(String value) {
            addCriterion("dj_lb >=", value, "djLb");
            return (Criteria) this;
        }

        public Criteria andDjLbLessThan(String value) {
            addCriterion("dj_lb <", value, "djLb");
            return (Criteria) this;
        }

        public Criteria andDjLbLessThanOrEqualTo(String value) {
            addCriterion("dj_lb <=", value, "djLb");
            return (Criteria) this;
        }

        public Criteria andDjLbLike(String value) {
            addCriterion("dj_lb like", value, "djLb");
            return (Criteria) this;
        }

        public Criteria andDjLbNotLike(String value) {
            addCriterion("dj_lb not like", value, "djLb");
            return (Criteria) this;
        }

        public Criteria andDjLbIn(List<String> values) {
            addCriterion("dj_lb in", values, "djLb");
            return (Criteria) this;
        }

        public Criteria andDjLbNotIn(List<String> values) {
            addCriterion("dj_lb not in", values, "djLb");
            return (Criteria) this;
        }

        public Criteria andDjLbBetween(String value1, String value2) {
            addCriterion("dj_lb between", value1, value2, "djLb");
            return (Criteria) this;
        }

        public Criteria andDjLbNotBetween(String value1, String value2) {
            addCriterion("dj_lb not between", value1, value2, "djLb");
            return (Criteria) this;
        }

        public Criteria andDjNameIsNull() {
            addCriterion("dj_name is null");
            return (Criteria) this;
        }

        public Criteria andDjNameIsNotNull() {
            addCriterion("dj_name is not null");
            return (Criteria) this;
        }

        public Criteria andDjNameEqualTo(String value) {
            addCriterion("dj_name =", value, "djName");
            return (Criteria) this;
        }

        public Criteria andDjNameNotEqualTo(String value) {
            addCriterion("dj_name <>", value, "djName");
            return (Criteria) this;
        }

        public Criteria andDjNameGreaterThan(String value) {
            addCriterion("dj_name >", value, "djName");
            return (Criteria) this;
        }

        public Criteria andDjNameGreaterThanOrEqualTo(String value) {
            addCriterion("dj_name >=", value, "djName");
            return (Criteria) this;
        }

        public Criteria andDjNameLessThan(String value) {
            addCriterion("dj_name <", value, "djName");
            return (Criteria) this;
        }

        public Criteria andDjNameLessThanOrEqualTo(String value) {
            addCriterion("dj_name <=", value, "djName");
            return (Criteria) this;
        }

        public Criteria andDjNameLike(String value) {
            addCriterion("dj_name like", value, "djName");
            return (Criteria) this;
        }

        public Criteria andDjNameNotLike(String value) {
            addCriterion("dj_name not like", value, "djName");
            return (Criteria) this;
        }

        public Criteria andDjNameIn(List<String> values) {
            addCriterion("dj_name in", values, "djName");
            return (Criteria) this;
        }

        public Criteria andDjNameNotIn(List<String> values) {
            addCriterion("dj_name not in", values, "djName");
            return (Criteria) this;
        }

        public Criteria andDjNameBetween(String value1, String value2) {
            addCriterion("dj_name between", value1, value2, "djName");
            return (Criteria) this;
        }

        public Criteria andDjNameNotBetween(String value1, String value2) {
            addCriterion("dj_name not between", value1, value2, "djName");
            return (Criteria) this;
        }

        public Criteria andDjYwmIsNull() {
            addCriterion("dj_ywm is null");
            return (Criteria) this;
        }

        public Criteria andDjYwmIsNotNull() {
            addCriterion("dj_ywm is not null");
            return (Criteria) this;
        }

        public Criteria andDjYwmEqualTo(String value) {
            addCriterion("dj_ywm =", value, "djYwm");
            return (Criteria) this;
        }

        public Criteria andDjYwmNotEqualTo(String value) {
            addCriterion("dj_ywm <>", value, "djYwm");
            return (Criteria) this;
        }

        public Criteria andDjYwmGreaterThan(String value) {
            addCriterion("dj_ywm >", value, "djYwm");
            return (Criteria) this;
        }

        public Criteria andDjYwmGreaterThanOrEqualTo(String value) {
            addCriterion("dj_ywm >=", value, "djYwm");
            return (Criteria) this;
        }

        public Criteria andDjYwmLessThan(String value) {
            addCriterion("dj_ywm <", value, "djYwm");
            return (Criteria) this;
        }

        public Criteria andDjYwmLessThanOrEqualTo(String value) {
            addCriterion("dj_ywm <=", value, "djYwm");
            return (Criteria) this;
        }

        public Criteria andDjYwmLike(String value) {
            addCriterion("dj_ywm like", value, "djYwm");
            return (Criteria) this;
        }

        public Criteria andDjYwmNotLike(String value) {
            addCriterion("dj_ywm not like", value, "djYwm");
            return (Criteria) this;
        }

        public Criteria andDjYwmIn(List<String> values) {
            addCriterion("dj_ywm in", values, "djYwm");
            return (Criteria) this;
        }

        public Criteria andDjYwmNotIn(List<String> values) {
            addCriterion("dj_ywm not in", values, "djYwm");
            return (Criteria) this;
        }

        public Criteria andDjYwmBetween(String value1, String value2) {
            addCriterion("dj_ywm between", value1, value2, "djYwm");
            return (Criteria) this;
        }

        public Criteria andDjYwmNotBetween(String value1, String value2) {
            addCriterion("dj_ywm not between", value1, value2, "djYwm");
            return (Criteria) this;
        }

        public Criteria andDjDuzhuxingIsNull() {
            addCriterion("dj_duzhuxing is null");
            return (Criteria) this;
        }

        public Criteria andDjDuzhuxingIsNotNull() {
            addCriterion("dj_duzhuxing is not null");
            return (Criteria) this;
        }

        public Criteria andDjDuzhuxingEqualTo(String value) {
            addCriterion("dj_duzhuxing =", value, "djDuzhuxing");
            return (Criteria) this;
        }

        public Criteria andDjDuzhuxingNotEqualTo(String value) {
            addCriterion("dj_duzhuxing <>", value, "djDuzhuxing");
            return (Criteria) this;
        }

        public Criteria andDjDuzhuxingGreaterThan(String value) {
            addCriterion("dj_duzhuxing >", value, "djDuzhuxing");
            return (Criteria) this;
        }

        public Criteria andDjDuzhuxingGreaterThanOrEqualTo(String value) {
            addCriterion("dj_duzhuxing >=", value, "djDuzhuxing");
            return (Criteria) this;
        }

        public Criteria andDjDuzhuxingLessThan(String value) {
            addCriterion("dj_duzhuxing <", value, "djDuzhuxing");
            return (Criteria) this;
        }

        public Criteria andDjDuzhuxingLessThanOrEqualTo(String value) {
            addCriterion("dj_duzhuxing <=", value, "djDuzhuxing");
            return (Criteria) this;
        }

        public Criteria andDjDuzhuxingLike(String value) {
            addCriterion("dj_duzhuxing like", value, "djDuzhuxing");
            return (Criteria) this;
        }

        public Criteria andDjDuzhuxingNotLike(String value) {
            addCriterion("dj_duzhuxing not like", value, "djDuzhuxing");
            return (Criteria) this;
        }

        public Criteria andDjDuzhuxingIn(List<String> values) {
            addCriterion("dj_duzhuxing in", values, "djDuzhuxing");
            return (Criteria) this;
        }

        public Criteria andDjDuzhuxingNotIn(List<String> values) {
            addCriterion("dj_duzhuxing not in", values, "djDuzhuxing");
            return (Criteria) this;
        }

        public Criteria andDjDuzhuxingBetween(String value1, String value2) {
            addCriterion("dj_duzhuxing between", value1, value2, "djDuzhuxing");
            return (Criteria) this;
        }

        public Criteria andDjDuzhuxingNotBetween(String value1, String value2) {
            addCriterion("dj_duzhuxing not between", value1, value2, "djDuzhuxing");
            return (Criteria) this;
        }

        public Criteria andDjBingyuanIsNull() {
            addCriterion("dj_bingyuan is null");
            return (Criteria) this;
        }

        public Criteria andDjBingyuanIsNotNull() {
            addCriterion("dj_bingyuan is not null");
            return (Criteria) this;
        }

        public Criteria andDjBingyuanEqualTo(String value) {
            addCriterion("dj_bingyuan =", value, "djBingyuan");
            return (Criteria) this;
        }

        public Criteria andDjBingyuanNotEqualTo(String value) {
            addCriterion("dj_bingyuan <>", value, "djBingyuan");
            return (Criteria) this;
        }

        public Criteria andDjBingyuanGreaterThan(String value) {
            addCriterion("dj_bingyuan >", value, "djBingyuan");
            return (Criteria) this;
        }

        public Criteria andDjBingyuanGreaterThanOrEqualTo(String value) {
            addCriterion("dj_bingyuan >=", value, "djBingyuan");
            return (Criteria) this;
        }

        public Criteria andDjBingyuanLessThan(String value) {
            addCriterion("dj_bingyuan <", value, "djBingyuan");
            return (Criteria) this;
        }

        public Criteria andDjBingyuanLessThanOrEqualTo(String value) {
            addCriterion("dj_bingyuan <=", value, "djBingyuan");
            return (Criteria) this;
        }

        public Criteria andDjBingyuanLike(String value) {
            addCriterion("dj_bingyuan like", value, "djBingyuan");
            return (Criteria) this;
        }

        public Criteria andDjBingyuanNotLike(String value) {
            addCriterion("dj_bingyuan not like", value, "djBingyuan");
            return (Criteria) this;
        }

        public Criteria andDjBingyuanIn(List<String> values) {
            addCriterion("dj_bingyuan in", values, "djBingyuan");
            return (Criteria) this;
        }

        public Criteria andDjBingyuanNotIn(List<String> values) {
            addCriterion("dj_bingyuan not in", values, "djBingyuan");
            return (Criteria) this;
        }

        public Criteria andDjBingyuanBetween(String value1, String value2) {
            addCriterion("dj_bingyuan between", value1, value2, "djBingyuan");
            return (Criteria) this;
        }

        public Criteria andDjBingyuanNotBetween(String value1, String value2) {
            addCriterion("dj_bingyuan not between", value1, value2, "djBingyuan");
            return (Criteria) this;
        }

        public Criteria andDjXibaoxingIsNull() {
            addCriterion("dj_xibaoxing is null");
            return (Criteria) this;
        }

        public Criteria andDjXibaoxingIsNotNull() {
            addCriterion("dj_xibaoxing is not null");
            return (Criteria) this;
        }

        public Criteria andDjXibaoxingEqualTo(String value) {
            addCriterion("dj_xibaoxing =", value, "djXibaoxing");
            return (Criteria) this;
        }

        public Criteria andDjXibaoxingNotEqualTo(String value) {
            addCriterion("dj_xibaoxing <>", value, "djXibaoxing");
            return (Criteria) this;
        }

        public Criteria andDjXibaoxingGreaterThan(String value) {
            addCriterion("dj_xibaoxing >", value, "djXibaoxing");
            return (Criteria) this;
        }

        public Criteria andDjXibaoxingGreaterThanOrEqualTo(String value) {
            addCriterion("dj_xibaoxing >=", value, "djXibaoxing");
            return (Criteria) this;
        }

        public Criteria andDjXibaoxingLessThan(String value) {
            addCriterion("dj_xibaoxing <", value, "djXibaoxing");
            return (Criteria) this;
        }

        public Criteria andDjXibaoxingLessThanOrEqualTo(String value) {
            addCriterion("dj_xibaoxing <=", value, "djXibaoxing");
            return (Criteria) this;
        }

        public Criteria andDjXibaoxingLike(String value) {
            addCriterion("dj_xibaoxing like", value, "djXibaoxing");
            return (Criteria) this;
        }

        public Criteria andDjXibaoxingNotLike(String value) {
            addCriterion("dj_xibaoxing not like", value, "djXibaoxing");
            return (Criteria) this;
        }

        public Criteria andDjXibaoxingIn(List<String> values) {
            addCriterion("dj_xibaoxing in", values, "djXibaoxing");
            return (Criteria) this;
        }

        public Criteria andDjXibaoxingNotIn(List<String> values) {
            addCriterion("dj_xibaoxing not in", values, "djXibaoxing");
            return (Criteria) this;
        }

        public Criteria andDjXibaoxingBetween(String value1, String value2) {
            addCriterion("dj_xibaoxing between", value1, value2, "djXibaoxing");
            return (Criteria) this;
        }

        public Criteria andDjXibaoxingNotBetween(String value1, String value2) {
            addCriterion("dj_xibaoxing not between", value1, value2, "djXibaoxing");
            return (Criteria) this;
        }

        public Criteria andDjNeibubhIsNull() {
            addCriterion("dj_neibubh is null");
            return (Criteria) this;
        }

        public Criteria andDjNeibubhIsNotNull() {
            addCriterion("dj_neibubh is not null");
            return (Criteria) this;
        }

        public Criteria andDjNeibubhEqualTo(String value) {
            addCriterion("dj_neibubh =", value, "djNeibubh");
            return (Criteria) this;
        }

        public Criteria andDjNeibubhNotEqualTo(String value) {
            addCriterion("dj_neibubh <>", value, "djNeibubh");
            return (Criteria) this;
        }

        public Criteria andDjNeibubhGreaterThan(String value) {
            addCriterion("dj_neibubh >", value, "djNeibubh");
            return (Criteria) this;
        }

        public Criteria andDjNeibubhGreaterThanOrEqualTo(String value) {
            addCriterion("dj_neibubh >=", value, "djNeibubh");
            return (Criteria) this;
        }

        public Criteria andDjNeibubhLessThan(String value) {
            addCriterion("dj_neibubh <", value, "djNeibubh");
            return (Criteria) this;
        }

        public Criteria andDjNeibubhLessThanOrEqualTo(String value) {
            addCriterion("dj_neibubh <=", value, "djNeibubh");
            return (Criteria) this;
        }

        public Criteria andDjNeibubhLike(String value) {
            addCriterion("dj_neibubh like", value, "djNeibubh");
            return (Criteria) this;
        }

        public Criteria andDjNeibubhNotLike(String value) {
            addCriterion("dj_neibubh not like", value, "djNeibubh");
            return (Criteria) this;
        }

        public Criteria andDjNeibubhIn(List<String> values) {
            addCriterion("dj_neibubh in", values, "djNeibubh");
            return (Criteria) this;
        }

        public Criteria andDjNeibubhNotIn(List<String> values) {
            addCriterion("dj_neibubh not in", values, "djNeibubh");
            return (Criteria) this;
        }

        public Criteria andDjNeibubhBetween(String value1, String value2) {
            addCriterion("dj_neibubh between", value1, value2, "djNeibubh");
            return (Criteria) this;
        }

        public Criteria andDjNeibubhNotBetween(String value1, String value2) {
            addCriterion("dj_neibubh not between", value1, value2, "djNeibubh");
            return (Criteria) this;
        }

        public Criteria andDjChuanciIsNull() {
            addCriterion("dj_chuanci is null");
            return (Criteria) this;
        }

        public Criteria andDjChuanciIsNotNull() {
            addCriterion("dj_chuanci is not null");
            return (Criteria) this;
        }

        public Criteria andDjChuanciEqualTo(String value) {
            addCriterion("dj_chuanci =", value, "djChuanci");
            return (Criteria) this;
        }

        public Criteria andDjChuanciNotEqualTo(String value) {
            addCriterion("dj_chuanci <>", value, "djChuanci");
            return (Criteria) this;
        }

        public Criteria andDjChuanciGreaterThan(String value) {
            addCriterion("dj_chuanci >", value, "djChuanci");
            return (Criteria) this;
        }

        public Criteria andDjChuanciGreaterThanOrEqualTo(String value) {
            addCriterion("dj_chuanci >=", value, "djChuanci");
            return (Criteria) this;
        }

        public Criteria andDjChuanciLessThan(String value) {
            addCriterion("dj_chuanci <", value, "djChuanci");
            return (Criteria) this;
        }

        public Criteria andDjChuanciLessThanOrEqualTo(String value) {
            addCriterion("dj_chuanci <=", value, "djChuanci");
            return (Criteria) this;
        }

        public Criteria andDjChuanciLike(String value) {
            addCriterion("dj_chuanci like", value, "djChuanci");
            return (Criteria) this;
        }

        public Criteria andDjChuanciNotLike(String value) {
            addCriterion("dj_chuanci not like", value, "djChuanci");
            return (Criteria) this;
        }

        public Criteria andDjChuanciIn(List<String> values) {
            addCriterion("dj_chuanci in", values, "djChuanci");
            return (Criteria) this;
        }

        public Criteria andDjChuanciNotIn(List<String> values) {
            addCriterion("dj_chuanci not in", values, "djChuanci");
            return (Criteria) this;
        }

        public Criteria andDjChuanciBetween(String value1, String value2) {
            addCriterion("dj_chuanci between", value1, value2, "djChuanci");
            return (Criteria) this;
        }

        public Criteria andDjChuanciNotBetween(String value1, String value2) {
            addCriterion("dj_chuanci not between", value1, value2, "djChuanci");
            return (Criteria) this;
        }

        public Criteria andDjZhuangtaiIsNull() {
            addCriterion("dj_zhuangtai is null");
            return (Criteria) this;
        }

        public Criteria andDjZhuangtaiIsNotNull() {
            addCriterion("dj_zhuangtai is not null");
            return (Criteria) this;
        }

        public Criteria andDjZhuangtaiEqualTo(String value) {
            addCriterion("dj_zhuangtai =", value, "djZhuangtai");
            return (Criteria) this;
        }

        public Criteria andDjZhuangtaiNotEqualTo(String value) {
            addCriterion("dj_zhuangtai <>", value, "djZhuangtai");
            return (Criteria) this;
        }

        public Criteria andDjZhuangtaiGreaterThan(String value) {
            addCriterion("dj_zhuangtai >", value, "djZhuangtai");
            return (Criteria) this;
        }

        public Criteria andDjZhuangtaiGreaterThanOrEqualTo(String value) {
            addCriterion("dj_zhuangtai >=", value, "djZhuangtai");
            return (Criteria) this;
        }

        public Criteria andDjZhuangtaiLessThan(String value) {
            addCriterion("dj_zhuangtai <", value, "djZhuangtai");
            return (Criteria) this;
        }

        public Criteria andDjZhuangtaiLessThanOrEqualTo(String value) {
            addCriterion("dj_zhuangtai <=", value, "djZhuangtai");
            return (Criteria) this;
        }

        public Criteria andDjZhuangtaiLike(String value) {
            addCriterion("dj_zhuangtai like", value, "djZhuangtai");
            return (Criteria) this;
        }

        public Criteria andDjZhuangtaiNotLike(String value) {
            addCriterion("dj_zhuangtai not like", value, "djZhuangtai");
            return (Criteria) this;
        }

        public Criteria andDjZhuangtaiIn(List<String> values) {
            addCriterion("dj_zhuangtai in", values, "djZhuangtai");
            return (Criteria) this;
        }

        public Criteria andDjZhuangtaiNotIn(List<String> values) {
            addCriterion("dj_zhuangtai not in", values, "djZhuangtai");
            return (Criteria) this;
        }

        public Criteria andDjZhuangtaiBetween(String value1, String value2) {
            addCriterion("dj_zhuangtai between", value1, value2, "djZhuangtai");
            return (Criteria) this;
        }

        public Criteria andDjZhuangtaiNotBetween(String value1, String value2) {
            addCriterion("dj_zhuangtai not between", value1, value2, "djZhuangtai");
            return (Criteria) this;
        }

        public Criteria andDjDuzhucdIsNull() {
            addCriterion("dj_duzhucd is null");
            return (Criteria) this;
        }

        public Criteria andDjDuzhucdIsNotNull() {
            addCriterion("dj_duzhucd is not null");
            return (Criteria) this;
        }

        public Criteria andDjDuzhucdEqualTo(String value) {
            addCriterion("dj_duzhucd =", value, "djDuzhucd");
            return (Criteria) this;
        }

        public Criteria andDjDuzhucdNotEqualTo(String value) {
            addCriterion("dj_duzhucd <>", value, "djDuzhucd");
            return (Criteria) this;
        }

        public Criteria andDjDuzhucdGreaterThan(String value) {
            addCriterion("dj_duzhucd >", value, "djDuzhucd");
            return (Criteria) this;
        }

        public Criteria andDjDuzhucdGreaterThanOrEqualTo(String value) {
            addCriterion("dj_duzhucd >=", value, "djDuzhucd");
            return (Criteria) this;
        }

        public Criteria andDjDuzhucdLessThan(String value) {
            addCriterion("dj_duzhucd <", value, "djDuzhucd");
            return (Criteria) this;
        }

        public Criteria andDjDuzhucdLessThanOrEqualTo(String value) {
            addCriterion("dj_duzhucd <=", value, "djDuzhucd");
            return (Criteria) this;
        }

        public Criteria andDjDuzhucdLike(String value) {
            addCriterion("dj_duzhucd like", value, "djDuzhucd");
            return (Criteria) this;
        }

        public Criteria andDjDuzhucdNotLike(String value) {
            addCriterion("dj_duzhucd not like", value, "djDuzhucd");
            return (Criteria) this;
        }

        public Criteria andDjDuzhucdIn(List<String> values) {
            addCriterion("dj_duzhucd in", values, "djDuzhucd");
            return (Criteria) this;
        }

        public Criteria andDjDuzhucdNotIn(List<String> values) {
            addCriterion("dj_duzhucd not in", values, "djDuzhucd");
            return (Criteria) this;
        }

        public Criteria andDjDuzhucdBetween(String value1, String value2) {
            addCriterion("dj_duzhucd between", value1, value2, "djDuzhucd");
            return (Criteria) this;
        }

        public Criteria andDjDuzhucdNotBetween(String value1, String value2) {
            addCriterion("dj_duzhucd not between", value1, value2, "djDuzhucd");
            return (Criteria) this;
        }

        public Criteria andDjLysuzhuIsNull() {
            addCriterion("dj_lysuzhu is null");
            return (Criteria) this;
        }

        public Criteria andDjLysuzhuIsNotNull() {
            addCriterion("dj_lysuzhu is not null");
            return (Criteria) this;
        }

        public Criteria andDjLysuzhuEqualTo(String value) {
            addCriterion("dj_lysuzhu =", value, "djLysuzhu");
            return (Criteria) this;
        }

        public Criteria andDjLysuzhuNotEqualTo(String value) {
            addCriterion("dj_lysuzhu <>", value, "djLysuzhu");
            return (Criteria) this;
        }

        public Criteria andDjLysuzhuGreaterThan(String value) {
            addCriterion("dj_lysuzhu >", value, "djLysuzhu");
            return (Criteria) this;
        }

        public Criteria andDjLysuzhuGreaterThanOrEqualTo(String value) {
            addCriterion("dj_lysuzhu >=", value, "djLysuzhu");
            return (Criteria) this;
        }

        public Criteria andDjLysuzhuLessThan(String value) {
            addCriterion("dj_lysuzhu <", value, "djLysuzhu");
            return (Criteria) this;
        }

        public Criteria andDjLysuzhuLessThanOrEqualTo(String value) {
            addCriterion("dj_lysuzhu <=", value, "djLysuzhu");
            return (Criteria) this;
        }

        public Criteria andDjLysuzhuLike(String value) {
            addCriterion("dj_lysuzhu like", value, "djLysuzhu");
            return (Criteria) this;
        }

        public Criteria andDjLysuzhuNotLike(String value) {
            addCriterion("dj_lysuzhu not like", value, "djLysuzhu");
            return (Criteria) this;
        }

        public Criteria andDjLysuzhuIn(List<String> values) {
            addCriterion("dj_lysuzhu in", values, "djLysuzhu");
            return (Criteria) this;
        }

        public Criteria andDjLysuzhuNotIn(List<String> values) {
            addCriterion("dj_lysuzhu not in", values, "djLysuzhu");
            return (Criteria) this;
        }

        public Criteria andDjLysuzhuBetween(String value1, String value2) {
            addCriterion("dj_lysuzhu between", value1, value2, "djLysuzhu");
            return (Criteria) this;
        }

        public Criteria andDjLysuzhuNotBetween(String value1, String value2) {
            addCriterion("dj_lysuzhu not between", value1, value2, "djLysuzhu");
            return (Criteria) this;
        }

        public Criteria andDjLaiyuanIsNull() {
            addCriterion("dj_laiyuan is null");
            return (Criteria) this;
        }

        public Criteria andDjLaiyuanIsNotNull() {
            addCriterion("dj_laiyuan is not null");
            return (Criteria) this;
        }

        public Criteria andDjLaiyuanEqualTo(String value) {
            addCriterion("dj_laiyuan =", value, "djLaiyuan");
            return (Criteria) this;
        }

        public Criteria andDjLaiyuanNotEqualTo(String value) {
            addCriterion("dj_laiyuan <>", value, "djLaiyuan");
            return (Criteria) this;
        }

        public Criteria andDjLaiyuanGreaterThan(String value) {
            addCriterion("dj_laiyuan >", value, "djLaiyuan");
            return (Criteria) this;
        }

        public Criteria andDjLaiyuanGreaterThanOrEqualTo(String value) {
            addCriterion("dj_laiyuan >=", value, "djLaiyuan");
            return (Criteria) this;
        }

        public Criteria andDjLaiyuanLessThan(String value) {
            addCriterion("dj_laiyuan <", value, "djLaiyuan");
            return (Criteria) this;
        }

        public Criteria andDjLaiyuanLessThanOrEqualTo(String value) {
            addCriterion("dj_laiyuan <=", value, "djLaiyuan");
            return (Criteria) this;
        }

        public Criteria andDjLaiyuanLike(String value) {
            addCriterion("dj_laiyuan like", value, "djLaiyuan");
            return (Criteria) this;
        }

        public Criteria andDjLaiyuanNotLike(String value) {
            addCriterion("dj_laiyuan not like", value, "djLaiyuan");
            return (Criteria) this;
        }

        public Criteria andDjLaiyuanIn(List<String> values) {
            addCriterion("dj_laiyuan in", values, "djLaiyuan");
            return (Criteria) this;
        }

        public Criteria andDjLaiyuanNotIn(List<String> values) {
            addCriterion("dj_laiyuan not in", values, "djLaiyuan");
            return (Criteria) this;
        }

        public Criteria andDjLaiyuanBetween(String value1, String value2) {
            addCriterion("dj_laiyuan between", value1, value2, "djLaiyuan");
            return (Criteria) this;
        }

        public Criteria andDjLaiyuanNotBetween(String value1, String value2) {
            addCriterion("dj_laiyuan not between", value1, value2, "djLaiyuan");
            return (Criteria) this;
        }

        public Criteria andDjHuoqutjIsNull() {
            addCriterion("dj_huoqutj is null");
            return (Criteria) this;
        }

        public Criteria andDjHuoqutjIsNotNull() {
            addCriterion("dj_huoqutj is not null");
            return (Criteria) this;
        }

        public Criteria andDjHuoqutjEqualTo(String value) {
            addCriterion("dj_huoqutj =", value, "djHuoqutj");
            return (Criteria) this;
        }

        public Criteria andDjHuoqutjNotEqualTo(String value) {
            addCriterion("dj_huoqutj <>", value, "djHuoqutj");
            return (Criteria) this;
        }

        public Criteria andDjHuoqutjGreaterThan(String value) {
            addCriterion("dj_huoqutj >", value, "djHuoqutj");
            return (Criteria) this;
        }

        public Criteria andDjHuoqutjGreaterThanOrEqualTo(String value) {
            addCriterion("dj_huoqutj >=", value, "djHuoqutj");
            return (Criteria) this;
        }

        public Criteria andDjHuoqutjLessThan(String value) {
            addCriterion("dj_huoqutj <", value, "djHuoqutj");
            return (Criteria) this;
        }

        public Criteria andDjHuoqutjLessThanOrEqualTo(String value) {
            addCriterion("dj_huoqutj <=", value, "djHuoqutj");
            return (Criteria) this;
        }

        public Criteria andDjHuoqutjLike(String value) {
            addCriterion("dj_huoqutj like", value, "djHuoqutj");
            return (Criteria) this;
        }

        public Criteria andDjHuoqutjNotLike(String value) {
            addCriterion("dj_huoqutj not like", value, "djHuoqutj");
            return (Criteria) this;
        }

        public Criteria andDjHuoqutjIn(List<String> values) {
            addCriterion("dj_huoqutj in", values, "djHuoqutj");
            return (Criteria) this;
        }

        public Criteria andDjHuoqutjNotIn(List<String> values) {
            addCriterion("dj_huoqutj not in", values, "djHuoqutj");
            return (Criteria) this;
        }

        public Criteria andDjHuoqutjBetween(String value1, String value2) {
            addCriterion("dj_huoqutj between", value1, value2, "djHuoqutj");
            return (Criteria) this;
        }

        public Criteria andDjHuoqutjNotBetween(String value1, String value2) {
            addCriterion("dj_huoqutj not between", value1, value2, "djHuoqutj");
            return (Criteria) this;
        }

        public Criteria andDjYblIsNull() {
            addCriterion("dj_ybl is null");
            return (Criteria) this;
        }

        public Criteria andDjYblIsNotNull() {
            addCriterion("dj_ybl is not null");
            return (Criteria) this;
        }

        public Criteria andDjYblEqualTo(Integer value) {
            addCriterion("dj_ybl =", value, "djYbl");
            return (Criteria) this;
        }

        public Criteria andDjYblNotEqualTo(Integer value) {
            addCriterion("dj_ybl <>", value, "djYbl");
            return (Criteria) this;
        }

        public Criteria andDjYblGreaterThan(Integer value) {
            addCriterion("dj_ybl >", value, "djYbl");
            return (Criteria) this;
        }

        public Criteria andDjYblGreaterThanOrEqualTo(Integer value) {
            addCriterion("dj_ybl >=", value, "djYbl");
            return (Criteria) this;
        }

        public Criteria andDjYblLessThan(Integer value) {
            addCriterion("dj_ybl <", value, "djYbl");
            return (Criteria) this;
        }

        public Criteria andDjYblLessThanOrEqualTo(Integer value) {
            addCriterion("dj_ybl <=", value, "djYbl");
            return (Criteria) this;
        }

        public Criteria andDjYblIn(List<Integer> values) {
            addCriterion("dj_ybl in", values, "djYbl");
            return (Criteria) this;
        }

        public Criteria andDjYblNotIn(List<Integer> values) {
            addCriterion("dj_ybl not in", values, "djYbl");
            return (Criteria) this;
        }

        public Criteria andDjYblBetween(Integer value1, Integer value2) {
            addCriterion("dj_ybl between", value1, value2, "djYbl");
            return (Criteria) this;
        }

        public Criteria andDjYblNotBetween(Integer value1, Integer value2) {
            addCriterion("dj_ybl not between", value1, value2, "djYbl");
            return (Criteria) this;
        }

        public Criteria andDjYbdanweiIsNull() {
            addCriterion("dj_ybdanwei is null");
            return (Criteria) this;
        }

        public Criteria andDjYbdanweiIsNotNull() {
            addCriterion("dj_ybdanwei is not null");
            return (Criteria) this;
        }

        public Criteria andDjYbdanweiEqualTo(String value) {
            addCriterion("dj_ybdanwei =", value, "djYbdanwei");
            return (Criteria) this;
        }

        public Criteria andDjYbdanweiNotEqualTo(String value) {
            addCriterion("dj_ybdanwei <>", value, "djYbdanwei");
            return (Criteria) this;
        }

        public Criteria andDjYbdanweiGreaterThan(String value) {
            addCriterion("dj_ybdanwei >", value, "djYbdanwei");
            return (Criteria) this;
        }

        public Criteria andDjYbdanweiGreaterThanOrEqualTo(String value) {
            addCriterion("dj_ybdanwei >=", value, "djYbdanwei");
            return (Criteria) this;
        }

        public Criteria andDjYbdanweiLessThan(String value) {
            addCriterion("dj_ybdanwei <", value, "djYbdanwei");
            return (Criteria) this;
        }

        public Criteria andDjYbdanweiLessThanOrEqualTo(String value) {
            addCriterion("dj_ybdanwei <=", value, "djYbdanwei");
            return (Criteria) this;
        }

        public Criteria andDjYbdanweiLike(String value) {
            addCriterion("dj_ybdanwei like", value, "djYbdanwei");
            return (Criteria) this;
        }

        public Criteria andDjYbdanweiNotLike(String value) {
            addCriterion("dj_ybdanwei not like", value, "djYbdanwei");
            return (Criteria) this;
        }

        public Criteria andDjYbdanweiIn(List<String> values) {
            addCriterion("dj_ybdanwei in", values, "djYbdanwei");
            return (Criteria) this;
        }

        public Criteria andDjYbdanweiNotIn(List<String> values) {
            addCriterion("dj_ybdanwei not in", values, "djYbdanwei");
            return (Criteria) this;
        }

        public Criteria andDjYbdanweiBetween(String value1, String value2) {
            addCriterion("dj_ybdanwei between", value1, value2, "djYbdanwei");
            return (Criteria) this;
        }

        public Criteria andDjYbdanweiNotBetween(String value1, String value2) {
            addCriterion("dj_ybdanwei not between", value1, value2, "djYbdanwei");
            return (Criteria) this;
        }

        public Criteria andDjBaocuntjIsNull() {
            addCriterion("dj_baocuntj is null");
            return (Criteria) this;
        }

        public Criteria andDjBaocuntjIsNotNull() {
            addCriterion("dj_baocuntj is not null");
            return (Criteria) this;
        }

        public Criteria andDjBaocuntjEqualTo(String value) {
            addCriterion("dj_baocuntj =", value, "djBaocuntj");
            return (Criteria) this;
        }

        public Criteria andDjBaocuntjNotEqualTo(String value) {
            addCriterion("dj_baocuntj <>", value, "djBaocuntj");
            return (Criteria) this;
        }

        public Criteria andDjBaocuntjGreaterThan(String value) {
            addCriterion("dj_baocuntj >", value, "djBaocuntj");
            return (Criteria) this;
        }

        public Criteria andDjBaocuntjGreaterThanOrEqualTo(String value) {
            addCriterion("dj_baocuntj >=", value, "djBaocuntj");
            return (Criteria) this;
        }

        public Criteria andDjBaocuntjLessThan(String value) {
            addCriterion("dj_baocuntj <", value, "djBaocuntj");
            return (Criteria) this;
        }

        public Criteria andDjBaocuntjLessThanOrEqualTo(String value) {
            addCriterion("dj_baocuntj <=", value, "djBaocuntj");
            return (Criteria) this;
        }

        public Criteria andDjBaocuntjLike(String value) {
            addCriterion("dj_baocuntj like", value, "djBaocuntj");
            return (Criteria) this;
        }

        public Criteria andDjBaocuntjNotLike(String value) {
            addCriterion("dj_baocuntj not like", value, "djBaocuntj");
            return (Criteria) this;
        }

        public Criteria andDjBaocuntjIn(List<String> values) {
            addCriterion("dj_baocuntj in", values, "djBaocuntj");
            return (Criteria) this;
        }

        public Criteria andDjBaocuntjNotIn(List<String> values) {
            addCriterion("dj_baocuntj not in", values, "djBaocuntj");
            return (Criteria) this;
        }

        public Criteria andDjBaocuntjBetween(String value1, String value2) {
            addCriterion("dj_baocuntj between", value1, value2, "djBaocuntj");
            return (Criteria) this;
        }

        public Criteria andDjBaocuntjNotBetween(String value1, String value2) {
            addCriterion("dj_baocuntj not between", value1, value2, "djBaocuntj");
            return (Criteria) this;
        }

        public Criteria andDjBaocunsjIsNull() {
            addCriterion("dj_baocunsj is null");
            return (Criteria) this;
        }

        public Criteria andDjBaocunsjIsNotNull() {
            addCriterion("dj_baocunsj is not null");
            return (Criteria) this;
        }

        public Criteria andDjBaocunsjEqualTo(String value) {
            addCriterion("dj_baocunsj =", value, "djBaocunsj");
            return (Criteria) this;
        }

        public Criteria andDjBaocunsjNotEqualTo(String value) {
            addCriterion("dj_baocunsj <>", value, "djBaocunsj");
            return (Criteria) this;
        }

        public Criteria andDjBaocunsjGreaterThan(String value) {
            addCriterion("dj_baocunsj >", value, "djBaocunsj");
            return (Criteria) this;
        }

        public Criteria andDjBaocunsjGreaterThanOrEqualTo(String value) {
            addCriterion("dj_baocunsj >=", value, "djBaocunsj");
            return (Criteria) this;
        }

        public Criteria andDjBaocunsjLessThan(String value) {
            addCriterion("dj_baocunsj <", value, "djBaocunsj");
            return (Criteria) this;
        }

        public Criteria andDjBaocunsjLessThanOrEqualTo(String value) {
            addCriterion("dj_baocunsj <=", value, "djBaocunsj");
            return (Criteria) this;
        }

        public Criteria andDjBaocunsjLike(String value) {
            addCriterion("dj_baocunsj like", value, "djBaocunsj");
            return (Criteria) this;
        }

        public Criteria andDjBaocunsjNotLike(String value) {
            addCriterion("dj_baocunsj not like", value, "djBaocunsj");
            return (Criteria) this;
        }

        public Criteria andDjBaocunsjIn(List<String> values) {
            addCriterion("dj_baocunsj in", values, "djBaocunsj");
            return (Criteria) this;
        }

        public Criteria andDjBaocunsjNotIn(List<String> values) {
            addCriterion("dj_baocunsj not in", values, "djBaocunsj");
            return (Criteria) this;
        }

        public Criteria andDjBaocunsjBetween(String value1, String value2) {
            addCriterion("dj_baocunsj between", value1, value2, "djBaocunsj");
            return (Criteria) this;
        }

        public Criteria andDjBaocunsjNotBetween(String value1, String value2) {
            addCriterion("dj_baocunsj not between", value1, value2, "djBaocunsj");
            return (Criteria) this;
        }

        public Criteria andDjJibenqkIsNull() {
            addCriterion("dj_jibenqk is null");
            return (Criteria) this;
        }

        public Criteria andDjJibenqkIsNotNull() {
            addCriterion("dj_jibenqk is not null");
            return (Criteria) this;
        }

        public Criteria andDjJibenqkEqualTo(String value) {
            addCriterion("dj_jibenqk =", value, "djJibenqk");
            return (Criteria) this;
        }

        public Criteria andDjJibenqkNotEqualTo(String value) {
            addCriterion("dj_jibenqk <>", value, "djJibenqk");
            return (Criteria) this;
        }

        public Criteria andDjJibenqkGreaterThan(String value) {
            addCriterion("dj_jibenqk >", value, "djJibenqk");
            return (Criteria) this;
        }

        public Criteria andDjJibenqkGreaterThanOrEqualTo(String value) {
            addCriterion("dj_jibenqk >=", value, "djJibenqk");
            return (Criteria) this;
        }

        public Criteria andDjJibenqkLessThan(String value) {
            addCriterion("dj_jibenqk <", value, "djJibenqk");
            return (Criteria) this;
        }

        public Criteria andDjJibenqkLessThanOrEqualTo(String value) {
            addCriterion("dj_jibenqk <=", value, "djJibenqk");
            return (Criteria) this;
        }

        public Criteria andDjJibenqkLike(String value) {
            addCriterion("dj_jibenqk like", value, "djJibenqk");
            return (Criteria) this;
        }

        public Criteria andDjJibenqkNotLike(String value) {
            addCriterion("dj_jibenqk not like", value, "djJibenqk");
            return (Criteria) this;
        }

        public Criteria andDjJibenqkIn(List<String> values) {
            addCriterion("dj_jibenqk in", values, "djJibenqk");
            return (Criteria) this;
        }

        public Criteria andDjJibenqkNotIn(List<String> values) {
            addCriterion("dj_jibenqk not in", values, "djJibenqk");
            return (Criteria) this;
        }

        public Criteria andDjJibenqkBetween(String value1, String value2) {
            addCriterion("dj_jibenqk between", value1, value2, "djJibenqk");
            return (Criteria) this;
        }

        public Criteria andDjJibenqkNotBetween(String value1, String value2) {
            addCriterion("dj_jibenqk not between", value1, value2, "djJibenqk");
            return (Criteria) this;
        }

        public Criteria andDjHuodeddIsNull() {
            addCriterion("dj_huodedd is null");
            return (Criteria) this;
        }

        public Criteria andDjHuodeddIsNotNull() {
            addCriterion("dj_huodedd is not null");
            return (Criteria) this;
        }

        public Criteria andDjHuodeddEqualTo(String value) {
            addCriterion("dj_huodedd =", value, "djHuodedd");
            return (Criteria) this;
        }

        public Criteria andDjHuodeddNotEqualTo(String value) {
            addCriterion("dj_huodedd <>", value, "djHuodedd");
            return (Criteria) this;
        }

        public Criteria andDjHuodeddGreaterThan(String value) {
            addCriterion("dj_huodedd >", value, "djHuodedd");
            return (Criteria) this;
        }

        public Criteria andDjHuodeddGreaterThanOrEqualTo(String value) {
            addCriterion("dj_huodedd >=", value, "djHuodedd");
            return (Criteria) this;
        }

        public Criteria andDjHuodeddLessThan(String value) {
            addCriterion("dj_huodedd <", value, "djHuodedd");
            return (Criteria) this;
        }

        public Criteria andDjHuodeddLessThanOrEqualTo(String value) {
            addCriterion("dj_huodedd <=", value, "djHuodedd");
            return (Criteria) this;
        }

        public Criteria andDjHuodeddLike(String value) {
            addCriterion("dj_huodedd like", value, "djHuodedd");
            return (Criteria) this;
        }

        public Criteria andDjHuodeddNotLike(String value) {
            addCriterion("dj_huodedd not like", value, "djHuodedd");
            return (Criteria) this;
        }

        public Criteria andDjHuodeddIn(List<String> values) {
            addCriterion("dj_huodedd in", values, "djHuodedd");
            return (Criteria) this;
        }

        public Criteria andDjHuodeddNotIn(List<String> values) {
            addCriterion("dj_huodedd not in", values, "djHuodedd");
            return (Criteria) this;
        }

        public Criteria andDjHuodeddBetween(String value1, String value2) {
            addCriterion("dj_huodedd between", value1, value2, "djHuodedd");
            return (Criteria) this;
        }

        public Criteria andDjHuodeddNotBetween(String value1, String value2) {
            addCriterion("dj_huodedd not between", value1, value2, "djHuodedd");
            return (Criteria) this;
        }

        public Criteria andDjBaocunwzIsNull() {
            addCriterion("dj_baocunwz is null");
            return (Criteria) this;
        }

        public Criteria andDjBaocunwzIsNotNull() {
            addCriterion("dj_baocunwz is not null");
            return (Criteria) this;
        }

        public Criteria andDjBaocunwzEqualTo(String value) {
            addCriterion("dj_baocunwz =", value, "djBaocunwz");
            return (Criteria) this;
        }

        public Criteria andDjBaocunwzNotEqualTo(String value) {
            addCriterion("dj_baocunwz <>", value, "djBaocunwz");
            return (Criteria) this;
        }

        public Criteria andDjBaocunwzGreaterThan(String value) {
            addCriterion("dj_baocunwz >", value, "djBaocunwz");
            return (Criteria) this;
        }

        public Criteria andDjBaocunwzGreaterThanOrEqualTo(String value) {
            addCriterion("dj_baocunwz >=", value, "djBaocunwz");
            return (Criteria) this;
        }

        public Criteria andDjBaocunwzLessThan(String value) {
            addCriterion("dj_baocunwz <", value, "djBaocunwz");
            return (Criteria) this;
        }

        public Criteria andDjBaocunwzLessThanOrEqualTo(String value) {
            addCriterion("dj_baocunwz <=", value, "djBaocunwz");
            return (Criteria) this;
        }

        public Criteria andDjBaocunwzLike(String value) {
            addCriterion("dj_baocunwz like", value, "djBaocunwz");
            return (Criteria) this;
        }

        public Criteria andDjBaocunwzNotLike(String value) {
            addCriterion("dj_baocunwz not like", value, "djBaocunwz");
            return (Criteria) this;
        }

        public Criteria andDjBaocunwzIn(List<String> values) {
            addCriterion("dj_baocunwz in", values, "djBaocunwz");
            return (Criteria) this;
        }

        public Criteria andDjBaocunwzNotIn(List<String> values) {
            addCriterion("dj_baocunwz not in", values, "djBaocunwz");
            return (Criteria) this;
        }

        public Criteria andDjBaocunwzBetween(String value1, String value2) {
            addCriterion("dj_baocunwz between", value1, value2, "djBaocunwz");
            return (Criteria) this;
        }

        public Criteria andDjBaocunwzNotBetween(String value1, String value2) {
            addCriterion("dj_baocunwz not between", value1, value2, "djBaocunwz");
            return (Criteria) this;
        }

        public Criteria andDjLianlrIsNull() {
            addCriterion("dj_lianlr is null");
            return (Criteria) this;
        }

        public Criteria andDjLianlrIsNotNull() {
            addCriterion("dj_lianlr is not null");
            return (Criteria) this;
        }

        public Criteria andDjLianlrEqualTo(String value) {
            addCriterion("dj_lianlr =", value, "djLianlr");
            return (Criteria) this;
        }

        public Criteria andDjLianlrNotEqualTo(String value) {
            addCriterion("dj_lianlr <>", value, "djLianlr");
            return (Criteria) this;
        }

        public Criteria andDjLianlrGreaterThan(String value) {
            addCriterion("dj_lianlr >", value, "djLianlr");
            return (Criteria) this;
        }

        public Criteria andDjLianlrGreaterThanOrEqualTo(String value) {
            addCriterion("dj_lianlr >=", value, "djLianlr");
            return (Criteria) this;
        }

        public Criteria andDjLianlrLessThan(String value) {
            addCriterion("dj_lianlr <", value, "djLianlr");
            return (Criteria) this;
        }

        public Criteria andDjLianlrLessThanOrEqualTo(String value) {
            addCriterion("dj_lianlr <=", value, "djLianlr");
            return (Criteria) this;
        }

        public Criteria andDjLianlrLike(String value) {
            addCriterion("dj_lianlr like", value, "djLianlr");
            return (Criteria) this;
        }

        public Criteria andDjLianlrNotLike(String value) {
            addCriterion("dj_lianlr not like", value, "djLianlr");
            return (Criteria) this;
        }

        public Criteria andDjLianlrIn(List<String> values) {
            addCriterion("dj_lianlr in", values, "djLianlr");
            return (Criteria) this;
        }

        public Criteria andDjLianlrNotIn(List<String> values) {
            addCriterion("dj_lianlr not in", values, "djLianlr");
            return (Criteria) this;
        }

        public Criteria andDjLianlrBetween(String value1, String value2) {
            addCriterion("dj_lianlr between", value1, value2, "djLianlr");
            return (Criteria) this;
        }

        public Criteria andDjLianlrNotBetween(String value1, String value2) {
            addCriterion("dj_lianlr not between", value1, value2, "djLianlr");
            return (Criteria) this;
        }

        public Criteria andDjLianldhIsNull() {
            addCriterion("dj_lianldh is null");
            return (Criteria) this;
        }

        public Criteria andDjLianldhIsNotNull() {
            addCriterion("dj_lianldh is not null");
            return (Criteria) this;
        }

        public Criteria andDjLianldhEqualTo(String value) {
            addCriterion("dj_lianldh =", value, "djLianldh");
            return (Criteria) this;
        }

        public Criteria andDjLianldhNotEqualTo(String value) {
            addCriterion("dj_lianldh <>", value, "djLianldh");
            return (Criteria) this;
        }

        public Criteria andDjLianldhGreaterThan(String value) {
            addCriterion("dj_lianldh >", value, "djLianldh");
            return (Criteria) this;
        }

        public Criteria andDjLianldhGreaterThanOrEqualTo(String value) {
            addCriterion("dj_lianldh >=", value, "djLianldh");
            return (Criteria) this;
        }

        public Criteria andDjLianldhLessThan(String value) {
            addCriterion("dj_lianldh <", value, "djLianldh");
            return (Criteria) this;
        }

        public Criteria andDjLianldhLessThanOrEqualTo(String value) {
            addCriterion("dj_lianldh <=", value, "djLianldh");
            return (Criteria) this;
        }

        public Criteria andDjLianldhLike(String value) {
            addCriterion("dj_lianldh like", value, "djLianldh");
            return (Criteria) this;
        }

        public Criteria andDjLianldhNotLike(String value) {
            addCriterion("dj_lianldh not like", value, "djLianldh");
            return (Criteria) this;
        }

        public Criteria andDjLianldhIn(List<String> values) {
            addCriterion("dj_lianldh in", values, "djLianldh");
            return (Criteria) this;
        }

        public Criteria andDjLianldhNotIn(List<String> values) {
            addCriterion("dj_lianldh not in", values, "djLianldh");
            return (Criteria) this;
        }

        public Criteria andDjLianldhBetween(String value1, String value2) {
            addCriterion("dj_lianldh between", value1, value2, "djLianldh");
            return (Criteria) this;
        }

        public Criteria andDjLianldhNotBetween(String value1, String value2) {
            addCriterion("dj_lianldh not between", value1, value2, "djLianldh");
            return (Criteria) this;
        }

        public Criteria andDjFuzerenIsNull() {
            addCriterion("dj_fuzeren is null");
            return (Criteria) this;
        }

        public Criteria andDjFuzerenIsNotNull() {
            addCriterion("dj_fuzeren is not null");
            return (Criteria) this;
        }

        public Criteria andDjFuzerenEqualTo(String value) {
            addCriterion("dj_fuzeren =", value, "djFuzeren");
            return (Criteria) this;
        }

        public Criteria andDjFuzerenNotEqualTo(String value) {
            addCriterion("dj_fuzeren <>", value, "djFuzeren");
            return (Criteria) this;
        }

        public Criteria andDjFuzerenGreaterThan(String value) {
            addCriterion("dj_fuzeren >", value, "djFuzeren");
            return (Criteria) this;
        }

        public Criteria andDjFuzerenGreaterThanOrEqualTo(String value) {
            addCriterion("dj_fuzeren >=", value, "djFuzeren");
            return (Criteria) this;
        }

        public Criteria andDjFuzerenLessThan(String value) {
            addCriterion("dj_fuzeren <", value, "djFuzeren");
            return (Criteria) this;
        }

        public Criteria andDjFuzerenLessThanOrEqualTo(String value) {
            addCriterion("dj_fuzeren <=", value, "djFuzeren");
            return (Criteria) this;
        }

        public Criteria andDjFuzerenLike(String value) {
            addCriterion("dj_fuzeren like", value, "djFuzeren");
            return (Criteria) this;
        }

        public Criteria andDjFuzerenNotLike(String value) {
            addCriterion("dj_fuzeren not like", value, "djFuzeren");
            return (Criteria) this;
        }

        public Criteria andDjFuzerenIn(List<String> values) {
            addCriterion("dj_fuzeren in", values, "djFuzeren");
            return (Criteria) this;
        }

        public Criteria andDjFuzerenNotIn(List<String> values) {
            addCriterion("dj_fuzeren not in", values, "djFuzeren");
            return (Criteria) this;
        }

        public Criteria andDjFuzerenBetween(String value1, String value2) {
            addCriterion("dj_fuzeren between", value1, value2, "djFuzeren");
            return (Criteria) this;
        }

        public Criteria andDjFuzerenNotBetween(String value1, String value2) {
            addCriterion("dj_fuzeren not between", value1, value2, "djFuzeren");
            return (Criteria) this;
        }

        public Criteria andDjFuzerendhIsNull() {
            addCriterion("dj_fuzerendh is null");
            return (Criteria) this;
        }

        public Criteria andDjFuzerendhIsNotNull() {
            addCriterion("dj_fuzerendh is not null");
            return (Criteria) this;
        }

        public Criteria andDjFuzerendhEqualTo(String value) {
            addCriterion("dj_fuzerendh =", value, "djFuzerendh");
            return (Criteria) this;
        }

        public Criteria andDjFuzerendhNotEqualTo(String value) {
            addCriterion("dj_fuzerendh <>", value, "djFuzerendh");
            return (Criteria) this;
        }

        public Criteria andDjFuzerendhGreaterThan(String value) {
            addCriterion("dj_fuzerendh >", value, "djFuzerendh");
            return (Criteria) this;
        }

        public Criteria andDjFuzerendhGreaterThanOrEqualTo(String value) {
            addCriterion("dj_fuzerendh >=", value, "djFuzerendh");
            return (Criteria) this;
        }

        public Criteria andDjFuzerendhLessThan(String value) {
            addCriterion("dj_fuzerendh <", value, "djFuzerendh");
            return (Criteria) this;
        }

        public Criteria andDjFuzerendhLessThanOrEqualTo(String value) {
            addCriterion("dj_fuzerendh <=", value, "djFuzerendh");
            return (Criteria) this;
        }

        public Criteria andDjFuzerendhLike(String value) {
            addCriterion("dj_fuzerendh like", value, "djFuzerendh");
            return (Criteria) this;
        }

        public Criteria andDjFuzerendhNotLike(String value) {
            addCriterion("dj_fuzerendh not like", value, "djFuzerendh");
            return (Criteria) this;
        }

        public Criteria andDjFuzerendhIn(List<String> values) {
            addCriterion("dj_fuzerendh in", values, "djFuzerendh");
            return (Criteria) this;
        }

        public Criteria andDjFuzerendhNotIn(List<String> values) {
            addCriterion("dj_fuzerendh not in", values, "djFuzerendh");
            return (Criteria) this;
        }

        public Criteria andDjFuzerendhBetween(String value1, String value2) {
            addCriterion("dj_fuzerendh between", value1, value2, "djFuzerendh");
            return (Criteria) this;
        }

        public Criteria andDjFuzerendhNotBetween(String value1, String value2) {
            addCriterion("dj_fuzerendh not between", value1, value2, "djFuzerendh");
            return (Criteria) this;
        }

        public Criteria andDjBy1IsNull() {
            addCriterion("dj_by1 is null");
            return (Criteria) this;
        }

        public Criteria andDjBy1IsNotNull() {
            addCriterion("dj_by1 is not null");
            return (Criteria) this;
        }

        public Criteria andDjBy1EqualTo(String value) {
            addCriterion("dj_by1 =", value, "djBy1");
            return (Criteria) this;
        }

        public Criteria andDjBy1NotEqualTo(String value) {
            addCriterion("dj_by1 <>", value, "djBy1");
            return (Criteria) this;
        }

        public Criteria andDjBy1GreaterThan(String value) {
            addCriterion("dj_by1 >", value, "djBy1");
            return (Criteria) this;
        }

        public Criteria andDjBy1GreaterThanOrEqualTo(String value) {
            addCriterion("dj_by1 >=", value, "djBy1");
            return (Criteria) this;
        }

        public Criteria andDjBy1LessThan(String value) {
            addCriterion("dj_by1 <", value, "djBy1");
            return (Criteria) this;
        }

        public Criteria andDjBy1LessThanOrEqualTo(String value) {
            addCriterion("dj_by1 <=", value, "djBy1");
            return (Criteria) this;
        }

        public Criteria andDjBy1Like(String value) {
            addCriterion("dj_by1 like", value, "djBy1");
            return (Criteria) this;
        }

        public Criteria andDjBy1NotLike(String value) {
            addCriterion("dj_by1 not like", value, "djBy1");
            return (Criteria) this;
        }

        public Criteria andDjBy1In(List<String> values) {
            addCriterion("dj_by1 in", values, "djBy1");
            return (Criteria) this;
        }

        public Criteria andDjBy1NotIn(List<String> values) {
            addCriterion("dj_by1 not in", values, "djBy1");
            return (Criteria) this;
        }

        public Criteria andDjBy1Between(String value1, String value2) {
            addCriterion("dj_by1 between", value1, value2, "djBy1");
            return (Criteria) this;
        }

        public Criteria andDjBy1NotBetween(String value1, String value2) {
            addCriterion("dj_by1 not between", value1, value2, "djBy1");
            return (Criteria) this;
        }

        public Criteria andDjBy2IsNull() {
            addCriterion("dj_by2 is null");
            return (Criteria) this;
        }

        public Criteria andDjBy2IsNotNull() {
            addCriterion("dj_by2 is not null");
            return (Criteria) this;
        }

        public Criteria andDjBy2EqualTo(String value) {
            addCriterion("dj_by2 =", value, "djBy2");
            return (Criteria) this;
        }

        public Criteria andDjBy2NotEqualTo(String value) {
            addCriterion("dj_by2 <>", value, "djBy2");
            return (Criteria) this;
        }

        public Criteria andDjBy2GreaterThan(String value) {
            addCriterion("dj_by2 >", value, "djBy2");
            return (Criteria) this;
        }

        public Criteria andDjBy2GreaterThanOrEqualTo(String value) {
            addCriterion("dj_by2 >=", value, "djBy2");
            return (Criteria) this;
        }

        public Criteria andDjBy2LessThan(String value) {
            addCriterion("dj_by2 <", value, "djBy2");
            return (Criteria) this;
        }

        public Criteria andDjBy2LessThanOrEqualTo(String value) {
            addCriterion("dj_by2 <=", value, "djBy2");
            return (Criteria) this;
        }

        public Criteria andDjBy2Like(String value) {
            addCriterion("dj_by2 like", value, "djBy2");
            return (Criteria) this;
        }

        public Criteria andDjBy2NotLike(String value) {
            addCriterion("dj_by2 not like", value, "djBy2");
            return (Criteria) this;
        }

        public Criteria andDjBy2In(List<String> values) {
            addCriterion("dj_by2 in", values, "djBy2");
            return (Criteria) this;
        }

        public Criteria andDjBy2NotIn(List<String> values) {
            addCriterion("dj_by2 not in", values, "djBy2");
            return (Criteria) this;
        }

        public Criteria andDjBy2Between(String value1, String value2) {
            addCriterion("dj_by2 between", value1, value2, "djBy2");
            return (Criteria) this;
        }

        public Criteria andDjBy2NotBetween(String value1, String value2) {
            addCriterion("dj_by2 not between", value1, value2, "djBy2");
            return (Criteria) this;
        }

        public Criteria andDjBy3IsNull() {
            addCriterion("dj_by3 is null");
            return (Criteria) this;
        }

        public Criteria andDjBy3IsNotNull() {
            addCriterion("dj_by3 is not null");
            return (Criteria) this;
        }

        public Criteria andDjBy3EqualTo(String value) {
            addCriterion("dj_by3 =", value, "djBy3");
            return (Criteria) this;
        }

        public Criteria andDjBy3NotEqualTo(String value) {
            addCriterion("dj_by3 <>", value, "djBy3");
            return (Criteria) this;
        }

        public Criteria andDjBy3GreaterThan(String value) {
            addCriterion("dj_by3 >", value, "djBy3");
            return (Criteria) this;
        }

        public Criteria andDjBy3GreaterThanOrEqualTo(String value) {
            addCriterion("dj_by3 >=", value, "djBy3");
            return (Criteria) this;
        }

        public Criteria andDjBy3LessThan(String value) {
            addCriterion("dj_by3 <", value, "djBy3");
            return (Criteria) this;
        }

        public Criteria andDjBy3LessThanOrEqualTo(String value) {
            addCriterion("dj_by3 <=", value, "djBy3");
            return (Criteria) this;
        }

        public Criteria andDjBy3Like(String value) {
            addCriterion("dj_by3 like", value, "djBy3");
            return (Criteria) this;
        }

        public Criteria andDjBy3NotLike(String value) {
            addCriterion("dj_by3 not like", value, "djBy3");
            return (Criteria) this;
        }

        public Criteria andDjBy3In(List<String> values) {
            addCriterion("dj_by3 in", values, "djBy3");
            return (Criteria) this;
        }

        public Criteria andDjBy3NotIn(List<String> values) {
            addCriterion("dj_by3 not in", values, "djBy3");
            return (Criteria) this;
        }

        public Criteria andDjBy3Between(String value1, String value2) {
            addCriterion("dj_by3 between", value1, value2, "djBy3");
            return (Criteria) this;
        }

        public Criteria andDjBy3NotBetween(String value1, String value2) {
            addCriterion("dj_by3 not between", value1, value2, "djBy3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dc_dwjy
     *
     * @mbg.generated do_not_delete_during_merge Sat Jan 23 21:18:05 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dc_dwjy
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}