package com.xsz.customs.model;

public class dcLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_log.Id
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_log.ip
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_log.time
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    private Long time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_log.movement
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    private String movement;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_log.Id
     *
     * @return the value of dc_log.Id
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_log.Id
     *
     * @param id the value for dc_log.Id
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_log.ip
     *
     * @return the value of dc_log.ip
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_log.ip
     *
     * @param ip the value for dc_log.ip
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_log.time
     *
     * @return the value of dc_log.time
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public Long getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_log.time
     *
     * @param time the value for dc_log.time
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public void setTime(Long time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_log.movement
     *
     * @return the value of dc_log.movement
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public String getMovement() {
        return movement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_log.movement
     *
     * @param movement the value for dc_log.movement
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public void setMovement(String movement) {
        this.movement = movement == null ? null : movement.trim();
    }
}