package com.xsz.customs.model;

import java.util.ArrayList;
import java.util.List;

public class dcUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dc_user
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dc_user
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dc_user
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public dcUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dc_user
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDcGqdmIsNull() {
            addCriterion("dc_gqdm is null");
            return (Criteria) this;
        }

        public Criteria andDcGqdmIsNotNull() {
            addCriterion("dc_gqdm is not null");
            return (Criteria) this;
        }

        public Criteria andDcGqdmEqualTo(String value) {
            addCriterion("dc_gqdm =", value, "dcGqdm");
            return (Criteria) this;
        }

        public Criteria andDcGqdmNotEqualTo(String value) {
            addCriterion("dc_gqdm <>", value, "dcGqdm");
            return (Criteria) this;
        }

        public Criteria andDcGqdmGreaterThan(String value) {
            addCriterion("dc_gqdm >", value, "dcGqdm");
            return (Criteria) this;
        }

        public Criteria andDcGqdmGreaterThanOrEqualTo(String value) {
            addCriterion("dc_gqdm >=", value, "dcGqdm");
            return (Criteria) this;
        }

        public Criteria andDcGqdmLessThan(String value) {
            addCriterion("dc_gqdm <", value, "dcGqdm");
            return (Criteria) this;
        }

        public Criteria andDcGqdmLessThanOrEqualTo(String value) {
            addCriterion("dc_gqdm <=", value, "dcGqdm");
            return (Criteria) this;
        }

        public Criteria andDcGqdmLike(String value) {
            addCriterion("dc_gqdm like", value, "dcGqdm");
            return (Criteria) this;
        }

        public Criteria andDcGqdmNotLike(String value) {
            addCriterion("dc_gqdm not like", value, "dcGqdm");
            return (Criteria) this;
        }

        public Criteria andDcGqdmIn(List<String> values) {
            addCriterion("dc_gqdm in", values, "dcGqdm");
            return (Criteria) this;
        }

        public Criteria andDcGqdmNotIn(List<String> values) {
            addCriterion("dc_gqdm not in", values, "dcGqdm");
            return (Criteria) this;
        }

        public Criteria andDcGqdmBetween(String value1, String value2) {
            addCriterion("dc_gqdm between", value1, value2, "dcGqdm");
            return (Criteria) this;
        }

        public Criteria andDcGqdmNotBetween(String value1, String value2) {
            addCriterion("dc_gqdm not between", value1, value2, "dcGqdm");
            return (Criteria) this;
        }

        public Criteria andDcGqdjIsNull() {
            addCriterion("dc_gqdj is null");
            return (Criteria) this;
        }

        public Criteria andDcGqdjIsNotNull() {
            addCriterion("dc_gqdj is not null");
            return (Criteria) this;
        }

        public Criteria andDcGqdjEqualTo(Integer value) {
            addCriterion("dc_gqdj =", value, "dcGqdj");
            return (Criteria) this;
        }

        public Criteria andDcGqdjNotEqualTo(Integer value) {
            addCriterion("dc_gqdj <>", value, "dcGqdj");
            return (Criteria) this;
        }

        public Criteria andDcGqdjGreaterThan(Integer value) {
            addCriterion("dc_gqdj >", value, "dcGqdj");
            return (Criteria) this;
        }

        public Criteria andDcGqdjGreaterThanOrEqualTo(Integer value) {
            addCriterion("dc_gqdj >=", value, "dcGqdj");
            return (Criteria) this;
        }

        public Criteria andDcGqdjLessThan(Integer value) {
            addCriterion("dc_gqdj <", value, "dcGqdj");
            return (Criteria) this;
        }

        public Criteria andDcGqdjLessThanOrEqualTo(Integer value) {
            addCriterion("dc_gqdj <=", value, "dcGqdj");
            return (Criteria) this;
        }

        public Criteria andDcGqdjIn(List<Integer> values) {
            addCriterion("dc_gqdj in", values, "dcGqdj");
            return (Criteria) this;
        }

        public Criteria andDcGqdjNotIn(List<Integer> values) {
            addCriterion("dc_gqdj not in", values, "dcGqdj");
            return (Criteria) this;
        }

        public Criteria andDcGqdjBetween(Integer value1, Integer value2) {
            addCriterion("dc_gqdj between", value1, value2, "dcGqdj");
            return (Criteria) this;
        }

        public Criteria andDcGqdjNotBetween(Integer value1, Integer value2) {
            addCriterion("dc_gqdj not between", value1, value2, "dcGqdj");
            return (Criteria) this;
        }

        public Criteria andDcGqnameIsNull() {
            addCriterion("dc_gqname is null");
            return (Criteria) this;
        }

        public Criteria andDcGqnameIsNotNull() {
            addCriterion("dc_gqname is not null");
            return (Criteria) this;
        }

        public Criteria andDcGqnameEqualTo(String value) {
            addCriterion("dc_gqname =", value, "dcGqname");
            return (Criteria) this;
        }

        public Criteria andDcGqnameNotEqualTo(String value) {
            addCriterion("dc_gqname <>", value, "dcGqname");
            return (Criteria) this;
        }

        public Criteria andDcGqnameGreaterThan(String value) {
            addCriterion("dc_gqname >", value, "dcGqname");
            return (Criteria) this;
        }

        public Criteria andDcGqnameGreaterThanOrEqualTo(String value) {
            addCriterion("dc_gqname >=", value, "dcGqname");
            return (Criteria) this;
        }

        public Criteria andDcGqnameLessThan(String value) {
            addCriterion("dc_gqname <", value, "dcGqname");
            return (Criteria) this;
        }

        public Criteria andDcGqnameLessThanOrEqualTo(String value) {
            addCriterion("dc_gqname <=", value, "dcGqname");
            return (Criteria) this;
        }

        public Criteria andDcGqnameLike(String value) {
            addCriterion("dc_gqname like", value, "dcGqname");
            return (Criteria) this;
        }

        public Criteria andDcGqnameNotLike(String value) {
            addCriterion("dc_gqname not like", value, "dcGqname");
            return (Criteria) this;
        }

        public Criteria andDcGqnameIn(List<String> values) {
            addCriterion("dc_gqname in", values, "dcGqname");
            return (Criteria) this;
        }

        public Criteria andDcGqnameNotIn(List<String> values) {
            addCriterion("dc_gqname not in", values, "dcGqname");
            return (Criteria) this;
        }

        public Criteria andDcGqnameBetween(String value1, String value2) {
            addCriterion("dc_gqname between", value1, value2, "dcGqname");
            return (Criteria) this;
        }

        public Criteria andDcGqnameNotBetween(String value1, String value2) {
            addCriterion("dc_gqname not between", value1, value2, "dcGqname");
            return (Criteria) this;
        }

        public Criteria andDcGqpwordIsNull() {
            addCriterion("dc_gqpword is null");
            return (Criteria) this;
        }

        public Criteria andDcGqpwordIsNotNull() {
            addCriterion("dc_gqpword is not null");
            return (Criteria) this;
        }

        public Criteria andDcGqpwordEqualTo(String value) {
            addCriterion("dc_gqpword =", value, "dcGqpword");
            return (Criteria) this;
        }

        public Criteria andDcGqpwordNotEqualTo(String value) {
            addCriterion("dc_gqpword <>", value, "dcGqpword");
            return (Criteria) this;
        }

        public Criteria andDcGqpwordGreaterThan(String value) {
            addCriterion("dc_gqpword >", value, "dcGqpword");
            return (Criteria) this;
        }

        public Criteria andDcGqpwordGreaterThanOrEqualTo(String value) {
            addCriterion("dc_gqpword >=", value, "dcGqpword");
            return (Criteria) this;
        }

        public Criteria andDcGqpwordLessThan(String value) {
            addCriterion("dc_gqpword <", value, "dcGqpword");
            return (Criteria) this;
        }

        public Criteria andDcGqpwordLessThanOrEqualTo(String value) {
            addCriterion("dc_gqpword <=", value, "dcGqpword");
            return (Criteria) this;
        }

        public Criteria andDcGqpwordLike(String value) {
            addCriterion("dc_gqpword like", value, "dcGqpword");
            return (Criteria) this;
        }

        public Criteria andDcGqpwordNotLike(String value) {
            addCriterion("dc_gqpword not like", value, "dcGqpword");
            return (Criteria) this;
        }

        public Criteria andDcGqpwordIn(List<String> values) {
            addCriterion("dc_gqpword in", values, "dcGqpword");
            return (Criteria) this;
        }

        public Criteria andDcGqpwordNotIn(List<String> values) {
            addCriterion("dc_gqpword not in", values, "dcGqpword");
            return (Criteria) this;
        }

        public Criteria andDcGqpwordBetween(String value1, String value2) {
            addCriterion("dc_gqpword between", value1, value2, "dcGqpword");
            return (Criteria) this;
        }

        public Criteria andDcGqpwordNotBetween(String value1, String value2) {
            addCriterion("dc_gqpword not between", value1, value2, "dcGqpword");
            return (Criteria) this;
        }

        public Criteria andDcShiwukuIsNull() {
            addCriterion("dc_shiwuku is null");
            return (Criteria) this;
        }

        public Criteria andDcShiwukuIsNotNull() {
            addCriterion("dc_shiwuku is not null");
            return (Criteria) this;
        }

        public Criteria andDcShiwukuEqualTo(String value) {
            addCriterion("dc_shiwuku =", value, "dcShiwuku");
            return (Criteria) this;
        }

        public Criteria andDcShiwukuNotEqualTo(String value) {
            addCriterion("dc_shiwuku <>", value, "dcShiwuku");
            return (Criteria) this;
        }

        public Criteria andDcShiwukuGreaterThan(String value) {
            addCriterion("dc_shiwuku >", value, "dcShiwuku");
            return (Criteria) this;
        }

        public Criteria andDcShiwukuGreaterThanOrEqualTo(String value) {
            addCriterion("dc_shiwuku >=", value, "dcShiwuku");
            return (Criteria) this;
        }

        public Criteria andDcShiwukuLessThan(String value) {
            addCriterion("dc_shiwuku <", value, "dcShiwuku");
            return (Criteria) this;
        }

        public Criteria andDcShiwukuLessThanOrEqualTo(String value) {
            addCriterion("dc_shiwuku <=", value, "dcShiwuku");
            return (Criteria) this;
        }

        public Criteria andDcShiwukuLike(String value) {
            addCriterion("dc_shiwuku like", value, "dcShiwuku");
            return (Criteria) this;
        }

        public Criteria andDcShiwukuNotLike(String value) {
            addCriterion("dc_shiwuku not like", value, "dcShiwuku");
            return (Criteria) this;
        }

        public Criteria andDcShiwukuIn(List<String> values) {
            addCriterion("dc_shiwuku in", values, "dcShiwuku");
            return (Criteria) this;
        }

        public Criteria andDcShiwukuNotIn(List<String> values) {
            addCriterion("dc_shiwuku not in", values, "dcShiwuku");
            return (Criteria) this;
        }

        public Criteria andDcShiwukuBetween(String value1, String value2) {
            addCriterion("dc_shiwuku between", value1, value2, "dcShiwuku");
            return (Criteria) this;
        }

        public Criteria andDcShiwukuNotBetween(String value1, String value2) {
            addCriterion("dc_shiwuku not between", value1, value2, "dcShiwuku");
            return (Criteria) this;
        }

        public Criteria andDcShujukuIsNull() {
            addCriterion("dc_shujuku is null");
            return (Criteria) this;
        }

        public Criteria andDcShujukuIsNotNull() {
            addCriterion("dc_shujuku is not null");
            return (Criteria) this;
        }

        public Criteria andDcShujukuEqualTo(String value) {
            addCriterion("dc_shujuku =", value, "dcShujuku");
            return (Criteria) this;
        }

        public Criteria andDcShujukuNotEqualTo(String value) {
            addCriterion("dc_shujuku <>", value, "dcShujuku");
            return (Criteria) this;
        }

        public Criteria andDcShujukuGreaterThan(String value) {
            addCriterion("dc_shujuku >", value, "dcShujuku");
            return (Criteria) this;
        }

        public Criteria andDcShujukuGreaterThanOrEqualTo(String value) {
            addCriterion("dc_shujuku >=", value, "dcShujuku");
            return (Criteria) this;
        }

        public Criteria andDcShujukuLessThan(String value) {
            addCriterion("dc_shujuku <", value, "dcShujuku");
            return (Criteria) this;
        }

        public Criteria andDcShujukuLessThanOrEqualTo(String value) {
            addCriterion("dc_shujuku <=", value, "dcShujuku");
            return (Criteria) this;
        }

        public Criteria andDcShujukuLike(String value) {
            addCriterion("dc_shujuku like", value, "dcShujuku");
            return (Criteria) this;
        }

        public Criteria andDcShujukuNotLike(String value) {
            addCriterion("dc_shujuku not like", value, "dcShujuku");
            return (Criteria) this;
        }

        public Criteria andDcShujukuIn(List<String> values) {
            addCriterion("dc_shujuku in", values, "dcShujuku");
            return (Criteria) this;
        }

        public Criteria andDcShujukuNotIn(List<String> values) {
            addCriterion("dc_shujuku not in", values, "dcShujuku");
            return (Criteria) this;
        }

        public Criteria andDcShujukuBetween(String value1, String value2) {
            addCriterion("dc_shujuku between", value1, value2, "dcShujuku");
            return (Criteria) this;
        }

        public Criteria andDcShujukuNotBetween(String value1, String value2) {
            addCriterion("dc_shujuku not between", value1, value2, "dcShujuku");
            return (Criteria) this;
        }

        public Criteria andDcLxrIsNull() {
            addCriterion("dc_lxr is null");
            return (Criteria) this;
        }

        public Criteria andDcLxrIsNotNull() {
            addCriterion("dc_lxr is not null");
            return (Criteria) this;
        }

        public Criteria andDcLxrEqualTo(String value) {
            addCriterion("dc_lxr =", value, "dcLxr");
            return (Criteria) this;
        }

        public Criteria andDcLxrNotEqualTo(String value) {
            addCriterion("dc_lxr <>", value, "dcLxr");
            return (Criteria) this;
        }

        public Criteria andDcLxrGreaterThan(String value) {
            addCriterion("dc_lxr >", value, "dcLxr");
            return (Criteria) this;
        }

        public Criteria andDcLxrGreaterThanOrEqualTo(String value) {
            addCriterion("dc_lxr >=", value, "dcLxr");
            return (Criteria) this;
        }

        public Criteria andDcLxrLessThan(String value) {
            addCriterion("dc_lxr <", value, "dcLxr");
            return (Criteria) this;
        }

        public Criteria andDcLxrLessThanOrEqualTo(String value) {
            addCriterion("dc_lxr <=", value, "dcLxr");
            return (Criteria) this;
        }

        public Criteria andDcLxrLike(String value) {
            addCriterion("dc_lxr like", value, "dcLxr");
            return (Criteria) this;
        }

        public Criteria andDcLxrNotLike(String value) {
            addCriterion("dc_lxr not like", value, "dcLxr");
            return (Criteria) this;
        }

        public Criteria andDcLxrIn(List<String> values) {
            addCriterion("dc_lxr in", values, "dcLxr");
            return (Criteria) this;
        }

        public Criteria andDcLxrNotIn(List<String> values) {
            addCriterion("dc_lxr not in", values, "dcLxr");
            return (Criteria) this;
        }

        public Criteria andDcLxrBetween(String value1, String value2) {
            addCriterion("dc_lxr between", value1, value2, "dcLxr");
            return (Criteria) this;
        }

        public Criteria andDcLxrNotBetween(String value1, String value2) {
            addCriterion("dc_lxr not between", value1, value2, "dcLxr");
            return (Criteria) this;
        }

        public Criteria andDcLxsjIsNull() {
            addCriterion("dc_lxsj is null");
            return (Criteria) this;
        }

        public Criteria andDcLxsjIsNotNull() {
            addCriterion("dc_lxsj is not null");
            return (Criteria) this;
        }

        public Criteria andDcLxsjEqualTo(String value) {
            addCriterion("dc_lxsj =", value, "dcLxsj");
            return (Criteria) this;
        }

        public Criteria andDcLxsjNotEqualTo(String value) {
            addCriterion("dc_lxsj <>", value, "dcLxsj");
            return (Criteria) this;
        }

        public Criteria andDcLxsjGreaterThan(String value) {
            addCriterion("dc_lxsj >", value, "dcLxsj");
            return (Criteria) this;
        }

        public Criteria andDcLxsjGreaterThanOrEqualTo(String value) {
            addCriterion("dc_lxsj >=", value, "dcLxsj");
            return (Criteria) this;
        }

        public Criteria andDcLxsjLessThan(String value) {
            addCriterion("dc_lxsj <", value, "dcLxsj");
            return (Criteria) this;
        }

        public Criteria andDcLxsjLessThanOrEqualTo(String value) {
            addCriterion("dc_lxsj <=", value, "dcLxsj");
            return (Criteria) this;
        }

        public Criteria andDcLxsjLike(String value) {
            addCriterion("dc_lxsj like", value, "dcLxsj");
            return (Criteria) this;
        }

        public Criteria andDcLxsjNotLike(String value) {
            addCriterion("dc_lxsj not like", value, "dcLxsj");
            return (Criteria) this;
        }

        public Criteria andDcLxsjIn(List<String> values) {
            addCriterion("dc_lxsj in", values, "dcLxsj");
            return (Criteria) this;
        }

        public Criteria andDcLxsjNotIn(List<String> values) {
            addCriterion("dc_lxsj not in", values, "dcLxsj");
            return (Criteria) this;
        }

        public Criteria andDcLxsjBetween(String value1, String value2) {
            addCriterion("dc_lxsj between", value1, value2, "dcLxsj");
            return (Criteria) this;
        }

        public Criteria andDcLxsjNotBetween(String value1, String value2) {
            addCriterion("dc_lxsj not between", value1, value2, "dcLxsj");
            return (Criteria) this;
        }

        public Criteria andDcLxdhIsNull() {
            addCriterion("dc_lxdh is null");
            return (Criteria) this;
        }

        public Criteria andDcLxdhIsNotNull() {
            addCriterion("dc_lxdh is not null");
            return (Criteria) this;
        }

        public Criteria andDcLxdhEqualTo(String value) {
            addCriterion("dc_lxdh =", value, "dcLxdh");
            return (Criteria) this;
        }

        public Criteria andDcLxdhNotEqualTo(String value) {
            addCriterion("dc_lxdh <>", value, "dcLxdh");
            return (Criteria) this;
        }

        public Criteria andDcLxdhGreaterThan(String value) {
            addCriterion("dc_lxdh >", value, "dcLxdh");
            return (Criteria) this;
        }

        public Criteria andDcLxdhGreaterThanOrEqualTo(String value) {
            addCriterion("dc_lxdh >=", value, "dcLxdh");
            return (Criteria) this;
        }

        public Criteria andDcLxdhLessThan(String value) {
            addCriterion("dc_lxdh <", value, "dcLxdh");
            return (Criteria) this;
        }

        public Criteria andDcLxdhLessThanOrEqualTo(String value) {
            addCriterion("dc_lxdh <=", value, "dcLxdh");
            return (Criteria) this;
        }

        public Criteria andDcLxdhLike(String value) {
            addCriterion("dc_lxdh like", value, "dcLxdh");
            return (Criteria) this;
        }

        public Criteria andDcLxdhNotLike(String value) {
            addCriterion("dc_lxdh not like", value, "dcLxdh");
            return (Criteria) this;
        }

        public Criteria andDcLxdhIn(List<String> values) {
            addCriterion("dc_lxdh in", values, "dcLxdh");
            return (Criteria) this;
        }

        public Criteria andDcLxdhNotIn(List<String> values) {
            addCriterion("dc_lxdh not in", values, "dcLxdh");
            return (Criteria) this;
        }

        public Criteria andDcLxdhBetween(String value1, String value2) {
            addCriterion("dc_lxdh between", value1, value2, "dcLxdh");
            return (Criteria) this;
        }

        public Criteria andDcLxdhNotBetween(String value1, String value2) {
            addCriterion("dc_lxdh not between", value1, value2, "dcLxdh");
            return (Criteria) this;
        }

        public Criteria andDcDzyjIsNull() {
            addCriterion("dc_dzyj is null");
            return (Criteria) this;
        }

        public Criteria andDcDzyjIsNotNull() {
            addCriterion("dc_dzyj is not null");
            return (Criteria) this;
        }

        public Criteria andDcDzyjEqualTo(String value) {
            addCriterion("dc_dzyj =", value, "dcDzyj");
            return (Criteria) this;
        }

        public Criteria andDcDzyjNotEqualTo(String value) {
            addCriterion("dc_dzyj <>", value, "dcDzyj");
            return (Criteria) this;
        }

        public Criteria andDcDzyjGreaterThan(String value) {
            addCriterion("dc_dzyj >", value, "dcDzyj");
            return (Criteria) this;
        }

        public Criteria andDcDzyjGreaterThanOrEqualTo(String value) {
            addCriterion("dc_dzyj >=", value, "dcDzyj");
            return (Criteria) this;
        }

        public Criteria andDcDzyjLessThan(String value) {
            addCriterion("dc_dzyj <", value, "dcDzyj");
            return (Criteria) this;
        }

        public Criteria andDcDzyjLessThanOrEqualTo(String value) {
            addCriterion("dc_dzyj <=", value, "dcDzyj");
            return (Criteria) this;
        }

        public Criteria andDcDzyjLike(String value) {
            addCriterion("dc_dzyj like", value, "dcDzyj");
            return (Criteria) this;
        }

        public Criteria andDcDzyjNotLike(String value) {
            addCriterion("dc_dzyj not like", value, "dcDzyj");
            return (Criteria) this;
        }

        public Criteria andDcDzyjIn(List<String> values) {
            addCriterion("dc_dzyj in", values, "dcDzyj");
            return (Criteria) this;
        }

        public Criteria andDcDzyjNotIn(List<String> values) {
            addCriterion("dc_dzyj not in", values, "dcDzyj");
            return (Criteria) this;
        }

        public Criteria andDcDzyjBetween(String value1, String value2) {
            addCriterion("dc_dzyj between", value1, value2, "dcDzyj");
            return (Criteria) this;
        }

        public Criteria andDcDzyjNotBetween(String value1, String value2) {
            addCriterion("dc_dzyj not between", value1, value2, "dcDzyj");
            return (Criteria) this;
        }

        public Criteria andDcWjlxrIsNull() {
            addCriterion("dc_wjlxr is null");
            return (Criteria) this;
        }

        public Criteria andDcWjlxrIsNotNull() {
            addCriterion("dc_wjlxr is not null");
            return (Criteria) this;
        }

        public Criteria andDcWjlxrEqualTo(String value) {
            addCriterion("dc_wjlxr =", value, "dcWjlxr");
            return (Criteria) this;
        }

        public Criteria andDcWjlxrNotEqualTo(String value) {
            addCriterion("dc_wjlxr <>", value, "dcWjlxr");
            return (Criteria) this;
        }

        public Criteria andDcWjlxrGreaterThan(String value) {
            addCriterion("dc_wjlxr >", value, "dcWjlxr");
            return (Criteria) this;
        }

        public Criteria andDcWjlxrGreaterThanOrEqualTo(String value) {
            addCriterion("dc_wjlxr >=", value, "dcWjlxr");
            return (Criteria) this;
        }

        public Criteria andDcWjlxrLessThan(String value) {
            addCriterion("dc_wjlxr <", value, "dcWjlxr");
            return (Criteria) this;
        }

        public Criteria andDcWjlxrLessThanOrEqualTo(String value) {
            addCriterion("dc_wjlxr <=", value, "dcWjlxr");
            return (Criteria) this;
        }

        public Criteria andDcWjlxrLike(String value) {
            addCriterion("dc_wjlxr like", value, "dcWjlxr");
            return (Criteria) this;
        }

        public Criteria andDcWjlxrNotLike(String value) {
            addCriterion("dc_wjlxr not like", value, "dcWjlxr");
            return (Criteria) this;
        }

        public Criteria andDcWjlxrIn(List<String> values) {
            addCriterion("dc_wjlxr in", values, "dcWjlxr");
            return (Criteria) this;
        }

        public Criteria andDcWjlxrNotIn(List<String> values) {
            addCriterion("dc_wjlxr not in", values, "dcWjlxr");
            return (Criteria) this;
        }

        public Criteria andDcWjlxrBetween(String value1, String value2) {
            addCriterion("dc_wjlxr between", value1, value2, "dcWjlxr");
            return (Criteria) this;
        }

        public Criteria andDcWjlxrNotBetween(String value1, String value2) {
            addCriterion("dc_wjlxr not between", value1, value2, "dcWjlxr");
            return (Criteria) this;
        }

        public Criteria andDcWjlxdhIsNull() {
            addCriterion("dc_wjlxdh is null");
            return (Criteria) this;
        }

        public Criteria andDcWjlxdhIsNotNull() {
            addCriterion("dc_wjlxdh is not null");
            return (Criteria) this;
        }

        public Criteria andDcWjlxdhEqualTo(String value) {
            addCriterion("dc_wjlxdh =", value, "dcWjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcWjlxdhNotEqualTo(String value) {
            addCriterion("dc_wjlxdh <>", value, "dcWjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcWjlxdhGreaterThan(String value) {
            addCriterion("dc_wjlxdh >", value, "dcWjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcWjlxdhGreaterThanOrEqualTo(String value) {
            addCriterion("dc_wjlxdh >=", value, "dcWjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcWjlxdhLessThan(String value) {
            addCriterion("dc_wjlxdh <", value, "dcWjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcWjlxdhLessThanOrEqualTo(String value) {
            addCriterion("dc_wjlxdh <=", value, "dcWjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcWjlxdhLike(String value) {
            addCriterion("dc_wjlxdh like", value, "dcWjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcWjlxdhNotLike(String value) {
            addCriterion("dc_wjlxdh not like", value, "dcWjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcWjlxdhIn(List<String> values) {
            addCriterion("dc_wjlxdh in", values, "dcWjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcWjlxdhNotIn(List<String> values) {
            addCriterion("dc_wjlxdh not in", values, "dcWjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcWjlxdhBetween(String value1, String value2) {
            addCriterion("dc_wjlxdh between", value1, value2, "dcWjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcWjlxdhNotBetween(String value1, String value2) {
            addCriterion("dc_wjlxdh not between", value1, value2, "dcWjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcWjfzrIsNull() {
            addCriterion("dc_wjfzr is null");
            return (Criteria) this;
        }

        public Criteria andDcWjfzrIsNotNull() {
            addCriterion("dc_wjfzr is not null");
            return (Criteria) this;
        }

        public Criteria andDcWjfzrEqualTo(String value) {
            addCriterion("dc_wjfzr =", value, "dcWjfzr");
            return (Criteria) this;
        }

        public Criteria andDcWjfzrNotEqualTo(String value) {
            addCriterion("dc_wjfzr <>", value, "dcWjfzr");
            return (Criteria) this;
        }

        public Criteria andDcWjfzrGreaterThan(String value) {
            addCriterion("dc_wjfzr >", value, "dcWjfzr");
            return (Criteria) this;
        }

        public Criteria andDcWjfzrGreaterThanOrEqualTo(String value) {
            addCriterion("dc_wjfzr >=", value, "dcWjfzr");
            return (Criteria) this;
        }

        public Criteria andDcWjfzrLessThan(String value) {
            addCriterion("dc_wjfzr <", value, "dcWjfzr");
            return (Criteria) this;
        }

        public Criteria andDcWjfzrLessThanOrEqualTo(String value) {
            addCriterion("dc_wjfzr <=", value, "dcWjfzr");
            return (Criteria) this;
        }

        public Criteria andDcWjfzrLike(String value) {
            addCriterion("dc_wjfzr like", value, "dcWjfzr");
            return (Criteria) this;
        }

        public Criteria andDcWjfzrNotLike(String value) {
            addCriterion("dc_wjfzr not like", value, "dcWjfzr");
            return (Criteria) this;
        }

        public Criteria andDcWjfzrIn(List<String> values) {
            addCriterion("dc_wjfzr in", values, "dcWjfzr");
            return (Criteria) this;
        }

        public Criteria andDcWjfzrNotIn(List<String> values) {
            addCriterion("dc_wjfzr not in", values, "dcWjfzr");
            return (Criteria) this;
        }

        public Criteria andDcWjfzrBetween(String value1, String value2) {
            addCriterion("dc_wjfzr between", value1, value2, "dcWjfzr");
            return (Criteria) this;
        }

        public Criteria andDcWjfzrNotBetween(String value1, String value2) {
            addCriterion("dc_wjfzr not between", value1, value2, "dcWjfzr");
            return (Criteria) this;
        }

        public Criteria andDcWjfzdhIsNull() {
            addCriterion("dc_wjfzdh is null");
            return (Criteria) this;
        }

        public Criteria andDcWjfzdhIsNotNull() {
            addCriterion("dc_wjfzdh is not null");
            return (Criteria) this;
        }

        public Criteria andDcWjfzdhEqualTo(String value) {
            addCriterion("dc_wjfzdh =", value, "dcWjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcWjfzdhNotEqualTo(String value) {
            addCriterion("dc_wjfzdh <>", value, "dcWjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcWjfzdhGreaterThan(String value) {
            addCriterion("dc_wjfzdh >", value, "dcWjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcWjfzdhGreaterThanOrEqualTo(String value) {
            addCriterion("dc_wjfzdh >=", value, "dcWjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcWjfzdhLessThan(String value) {
            addCriterion("dc_wjfzdh <", value, "dcWjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcWjfzdhLessThanOrEqualTo(String value) {
            addCriterion("dc_wjfzdh <=", value, "dcWjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcWjfzdhLike(String value) {
            addCriterion("dc_wjfzdh like", value, "dcWjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcWjfzdhNotLike(String value) {
            addCriterion("dc_wjfzdh not like", value, "dcWjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcWjfzdhIn(List<String> values) {
            addCriterion("dc_wjfzdh in", values, "dcWjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcWjfzdhNotIn(List<String> values) {
            addCriterion("dc_wjfzdh not in", values, "dcWjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcWjfzdhBetween(String value1, String value2) {
            addCriterion("dc_wjfzdh between", value1, value2, "dcWjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcWjfzdhNotBetween(String value1, String value2) {
            addCriterion("dc_wjfzdh not between", value1, value2, "dcWjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcDjlxrIsNull() {
            addCriterion("dc_djlxr is null");
            return (Criteria) this;
        }

        public Criteria andDcDjlxrIsNotNull() {
            addCriterion("dc_djlxr is not null");
            return (Criteria) this;
        }

        public Criteria andDcDjlxrEqualTo(String value) {
            addCriterion("dc_djlxr =", value, "dcDjlxr");
            return (Criteria) this;
        }

        public Criteria andDcDjlxrNotEqualTo(String value) {
            addCriterion("dc_djlxr <>", value, "dcDjlxr");
            return (Criteria) this;
        }

        public Criteria andDcDjlxrGreaterThan(String value) {
            addCriterion("dc_djlxr >", value, "dcDjlxr");
            return (Criteria) this;
        }

        public Criteria andDcDjlxrGreaterThanOrEqualTo(String value) {
            addCriterion("dc_djlxr >=", value, "dcDjlxr");
            return (Criteria) this;
        }

        public Criteria andDcDjlxrLessThan(String value) {
            addCriterion("dc_djlxr <", value, "dcDjlxr");
            return (Criteria) this;
        }

        public Criteria andDcDjlxrLessThanOrEqualTo(String value) {
            addCriterion("dc_djlxr <=", value, "dcDjlxr");
            return (Criteria) this;
        }

        public Criteria andDcDjlxrLike(String value) {
            addCriterion("dc_djlxr like", value, "dcDjlxr");
            return (Criteria) this;
        }

        public Criteria andDcDjlxrNotLike(String value) {
            addCriterion("dc_djlxr not like", value, "dcDjlxr");
            return (Criteria) this;
        }

        public Criteria andDcDjlxrIn(List<String> values) {
            addCriterion("dc_djlxr in", values, "dcDjlxr");
            return (Criteria) this;
        }

        public Criteria andDcDjlxrNotIn(List<String> values) {
            addCriterion("dc_djlxr not in", values, "dcDjlxr");
            return (Criteria) this;
        }

        public Criteria andDcDjlxrBetween(String value1, String value2) {
            addCriterion("dc_djlxr between", value1, value2, "dcDjlxr");
            return (Criteria) this;
        }

        public Criteria andDcDjlxrNotBetween(String value1, String value2) {
            addCriterion("dc_djlxr not between", value1, value2, "dcDjlxr");
            return (Criteria) this;
        }

        public Criteria andDcDjlxdhIsNull() {
            addCriterion("dc_djlxdh is null");
            return (Criteria) this;
        }

        public Criteria andDcDjlxdhIsNotNull() {
            addCriterion("dc_djlxdh is not null");
            return (Criteria) this;
        }

        public Criteria andDcDjlxdhEqualTo(String value) {
            addCriterion("dc_djlxdh =", value, "dcDjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcDjlxdhNotEqualTo(String value) {
            addCriterion("dc_djlxdh <>", value, "dcDjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcDjlxdhGreaterThan(String value) {
            addCriterion("dc_djlxdh >", value, "dcDjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcDjlxdhGreaterThanOrEqualTo(String value) {
            addCriterion("dc_djlxdh >=", value, "dcDjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcDjlxdhLessThan(String value) {
            addCriterion("dc_djlxdh <", value, "dcDjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcDjlxdhLessThanOrEqualTo(String value) {
            addCriterion("dc_djlxdh <=", value, "dcDjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcDjlxdhLike(String value) {
            addCriterion("dc_djlxdh like", value, "dcDjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcDjlxdhNotLike(String value) {
            addCriterion("dc_djlxdh not like", value, "dcDjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcDjlxdhIn(List<String> values) {
            addCriterion("dc_djlxdh in", values, "dcDjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcDjlxdhNotIn(List<String> values) {
            addCriterion("dc_djlxdh not in", values, "dcDjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcDjlxdhBetween(String value1, String value2) {
            addCriterion("dc_djlxdh between", value1, value2, "dcDjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcDjlxdhNotBetween(String value1, String value2) {
            addCriterion("dc_djlxdh not between", value1, value2, "dcDjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcDjfzrIsNull() {
            addCriterion("dc_djfzr is null");
            return (Criteria) this;
        }

        public Criteria andDcDjfzrIsNotNull() {
            addCriterion("dc_djfzr is not null");
            return (Criteria) this;
        }

        public Criteria andDcDjfzrEqualTo(String value) {
            addCriterion("dc_djfzr =", value, "dcDjfzr");
            return (Criteria) this;
        }

        public Criteria andDcDjfzrNotEqualTo(String value) {
            addCriterion("dc_djfzr <>", value, "dcDjfzr");
            return (Criteria) this;
        }

        public Criteria andDcDjfzrGreaterThan(String value) {
            addCriterion("dc_djfzr >", value, "dcDjfzr");
            return (Criteria) this;
        }

        public Criteria andDcDjfzrGreaterThanOrEqualTo(String value) {
            addCriterion("dc_djfzr >=", value, "dcDjfzr");
            return (Criteria) this;
        }

        public Criteria andDcDjfzrLessThan(String value) {
            addCriterion("dc_djfzr <", value, "dcDjfzr");
            return (Criteria) this;
        }

        public Criteria andDcDjfzrLessThanOrEqualTo(String value) {
            addCriterion("dc_djfzr <=", value, "dcDjfzr");
            return (Criteria) this;
        }

        public Criteria andDcDjfzrLike(String value) {
            addCriterion("dc_djfzr like", value, "dcDjfzr");
            return (Criteria) this;
        }

        public Criteria andDcDjfzrNotLike(String value) {
            addCriterion("dc_djfzr not like", value, "dcDjfzr");
            return (Criteria) this;
        }

        public Criteria andDcDjfzrIn(List<String> values) {
            addCriterion("dc_djfzr in", values, "dcDjfzr");
            return (Criteria) this;
        }

        public Criteria andDcDjfzrNotIn(List<String> values) {
            addCriterion("dc_djfzr not in", values, "dcDjfzr");
            return (Criteria) this;
        }

        public Criteria andDcDjfzrBetween(String value1, String value2) {
            addCriterion("dc_djfzr between", value1, value2, "dcDjfzr");
            return (Criteria) this;
        }

        public Criteria andDcDjfzrNotBetween(String value1, String value2) {
            addCriterion("dc_djfzr not between", value1, value2, "dcDjfzr");
            return (Criteria) this;
        }

        public Criteria andDcDjfzdhIsNull() {
            addCriterion("dc_djfzdh is null");
            return (Criteria) this;
        }

        public Criteria andDcDjfzdhIsNotNull() {
            addCriterion("dc_djfzdh is not null");
            return (Criteria) this;
        }

        public Criteria andDcDjfzdhEqualTo(String value) {
            addCriterion("dc_djfzdh =", value, "dcDjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcDjfzdhNotEqualTo(String value) {
            addCriterion("dc_djfzdh <>", value, "dcDjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcDjfzdhGreaterThan(String value) {
            addCriterion("dc_djfzdh >", value, "dcDjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcDjfzdhGreaterThanOrEqualTo(String value) {
            addCriterion("dc_djfzdh >=", value, "dcDjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcDjfzdhLessThan(String value) {
            addCriterion("dc_djfzdh <", value, "dcDjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcDjfzdhLessThanOrEqualTo(String value) {
            addCriterion("dc_djfzdh <=", value, "dcDjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcDjfzdhLike(String value) {
            addCriterion("dc_djfzdh like", value, "dcDjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcDjfzdhNotLike(String value) {
            addCriterion("dc_djfzdh not like", value, "dcDjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcDjfzdhIn(List<String> values) {
            addCriterion("dc_djfzdh in", values, "dcDjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcDjfzdhNotIn(List<String> values) {
            addCriterion("dc_djfzdh not in", values, "dcDjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcDjfzdhBetween(String value1, String value2) {
            addCriterion("dc_djfzdh between", value1, value2, "dcDjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcDjfzdhNotBetween(String value1, String value2) {
            addCriterion("dc_djfzdh not between", value1, value2, "dcDjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcZjlxrIsNull() {
            addCriterion("dc_zjlxr is null");
            return (Criteria) this;
        }

        public Criteria andDcZjlxrIsNotNull() {
            addCriterion("dc_zjlxr is not null");
            return (Criteria) this;
        }

        public Criteria andDcZjlxrEqualTo(String value) {
            addCriterion("dc_zjlxr =", value, "dcZjlxr");
            return (Criteria) this;
        }

        public Criteria andDcZjlxrNotEqualTo(String value) {
            addCriterion("dc_zjlxr <>", value, "dcZjlxr");
            return (Criteria) this;
        }

        public Criteria andDcZjlxrGreaterThan(String value) {
            addCriterion("dc_zjlxr >", value, "dcZjlxr");
            return (Criteria) this;
        }

        public Criteria andDcZjlxrGreaterThanOrEqualTo(String value) {
            addCriterion("dc_zjlxr >=", value, "dcZjlxr");
            return (Criteria) this;
        }

        public Criteria andDcZjlxrLessThan(String value) {
            addCriterion("dc_zjlxr <", value, "dcZjlxr");
            return (Criteria) this;
        }

        public Criteria andDcZjlxrLessThanOrEqualTo(String value) {
            addCriterion("dc_zjlxr <=", value, "dcZjlxr");
            return (Criteria) this;
        }

        public Criteria andDcZjlxrLike(String value) {
            addCriterion("dc_zjlxr like", value, "dcZjlxr");
            return (Criteria) this;
        }

        public Criteria andDcZjlxrNotLike(String value) {
            addCriterion("dc_zjlxr not like", value, "dcZjlxr");
            return (Criteria) this;
        }

        public Criteria andDcZjlxrIn(List<String> values) {
            addCriterion("dc_zjlxr in", values, "dcZjlxr");
            return (Criteria) this;
        }

        public Criteria andDcZjlxrNotIn(List<String> values) {
            addCriterion("dc_zjlxr not in", values, "dcZjlxr");
            return (Criteria) this;
        }

        public Criteria andDcZjlxrBetween(String value1, String value2) {
            addCriterion("dc_zjlxr between", value1, value2, "dcZjlxr");
            return (Criteria) this;
        }

        public Criteria andDcZjlxrNotBetween(String value1, String value2) {
            addCriterion("dc_zjlxr not between", value1, value2, "dcZjlxr");
            return (Criteria) this;
        }

        public Criteria andDcZjlxdhIsNull() {
            addCriterion("dc_zjlxdh is null");
            return (Criteria) this;
        }

        public Criteria andDcZjlxdhIsNotNull() {
            addCriterion("dc_zjlxdh is not null");
            return (Criteria) this;
        }

        public Criteria andDcZjlxdhEqualTo(String value) {
            addCriterion("dc_zjlxdh =", value, "dcZjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcZjlxdhNotEqualTo(String value) {
            addCriterion("dc_zjlxdh <>", value, "dcZjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcZjlxdhGreaterThan(String value) {
            addCriterion("dc_zjlxdh >", value, "dcZjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcZjlxdhGreaterThanOrEqualTo(String value) {
            addCriterion("dc_zjlxdh >=", value, "dcZjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcZjlxdhLessThan(String value) {
            addCriterion("dc_zjlxdh <", value, "dcZjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcZjlxdhLessThanOrEqualTo(String value) {
            addCriterion("dc_zjlxdh <=", value, "dcZjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcZjlxdhLike(String value) {
            addCriterion("dc_zjlxdh like", value, "dcZjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcZjlxdhNotLike(String value) {
            addCriterion("dc_zjlxdh not like", value, "dcZjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcZjlxdhIn(List<String> values) {
            addCriterion("dc_zjlxdh in", values, "dcZjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcZjlxdhNotIn(List<String> values) {
            addCriterion("dc_zjlxdh not in", values, "dcZjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcZjlxdhBetween(String value1, String value2) {
            addCriterion("dc_zjlxdh between", value1, value2, "dcZjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcZjlxdhNotBetween(String value1, String value2) {
            addCriterion("dc_zjlxdh not between", value1, value2, "dcZjlxdh");
            return (Criteria) this;
        }

        public Criteria andDcZjfzrIsNull() {
            addCriterion("dc_zjfzr is null");
            return (Criteria) this;
        }

        public Criteria andDcZjfzrIsNotNull() {
            addCriterion("dc_zjfzr is not null");
            return (Criteria) this;
        }

        public Criteria andDcZjfzrEqualTo(String value) {
            addCriterion("dc_zjfzr =", value, "dcZjfzr");
            return (Criteria) this;
        }

        public Criteria andDcZjfzrNotEqualTo(String value) {
            addCriterion("dc_zjfzr <>", value, "dcZjfzr");
            return (Criteria) this;
        }

        public Criteria andDcZjfzrGreaterThan(String value) {
            addCriterion("dc_zjfzr >", value, "dcZjfzr");
            return (Criteria) this;
        }

        public Criteria andDcZjfzrGreaterThanOrEqualTo(String value) {
            addCriterion("dc_zjfzr >=", value, "dcZjfzr");
            return (Criteria) this;
        }

        public Criteria andDcZjfzrLessThan(String value) {
            addCriterion("dc_zjfzr <", value, "dcZjfzr");
            return (Criteria) this;
        }

        public Criteria andDcZjfzrLessThanOrEqualTo(String value) {
            addCriterion("dc_zjfzr <=", value, "dcZjfzr");
            return (Criteria) this;
        }

        public Criteria andDcZjfzrLike(String value) {
            addCriterion("dc_zjfzr like", value, "dcZjfzr");
            return (Criteria) this;
        }

        public Criteria andDcZjfzrNotLike(String value) {
            addCriterion("dc_zjfzr not like", value, "dcZjfzr");
            return (Criteria) this;
        }

        public Criteria andDcZjfzrIn(List<String> values) {
            addCriterion("dc_zjfzr in", values, "dcZjfzr");
            return (Criteria) this;
        }

        public Criteria andDcZjfzrNotIn(List<String> values) {
            addCriterion("dc_zjfzr not in", values, "dcZjfzr");
            return (Criteria) this;
        }

        public Criteria andDcZjfzrBetween(String value1, String value2) {
            addCriterion("dc_zjfzr between", value1, value2, "dcZjfzr");
            return (Criteria) this;
        }

        public Criteria andDcZjfzrNotBetween(String value1, String value2) {
            addCriterion("dc_zjfzr not between", value1, value2, "dcZjfzr");
            return (Criteria) this;
        }

        public Criteria andDcZjfzdhIsNull() {
            addCriterion("dc_zjfzdh is null");
            return (Criteria) this;
        }

        public Criteria andDcZjfzdhIsNotNull() {
            addCriterion("dc_zjfzdh is not null");
            return (Criteria) this;
        }

        public Criteria andDcZjfzdhEqualTo(String value) {
            addCriterion("dc_zjfzdh =", value, "dcZjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcZjfzdhNotEqualTo(String value) {
            addCriterion("dc_zjfzdh <>", value, "dcZjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcZjfzdhGreaterThan(String value) {
            addCriterion("dc_zjfzdh >", value, "dcZjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcZjfzdhGreaterThanOrEqualTo(String value) {
            addCriterion("dc_zjfzdh >=", value, "dcZjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcZjfzdhLessThan(String value) {
            addCriterion("dc_zjfzdh <", value, "dcZjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcZjfzdhLessThanOrEqualTo(String value) {
            addCriterion("dc_zjfzdh <=", value, "dcZjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcZjfzdhLike(String value) {
            addCriterion("dc_zjfzdh like", value, "dcZjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcZjfzdhNotLike(String value) {
            addCriterion("dc_zjfzdh not like", value, "dcZjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcZjfzdhIn(List<String> values) {
            addCriterion("dc_zjfzdh in", values, "dcZjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcZjfzdhNotIn(List<String> values) {
            addCriterion("dc_zjfzdh not in", values, "dcZjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcZjfzdhBetween(String value1, String value2) {
            addCriterion("dc_zjfzdh between", value1, value2, "dcZjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcZjfzdhNotBetween(String value1, String value2) {
            addCriterion("dc_zjfzdh not between", value1, value2, "dcZjfzdh");
            return (Criteria) this;
        }

        public Criteria andDcBy1IsNull() {
            addCriterion("dc_by1 is null");
            return (Criteria) this;
        }

        public Criteria andDcBy1IsNotNull() {
            addCriterion("dc_by1 is not null");
            return (Criteria) this;
        }

        public Criteria andDcBy1EqualTo(String value) {
            addCriterion("dc_by1 =", value, "dcBy1");
            return (Criteria) this;
        }

        public Criteria andDcBy1NotEqualTo(String value) {
            addCriterion("dc_by1 <>", value, "dcBy1");
            return (Criteria) this;
        }

        public Criteria andDcBy1GreaterThan(String value) {
            addCriterion("dc_by1 >", value, "dcBy1");
            return (Criteria) this;
        }

        public Criteria andDcBy1GreaterThanOrEqualTo(String value) {
            addCriterion("dc_by1 >=", value, "dcBy1");
            return (Criteria) this;
        }

        public Criteria andDcBy1LessThan(String value) {
            addCriterion("dc_by1 <", value, "dcBy1");
            return (Criteria) this;
        }

        public Criteria andDcBy1LessThanOrEqualTo(String value) {
            addCriterion("dc_by1 <=", value, "dcBy1");
            return (Criteria) this;
        }

        public Criteria andDcBy1Like(String value) {
            addCriterion("dc_by1 like", value, "dcBy1");
            return (Criteria) this;
        }

        public Criteria andDcBy1NotLike(String value) {
            addCriterion("dc_by1 not like", value, "dcBy1");
            return (Criteria) this;
        }

        public Criteria andDcBy1In(List<String> values) {
            addCriterion("dc_by1 in", values, "dcBy1");
            return (Criteria) this;
        }

        public Criteria andDcBy1NotIn(List<String> values) {
            addCriterion("dc_by1 not in", values, "dcBy1");
            return (Criteria) this;
        }

        public Criteria andDcBy1Between(String value1, String value2) {
            addCriterion("dc_by1 between", value1, value2, "dcBy1");
            return (Criteria) this;
        }

        public Criteria andDcBy1NotBetween(String value1, String value2) {
            addCriterion("dc_by1 not between", value1, value2, "dcBy1");
            return (Criteria) this;
        }

        public Criteria andDcBy2IsNull() {
            addCriterion("dc_by2 is null");
            return (Criteria) this;
        }

        public Criteria andDcBy2IsNotNull() {
            addCriterion("dc_by2 is not null");
            return (Criteria) this;
        }

        public Criteria andDcBy2EqualTo(String value) {
            addCriterion("dc_by2 =", value, "dcBy2");
            return (Criteria) this;
        }

        public Criteria andDcBy2NotEqualTo(String value) {
            addCriterion("dc_by2 <>", value, "dcBy2");
            return (Criteria) this;
        }

        public Criteria andDcBy2GreaterThan(String value) {
            addCriterion("dc_by2 >", value, "dcBy2");
            return (Criteria) this;
        }

        public Criteria andDcBy2GreaterThanOrEqualTo(String value) {
            addCriterion("dc_by2 >=", value, "dcBy2");
            return (Criteria) this;
        }

        public Criteria andDcBy2LessThan(String value) {
            addCriterion("dc_by2 <", value, "dcBy2");
            return (Criteria) this;
        }

        public Criteria andDcBy2LessThanOrEqualTo(String value) {
            addCriterion("dc_by2 <=", value, "dcBy2");
            return (Criteria) this;
        }

        public Criteria andDcBy2Like(String value) {
            addCriterion("dc_by2 like", value, "dcBy2");
            return (Criteria) this;
        }

        public Criteria andDcBy2NotLike(String value) {
            addCriterion("dc_by2 not like", value, "dcBy2");
            return (Criteria) this;
        }

        public Criteria andDcBy2In(List<String> values) {
            addCriterion("dc_by2 in", values, "dcBy2");
            return (Criteria) this;
        }

        public Criteria andDcBy2NotIn(List<String> values) {
            addCriterion("dc_by2 not in", values, "dcBy2");
            return (Criteria) this;
        }

        public Criteria andDcBy2Between(String value1, String value2) {
            addCriterion("dc_by2 between", value1, value2, "dcBy2");
            return (Criteria) this;
        }

        public Criteria andDcBy2NotBetween(String value1, String value2) {
            addCriterion("dc_by2 not between", value1, value2, "dcBy2");
            return (Criteria) this;
        }

        public Criteria andDcBy3IsNull() {
            addCriterion("dc_by3 is null");
            return (Criteria) this;
        }

        public Criteria andDcBy3IsNotNull() {
            addCriterion("dc_by3 is not null");
            return (Criteria) this;
        }

        public Criteria andDcBy3EqualTo(String value) {
            addCriterion("dc_by3 =", value, "dcBy3");
            return (Criteria) this;
        }

        public Criteria andDcBy3NotEqualTo(String value) {
            addCriterion("dc_by3 <>", value, "dcBy3");
            return (Criteria) this;
        }

        public Criteria andDcBy3GreaterThan(String value) {
            addCriterion("dc_by3 >", value, "dcBy3");
            return (Criteria) this;
        }

        public Criteria andDcBy3GreaterThanOrEqualTo(String value) {
            addCriterion("dc_by3 >=", value, "dcBy3");
            return (Criteria) this;
        }

        public Criteria andDcBy3LessThan(String value) {
            addCriterion("dc_by3 <", value, "dcBy3");
            return (Criteria) this;
        }

        public Criteria andDcBy3LessThanOrEqualTo(String value) {
            addCriterion("dc_by3 <=", value, "dcBy3");
            return (Criteria) this;
        }

        public Criteria andDcBy3Like(String value) {
            addCriterion("dc_by3 like", value, "dcBy3");
            return (Criteria) this;
        }

        public Criteria andDcBy3NotLike(String value) {
            addCriterion("dc_by3 not like", value, "dcBy3");
            return (Criteria) this;
        }

        public Criteria andDcBy3In(List<String> values) {
            addCriterion("dc_by3 in", values, "dcBy3");
            return (Criteria) this;
        }

        public Criteria andDcBy3NotIn(List<String> values) {
            addCriterion("dc_by3 not in", values, "dcBy3");
            return (Criteria) this;
        }

        public Criteria andDcBy3Between(String value1, String value2) {
            addCriterion("dc_by3 between", value1, value2, "dcBy3");
            return (Criteria) this;
        }

        public Criteria andDcBy3NotBetween(String value1, String value2) {
            addCriterion("dc_by3 not between", value1, value2, "dcBy3");
            return (Criteria) this;
        }

        public Criteria andDcWjqxIsNull() {
            addCriterion("dc_wjqx is null");
            return (Criteria) this;
        }

        public Criteria andDcWjqxIsNotNull() {
            addCriterion("dc_wjqx is not null");
            return (Criteria) this;
        }

        public Criteria andDcWjqxEqualTo(Boolean value) {
            addCriterion("dc_wjqx =", value, "dcWjqx");
            return (Criteria) this;
        }

        public Criteria andDcWjqxNotEqualTo(Boolean value) {
            addCriterion("dc_wjqx <>", value, "dcWjqx");
            return (Criteria) this;
        }

        public Criteria andDcWjqxGreaterThan(Boolean value) {
            addCriterion("dc_wjqx >", value, "dcWjqx");
            return (Criteria) this;
        }

        public Criteria andDcWjqxGreaterThanOrEqualTo(Boolean value) {
            addCriterion("dc_wjqx >=", value, "dcWjqx");
            return (Criteria) this;
        }

        public Criteria andDcWjqxLessThan(Boolean value) {
            addCriterion("dc_wjqx <", value, "dcWjqx");
            return (Criteria) this;
        }

        public Criteria andDcWjqxLessThanOrEqualTo(Boolean value) {
            addCriterion("dc_wjqx <=", value, "dcWjqx");
            return (Criteria) this;
        }

        public Criteria andDcWjqxIn(List<Boolean> values) {
            addCriterion("dc_wjqx in", values, "dcWjqx");
            return (Criteria) this;
        }

        public Criteria andDcWjqxNotIn(List<Boolean> values) {
            addCriterion("dc_wjqx not in", values, "dcWjqx");
            return (Criteria) this;
        }

        public Criteria andDcWjqxBetween(Boolean value1, Boolean value2) {
            addCriterion("dc_wjqx between", value1, value2, "dcWjqx");
            return (Criteria) this;
        }

        public Criteria andDcWjqxNotBetween(Boolean value1, Boolean value2) {
            addCriterion("dc_wjqx not between", value1, value2, "dcWjqx");
            return (Criteria) this;
        }

        public Criteria andDcDjqxIsNull() {
            addCriterion("dc_djqx is null");
            return (Criteria) this;
        }

        public Criteria andDcDjqxIsNotNull() {
            addCriterion("dc_djqx is not null");
            return (Criteria) this;
        }

        public Criteria andDcDjqxEqualTo(Boolean value) {
            addCriterion("dc_djqx =", value, "dcDjqx");
            return (Criteria) this;
        }

        public Criteria andDcDjqxNotEqualTo(Boolean value) {
            addCriterion("dc_djqx <>", value, "dcDjqx");
            return (Criteria) this;
        }

        public Criteria andDcDjqxGreaterThan(Boolean value) {
            addCriterion("dc_djqx >", value, "dcDjqx");
            return (Criteria) this;
        }

        public Criteria andDcDjqxGreaterThanOrEqualTo(Boolean value) {
            addCriterion("dc_djqx >=", value, "dcDjqx");
            return (Criteria) this;
        }

        public Criteria andDcDjqxLessThan(Boolean value) {
            addCriterion("dc_djqx <", value, "dcDjqx");
            return (Criteria) this;
        }

        public Criteria andDcDjqxLessThanOrEqualTo(Boolean value) {
            addCriterion("dc_djqx <=", value, "dcDjqx");
            return (Criteria) this;
        }

        public Criteria andDcDjqxIn(List<Boolean> values) {
            addCriterion("dc_djqx in", values, "dcDjqx");
            return (Criteria) this;
        }

        public Criteria andDcDjqxNotIn(List<Boolean> values) {
            addCriterion("dc_djqx not in", values, "dcDjqx");
            return (Criteria) this;
        }

        public Criteria andDcDjqxBetween(Boolean value1, Boolean value2) {
            addCriterion("dc_djqx between", value1, value2, "dcDjqx");
            return (Criteria) this;
        }

        public Criteria andDcDjqxNotBetween(Boolean value1, Boolean value2) {
            addCriterion("dc_djqx not between", value1, value2, "dcDjqx");
            return (Criteria) this;
        }

        public Criteria andDcZjqxIsNull() {
            addCriterion("dc_zjqx is null");
            return (Criteria) this;
        }

        public Criteria andDcZjqxIsNotNull() {
            addCriterion("dc_zjqx is not null");
            return (Criteria) this;
        }

        public Criteria andDcZjqxEqualTo(Boolean value) {
            addCriterion("dc_zjqx =", value, "dcZjqx");
            return (Criteria) this;
        }

        public Criteria andDcZjqxNotEqualTo(Boolean value) {
            addCriterion("dc_zjqx <>", value, "dcZjqx");
            return (Criteria) this;
        }

        public Criteria andDcZjqxGreaterThan(Boolean value) {
            addCriterion("dc_zjqx >", value, "dcZjqx");
            return (Criteria) this;
        }

        public Criteria andDcZjqxGreaterThanOrEqualTo(Boolean value) {
            addCriterion("dc_zjqx >=", value, "dcZjqx");
            return (Criteria) this;
        }

        public Criteria andDcZjqxLessThan(Boolean value) {
            addCriterion("dc_zjqx <", value, "dcZjqx");
            return (Criteria) this;
        }

        public Criteria andDcZjqxLessThanOrEqualTo(Boolean value) {
            addCriterion("dc_zjqx <=", value, "dcZjqx");
            return (Criteria) this;
        }

        public Criteria andDcZjqxIn(List<Boolean> values) {
            addCriterion("dc_zjqx in", values, "dcZjqx");
            return (Criteria) this;
        }

        public Criteria andDcZjqxNotIn(List<Boolean> values) {
            addCriterion("dc_zjqx not in", values, "dcZjqx");
            return (Criteria) this;
        }

        public Criteria andDcZjqxBetween(Boolean value1, Boolean value2) {
            addCriterion("dc_zjqx between", value1, value2, "dcZjqx");
            return (Criteria) this;
        }

        public Criteria andDcZjqxNotBetween(Boolean value1, Boolean value2) {
            addCriterion("dc_zjqx not between", value1, value2, "dcZjqx");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dc_user
     *
     * @mbg.generated do_not_delete_during_merge Sat Jan 23 21:18:05 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dc_user
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}