package com.xsz.customs.model;

public class dcUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.Id
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.dc_gqdm
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String dcGqdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.dc_gqdj
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private Integer dcGqdj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.dc_gqname
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String dcGqname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.dc_gqpword
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String dcGqpword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.dc_shiwuku
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String dcShiwuku;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.dc_shujuku
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String dcShujuku;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.dc_lxr
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String dcLxr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.dc_lxsj
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String dcLxsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.dc_lxdh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String dcLxdh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.dc_dzyj
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String dcDzyj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.dc_wjlxr
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String dcWjlxr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.dc_wjlxdh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String dcWjlxdh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.dc_wjfzr
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String dcWjfzr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.dc_wjfzdh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String dcWjfzdh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.dc_djlxr
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String dcDjlxr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.dc_djlxdh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String dcDjlxdh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.dc_djfzr
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String dcDjfzr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.dc_djfzdh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String dcDjfzdh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.dc_zjlxr
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String dcZjlxr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.dc_zjlxdh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String dcZjlxdh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.dc_zjfzr
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String dcZjfzr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.dc_zjfzdh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String dcZjfzdh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.dc_by1
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String dcBy1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.dc_by2
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String dcBy2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.dc_by3
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String dcBy3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.Id
     *
     * @return the value of dc_user.Id
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.Id
     *
     * @param id the value for dc_user.Id
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.dc_gqdm
     *
     * @return the value of dc_user.dc_gqdm
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getDcGqdm() {
        return dcGqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.dc_gqdm
     *
     * @param dcGqdm the value for dc_user.dc_gqdm
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcGqdm(String dcGqdm) {
        this.dcGqdm = dcGqdm == null ? null : dcGqdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.dc_gqdj
     *
     * @return the value of dc_user.dc_gqdj
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public Integer getDcGqdj() {
        return dcGqdj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.dc_gqdj
     *
     * @param dcGqdj the value for dc_user.dc_gqdj
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcGqdj(Integer dcGqdj) {
        this.dcGqdj = dcGqdj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.dc_gqname
     *
     * @return the value of dc_user.dc_gqname
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getDcGqname() {
        return dcGqname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.dc_gqname
     *
     * @param dcGqname the value for dc_user.dc_gqname
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcGqname(String dcGqname) {
        this.dcGqname = dcGqname == null ? null : dcGqname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.dc_gqpword
     *
     * @return the value of dc_user.dc_gqpword
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getDcGqpword() {
        return dcGqpword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.dc_gqpword
     *
     * @param dcGqpword the value for dc_user.dc_gqpword
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcGqpword(String dcGqpword) {
        this.dcGqpword = dcGqpword == null ? null : dcGqpword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.dc_shiwuku
     *
     * @return the value of dc_user.dc_shiwuku
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getDcShiwuku() {
        return dcShiwuku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.dc_shiwuku
     *
     * @param dcShiwuku the value for dc_user.dc_shiwuku
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcShiwuku(String dcShiwuku) {
        this.dcShiwuku = dcShiwuku == null ? null : dcShiwuku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.dc_shujuku
     *
     * @return the value of dc_user.dc_shujuku
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getDcShujuku() {
        return dcShujuku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.dc_shujuku
     *
     * @param dcShujuku the value for dc_user.dc_shujuku
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcShujuku(String dcShujuku) {
        this.dcShujuku = dcShujuku == null ? null : dcShujuku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.dc_lxr
     *
     * @return the value of dc_user.dc_lxr
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getDcLxr() {
        return dcLxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.dc_lxr
     *
     * @param dcLxr the value for dc_user.dc_lxr
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcLxr(String dcLxr) {
        this.dcLxr = dcLxr == null ? null : dcLxr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.dc_lxsj
     *
     * @return the value of dc_user.dc_lxsj
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getDcLxsj() {
        return dcLxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.dc_lxsj
     *
     * @param dcLxsj the value for dc_user.dc_lxsj
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcLxsj(String dcLxsj) {
        this.dcLxsj = dcLxsj == null ? null : dcLxsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.dc_lxdh
     *
     * @return the value of dc_user.dc_lxdh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getDcLxdh() {
        return dcLxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.dc_lxdh
     *
     * @param dcLxdh the value for dc_user.dc_lxdh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcLxdh(String dcLxdh) {
        this.dcLxdh = dcLxdh == null ? null : dcLxdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.dc_dzyj
     *
     * @return the value of dc_user.dc_dzyj
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getDcDzyj() {
        return dcDzyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.dc_dzyj
     *
     * @param dcDzyj the value for dc_user.dc_dzyj
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcDzyj(String dcDzyj) {
        this.dcDzyj = dcDzyj == null ? null : dcDzyj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.dc_wjlxr
     *
     * @return the value of dc_user.dc_wjlxr
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getDcWjlxr() {
        return dcWjlxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.dc_wjlxr
     *
     * @param dcWjlxr the value for dc_user.dc_wjlxr
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcWjlxr(String dcWjlxr) {
        this.dcWjlxr = dcWjlxr == null ? null : dcWjlxr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.dc_wjlxdh
     *
     * @return the value of dc_user.dc_wjlxdh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getDcWjlxdh() {
        return dcWjlxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.dc_wjlxdh
     *
     * @param dcWjlxdh the value for dc_user.dc_wjlxdh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcWjlxdh(String dcWjlxdh) {
        this.dcWjlxdh = dcWjlxdh == null ? null : dcWjlxdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.dc_wjfzr
     *
     * @return the value of dc_user.dc_wjfzr
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getDcWjfzr() {
        return dcWjfzr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.dc_wjfzr
     *
     * @param dcWjfzr the value for dc_user.dc_wjfzr
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcWjfzr(String dcWjfzr) {
        this.dcWjfzr = dcWjfzr == null ? null : dcWjfzr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.dc_wjfzdh
     *
     * @return the value of dc_user.dc_wjfzdh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getDcWjfzdh() {
        return dcWjfzdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.dc_wjfzdh
     *
     * @param dcWjfzdh the value for dc_user.dc_wjfzdh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcWjfzdh(String dcWjfzdh) {
        this.dcWjfzdh = dcWjfzdh == null ? null : dcWjfzdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.dc_djlxr
     *
     * @return the value of dc_user.dc_djlxr
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getDcDjlxr() {
        return dcDjlxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.dc_djlxr
     *
     * @param dcDjlxr the value for dc_user.dc_djlxr
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcDjlxr(String dcDjlxr) {
        this.dcDjlxr = dcDjlxr == null ? null : dcDjlxr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.dc_djlxdh
     *
     * @return the value of dc_user.dc_djlxdh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getDcDjlxdh() {
        return dcDjlxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.dc_djlxdh
     *
     * @param dcDjlxdh the value for dc_user.dc_djlxdh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcDjlxdh(String dcDjlxdh) {
        this.dcDjlxdh = dcDjlxdh == null ? null : dcDjlxdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.dc_djfzr
     *
     * @return the value of dc_user.dc_djfzr
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getDcDjfzr() {
        return dcDjfzr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.dc_djfzr
     *
     * @param dcDjfzr the value for dc_user.dc_djfzr
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcDjfzr(String dcDjfzr) {
        this.dcDjfzr = dcDjfzr == null ? null : dcDjfzr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.dc_djfzdh
     *
     * @return the value of dc_user.dc_djfzdh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getDcDjfzdh() {
        return dcDjfzdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.dc_djfzdh
     *
     * @param dcDjfzdh the value for dc_user.dc_djfzdh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcDjfzdh(String dcDjfzdh) {
        this.dcDjfzdh = dcDjfzdh == null ? null : dcDjfzdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.dc_zjlxr
     *
     * @return the value of dc_user.dc_zjlxr
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getDcZjlxr() {
        return dcZjlxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.dc_zjlxr
     *
     * @param dcZjlxr the value for dc_user.dc_zjlxr
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcZjlxr(String dcZjlxr) {
        this.dcZjlxr = dcZjlxr == null ? null : dcZjlxr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.dc_zjlxdh
     *
     * @return the value of dc_user.dc_zjlxdh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getDcZjlxdh() {
        return dcZjlxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.dc_zjlxdh
     *
     * @param dcZjlxdh the value for dc_user.dc_zjlxdh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcZjlxdh(String dcZjlxdh) {
        this.dcZjlxdh = dcZjlxdh == null ? null : dcZjlxdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.dc_zjfzr
     *
     * @return the value of dc_user.dc_zjfzr
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getDcZjfzr() {
        return dcZjfzr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.dc_zjfzr
     *
     * @param dcZjfzr the value for dc_user.dc_zjfzr
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcZjfzr(String dcZjfzr) {
        this.dcZjfzr = dcZjfzr == null ? null : dcZjfzr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.dc_zjfzdh
     *
     * @return the value of dc_user.dc_zjfzdh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getDcZjfzdh() {
        return dcZjfzdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.dc_zjfzdh
     *
     * @param dcZjfzdh the value for dc_user.dc_zjfzdh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcZjfzdh(String dcZjfzdh) {
        this.dcZjfzdh = dcZjfzdh == null ? null : dcZjfzdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.dc_by1
     *
     * @return the value of dc_user.dc_by1
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getDcBy1() {
        return dcBy1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.dc_by1
     *
     * @param dcBy1 the value for dc_user.dc_by1
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcBy1(String dcBy1) {
        this.dcBy1 = dcBy1 == null ? null : dcBy1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.dc_by2
     *
     * @return the value of dc_user.dc_by2
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getDcBy2() {
        return dcBy2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.dc_by2
     *
     * @param dcBy2 the value for dc_user.dc_by2
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcBy2(String dcBy2) {
        this.dcBy2 = dcBy2 == null ? null : dcBy2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.dc_by3
     *
     * @return the value of dc_user.dc_by3
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getDcBy3() {
        return dcBy3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.dc_by3
     *
     * @param dcBy3 the value for dc_user.dc_by3
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcBy3(String dcBy3) {
        this.dcBy3 = dcBy3 == null ? null : dcBy3.trim();
    }
}