package com.xsz.customs.model;

public class dcWsjy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.Id
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.dc_renwumc
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String dcRenwumc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.dc_renwuid
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private Integer dcRenwuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.dc_renwuxh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private Integer dcRenwuxh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.dc_renwugqdm
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String dcRenwugqdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.dc_renwugqname
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String dcRenwugqname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.dc_renwugqdm2
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String dcRenwugqdm2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.dc_renwugqxh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private Integer dcRenwugqxh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.wj_ywly
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String wjYwly;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.wj_lb
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String wjLb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.wj_name
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String wjName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.wj_ldxm
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String wjLdxm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.wj_zhuxi
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String wjZhuxi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.wj_zhuanci
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String wjZhuanci;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.wj_neibubh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String wjNeibubh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.wj_baocunxs
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String wjBaocunxs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.wj_laiyuan
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String wjLaiyuan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.wj_lysuzhu
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String wjLysuzhu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.wj_ybl
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private Integer wjYbl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.wj_ybdanwei
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String wjYbdanwei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.wj_baocunzt
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String wjBaocunzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.wj_huodedd
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String wjHuodedd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.wj_huoqutj
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String wjHuoqutj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.wj_baocuntj
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String wjBaocuntj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.wj_baocunsj
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String wjBaocunsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.wj_baocunwz
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String wjBaocunwz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.wj_lianlr
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String wjLianlr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.wj_lianldh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String wjLianldh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.wj_fuzeren
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String wjFuzeren;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.wj_fuzerendh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String wjFuzerendh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.wj_by1
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String wjBy1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.wj_by2
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String wjBy2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_wsjy.wj_by3
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    private String wjBy3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.Id
     *
     * @return the value of dc_wsjy.Id
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.Id
     *
     * @param id the value for dc_wsjy.Id
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.dc_renwumc
     *
     * @return the value of dc_wsjy.dc_renwumc
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getDcRenwumc() {
        return dcRenwumc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.dc_renwumc
     *
     * @param dcRenwumc the value for dc_wsjy.dc_renwumc
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcRenwumc(String dcRenwumc) {
        this.dcRenwumc = dcRenwumc == null ? null : dcRenwumc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.dc_renwuid
     *
     * @return the value of dc_wsjy.dc_renwuid
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public Integer getDcRenwuid() {
        return dcRenwuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.dc_renwuid
     *
     * @param dcRenwuid the value for dc_wsjy.dc_renwuid
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcRenwuid(Integer dcRenwuid) {
        this.dcRenwuid = dcRenwuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.dc_renwuxh
     *
     * @return the value of dc_wsjy.dc_renwuxh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public Integer getDcRenwuxh() {
        return dcRenwuxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.dc_renwuxh
     *
     * @param dcRenwuxh the value for dc_wsjy.dc_renwuxh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcRenwuxh(Integer dcRenwuxh) {
        this.dcRenwuxh = dcRenwuxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.dc_renwugqdm
     *
     * @return the value of dc_wsjy.dc_renwugqdm
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getDcRenwugqdm() {
        return dcRenwugqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.dc_renwugqdm
     *
     * @param dcRenwugqdm the value for dc_wsjy.dc_renwugqdm
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcRenwugqdm(String dcRenwugqdm) {
        this.dcRenwugqdm = dcRenwugqdm == null ? null : dcRenwugqdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.dc_renwugqname
     *
     * @return the value of dc_wsjy.dc_renwugqname
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getDcRenwugqname() {
        return dcRenwugqname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.dc_renwugqname
     *
     * @param dcRenwugqname the value for dc_wsjy.dc_renwugqname
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcRenwugqname(String dcRenwugqname) {
        this.dcRenwugqname = dcRenwugqname == null ? null : dcRenwugqname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.dc_renwugqdm2
     *
     * @return the value of dc_wsjy.dc_renwugqdm2
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getDcRenwugqdm2() {
        return dcRenwugqdm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.dc_renwugqdm2
     *
     * @param dcRenwugqdm2 the value for dc_wsjy.dc_renwugqdm2
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcRenwugqdm2(String dcRenwugqdm2) {
        this.dcRenwugqdm2 = dcRenwugqdm2 == null ? null : dcRenwugqdm2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.dc_renwugqxh
     *
     * @return the value of dc_wsjy.dc_renwugqxh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public Integer getDcRenwugqxh() {
        return dcRenwugqxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.dc_renwugqxh
     *
     * @param dcRenwugqxh the value for dc_wsjy.dc_renwugqxh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setDcRenwugqxh(Integer dcRenwugqxh) {
        this.dcRenwugqxh = dcRenwugqxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.wj_ywly
     *
     * @return the value of dc_wsjy.wj_ywly
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getWjYwly() {
        return wjYwly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.wj_ywly
     *
     * @param wjYwly the value for dc_wsjy.wj_ywly
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setWjYwly(String wjYwly) {
        this.wjYwly = wjYwly == null ? null : wjYwly.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.wj_lb
     *
     * @return the value of dc_wsjy.wj_lb
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getWjLb() {
        return wjLb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.wj_lb
     *
     * @param wjLb the value for dc_wsjy.wj_lb
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setWjLb(String wjLb) {
        this.wjLb = wjLb == null ? null : wjLb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.wj_name
     *
     * @return the value of dc_wsjy.wj_name
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getWjName() {
        return wjName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.wj_name
     *
     * @param wjName the value for dc_wsjy.wj_name
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setWjName(String wjName) {
        this.wjName = wjName == null ? null : wjName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.wj_ldxm
     *
     * @return the value of dc_wsjy.wj_ldxm
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getWjLdxm() {
        return wjLdxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.wj_ldxm
     *
     * @param wjLdxm the value for dc_wsjy.wj_ldxm
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setWjLdxm(String wjLdxm) {
        this.wjLdxm = wjLdxm == null ? null : wjLdxm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.wj_zhuxi
     *
     * @return the value of dc_wsjy.wj_zhuxi
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getWjZhuxi() {
        return wjZhuxi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.wj_zhuxi
     *
     * @param wjZhuxi the value for dc_wsjy.wj_zhuxi
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setWjZhuxi(String wjZhuxi) {
        this.wjZhuxi = wjZhuxi == null ? null : wjZhuxi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.wj_zhuanci
     *
     * @return the value of dc_wsjy.wj_zhuanci
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getWjZhuanci() {
        return wjZhuanci;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.wj_zhuanci
     *
     * @param wjZhuanci the value for dc_wsjy.wj_zhuanci
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setWjZhuanci(String wjZhuanci) {
        this.wjZhuanci = wjZhuanci == null ? null : wjZhuanci.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.wj_neibubh
     *
     * @return the value of dc_wsjy.wj_neibubh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getWjNeibubh() {
        return wjNeibubh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.wj_neibubh
     *
     * @param wjNeibubh the value for dc_wsjy.wj_neibubh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setWjNeibubh(String wjNeibubh) {
        this.wjNeibubh = wjNeibubh == null ? null : wjNeibubh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.wj_baocunxs
     *
     * @return the value of dc_wsjy.wj_baocunxs
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getWjBaocunxs() {
        return wjBaocunxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.wj_baocunxs
     *
     * @param wjBaocunxs the value for dc_wsjy.wj_baocunxs
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setWjBaocunxs(String wjBaocunxs) {
        this.wjBaocunxs = wjBaocunxs == null ? null : wjBaocunxs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.wj_laiyuan
     *
     * @return the value of dc_wsjy.wj_laiyuan
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getWjLaiyuan() {
        return wjLaiyuan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.wj_laiyuan
     *
     * @param wjLaiyuan the value for dc_wsjy.wj_laiyuan
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setWjLaiyuan(String wjLaiyuan) {
        this.wjLaiyuan = wjLaiyuan == null ? null : wjLaiyuan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.wj_lysuzhu
     *
     * @return the value of dc_wsjy.wj_lysuzhu
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getWjLysuzhu() {
        return wjLysuzhu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.wj_lysuzhu
     *
     * @param wjLysuzhu the value for dc_wsjy.wj_lysuzhu
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setWjLysuzhu(String wjLysuzhu) {
        this.wjLysuzhu = wjLysuzhu == null ? null : wjLysuzhu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.wj_ybl
     *
     * @return the value of dc_wsjy.wj_ybl
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public Integer getWjYbl() {
        return wjYbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.wj_ybl
     *
     * @param wjYbl the value for dc_wsjy.wj_ybl
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setWjYbl(Integer wjYbl) {
        this.wjYbl = wjYbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.wj_ybdanwei
     *
     * @return the value of dc_wsjy.wj_ybdanwei
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getWjYbdanwei() {
        return wjYbdanwei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.wj_ybdanwei
     *
     * @param wjYbdanwei the value for dc_wsjy.wj_ybdanwei
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setWjYbdanwei(String wjYbdanwei) {
        this.wjYbdanwei = wjYbdanwei == null ? null : wjYbdanwei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.wj_baocunzt
     *
     * @return the value of dc_wsjy.wj_baocunzt
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getWjBaocunzt() {
        return wjBaocunzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.wj_baocunzt
     *
     * @param wjBaocunzt the value for dc_wsjy.wj_baocunzt
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setWjBaocunzt(String wjBaocunzt) {
        this.wjBaocunzt = wjBaocunzt == null ? null : wjBaocunzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.wj_huodedd
     *
     * @return the value of dc_wsjy.wj_huodedd
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getWjHuodedd() {
        return wjHuodedd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.wj_huodedd
     *
     * @param wjHuodedd the value for dc_wsjy.wj_huodedd
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setWjHuodedd(String wjHuodedd) {
        this.wjHuodedd = wjHuodedd == null ? null : wjHuodedd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.wj_huoqutj
     *
     * @return the value of dc_wsjy.wj_huoqutj
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getWjHuoqutj() {
        return wjHuoqutj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.wj_huoqutj
     *
     * @param wjHuoqutj the value for dc_wsjy.wj_huoqutj
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setWjHuoqutj(String wjHuoqutj) {
        this.wjHuoqutj = wjHuoqutj == null ? null : wjHuoqutj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.wj_baocuntj
     *
     * @return the value of dc_wsjy.wj_baocuntj
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getWjBaocuntj() {
        return wjBaocuntj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.wj_baocuntj
     *
     * @param wjBaocuntj the value for dc_wsjy.wj_baocuntj
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setWjBaocuntj(String wjBaocuntj) {
        this.wjBaocuntj = wjBaocuntj == null ? null : wjBaocuntj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.wj_baocunsj
     *
     * @return the value of dc_wsjy.wj_baocunsj
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getWjBaocunsj() {
        return wjBaocunsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.wj_baocunsj
     *
     * @param wjBaocunsj the value for dc_wsjy.wj_baocunsj
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setWjBaocunsj(String wjBaocunsj) {
        this.wjBaocunsj = wjBaocunsj == null ? null : wjBaocunsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.wj_baocunwz
     *
     * @return the value of dc_wsjy.wj_baocunwz
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getWjBaocunwz() {
        return wjBaocunwz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.wj_baocunwz
     *
     * @param wjBaocunwz the value for dc_wsjy.wj_baocunwz
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setWjBaocunwz(String wjBaocunwz) {
        this.wjBaocunwz = wjBaocunwz == null ? null : wjBaocunwz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.wj_lianlr
     *
     * @return the value of dc_wsjy.wj_lianlr
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getWjLianlr() {
        return wjLianlr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.wj_lianlr
     *
     * @param wjLianlr the value for dc_wsjy.wj_lianlr
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setWjLianlr(String wjLianlr) {
        this.wjLianlr = wjLianlr == null ? null : wjLianlr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.wj_lianldh
     *
     * @return the value of dc_wsjy.wj_lianldh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getWjLianldh() {
        return wjLianldh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.wj_lianldh
     *
     * @param wjLianldh the value for dc_wsjy.wj_lianldh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setWjLianldh(String wjLianldh) {
        this.wjLianldh = wjLianldh == null ? null : wjLianldh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.wj_fuzeren
     *
     * @return the value of dc_wsjy.wj_fuzeren
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getWjFuzeren() {
        return wjFuzeren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.wj_fuzeren
     *
     * @param wjFuzeren the value for dc_wsjy.wj_fuzeren
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setWjFuzeren(String wjFuzeren) {
        this.wjFuzeren = wjFuzeren == null ? null : wjFuzeren.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.wj_fuzerendh
     *
     * @return the value of dc_wsjy.wj_fuzerendh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getWjFuzerendh() {
        return wjFuzerendh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.wj_fuzerendh
     *
     * @param wjFuzerendh the value for dc_wsjy.wj_fuzerendh
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setWjFuzerendh(String wjFuzerendh) {
        this.wjFuzerendh = wjFuzerendh == null ? null : wjFuzerendh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.wj_by1
     *
     * @return the value of dc_wsjy.wj_by1
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getWjBy1() {
        return wjBy1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.wj_by1
     *
     * @param wjBy1 the value for dc_wsjy.wj_by1
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setWjBy1(String wjBy1) {
        this.wjBy1 = wjBy1 == null ? null : wjBy1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.wj_by2
     *
     * @return the value of dc_wsjy.wj_by2
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getWjBy2() {
        return wjBy2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.wj_by2
     *
     * @param wjBy2 the value for dc_wsjy.wj_by2
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setWjBy2(String wjBy2) {
        this.wjBy2 = wjBy2 == null ? null : wjBy2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_wsjy.wj_by3
     *
     * @return the value of dc_wsjy.wj_by3
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public String getWjBy3() {
        return wjBy3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_wsjy.wj_by3
     *
     * @param wjBy3 the value for dc_wsjy.wj_by3
     *
     * @mbg.generated Tue Dec 29 15:47:18 CST 2020
     */
    public void setWjBy3(String wjBy3) {
        this.wjBy3 = wjBy3 == null ? null : wjBy3.trim();
    }
}