package com.xsz.customs.model;

public class dcZwjy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.Id
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.dc_renwumc
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private String dcRenwumc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.dc_renwuid
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private Integer dcRenwuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.dc_renwuxh
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private Integer dcRenwuxh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.dc_renwugqdm
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private String dcRenwugqdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.dc_renwugqname
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private String dcRenwugqname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.dc_renwugqdm2
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private String dcRenwugqdm2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.dc_renwugqxh
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private Integer dcRenwugqxh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.zj_ywly
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private String zjYwly;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.zj_lb
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private String zjLb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.zj_name
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private String zjName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.zj_ldxm
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private String zjLdxm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.zj_shidai
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private String zjShidai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.zj_neibubh
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private String zjNeibubh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.zj_jianyidw
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private String zjJianyidw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.zj_jianyiywlb
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private String zjJianyiywlb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.zj_huowulb
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private String zjHuowulb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.zj_jizhu
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private String zjJizhu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.zj_baocunxs
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private String zjBaocunxs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.zj_laiyuan
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private String zjLaiyuan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.zj_laiyuangj
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private String zjLaiyuangj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.zj_ybl
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private Integer zjYbl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.zj_ybdanwei
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private String zjYbdanwei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.zj_baocunzt
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private String zjBaocunzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.zj_huodedd
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private String zjHuodedd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.zj_baocunwz
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private String zjBaocunwz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.zj_baocuntj
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private String zjBaocuntj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.zj_baocunsj
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private String zjBaocunsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.zj_lianlr
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private String zjLianlr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.zj_lianldh
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private String zjLianldh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.zj_fuzeren
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private String zjFuzeren;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.zj_fuzerendh
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private String zjFuzerendh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.zj_by1
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private String zjBy1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.zj_by2
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private String zjBy2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_zwjy.zj_by3
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    private String zjBy3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.Id
     *
     * @return the value of dc_zwjy.Id
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.Id
     *
     * @param id the value for dc_zwjy.Id
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.dc_renwumc
     *
     * @return the value of dc_zwjy.dc_renwumc
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getDcRenwumc() {
        return dcRenwumc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.dc_renwumc
     *
     * @param dcRenwumc the value for dc_zwjy.dc_renwumc
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setDcRenwumc(String dcRenwumc) {
        this.dcRenwumc = dcRenwumc == null ? null : dcRenwumc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.dc_renwuid
     *
     * @return the value of dc_zwjy.dc_renwuid
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public Integer getDcRenwuid() {
        return dcRenwuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.dc_renwuid
     *
     * @param dcRenwuid the value for dc_zwjy.dc_renwuid
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setDcRenwuid(Integer dcRenwuid) {
        this.dcRenwuid = dcRenwuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.dc_renwuxh
     *
     * @return the value of dc_zwjy.dc_renwuxh
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public Integer getDcRenwuxh() {
        return dcRenwuxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.dc_renwuxh
     *
     * @param dcRenwuxh the value for dc_zwjy.dc_renwuxh
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setDcRenwuxh(Integer dcRenwuxh) {
        this.dcRenwuxh = dcRenwuxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.dc_renwugqdm
     *
     * @return the value of dc_zwjy.dc_renwugqdm
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getDcRenwugqdm() {
        return dcRenwugqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.dc_renwugqdm
     *
     * @param dcRenwugqdm the value for dc_zwjy.dc_renwugqdm
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setDcRenwugqdm(String dcRenwugqdm) {
        this.dcRenwugqdm = dcRenwugqdm == null ? null : dcRenwugqdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.dc_renwugqname
     *
     * @return the value of dc_zwjy.dc_renwugqname
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getDcRenwugqname() {
        return dcRenwugqname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.dc_renwugqname
     *
     * @param dcRenwugqname the value for dc_zwjy.dc_renwugqname
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setDcRenwugqname(String dcRenwugqname) {
        this.dcRenwugqname = dcRenwugqname == null ? null : dcRenwugqname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.dc_renwugqdm2
     *
     * @return the value of dc_zwjy.dc_renwugqdm2
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getDcRenwugqdm2() {
        return dcRenwugqdm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.dc_renwugqdm2
     *
     * @param dcRenwugqdm2 the value for dc_zwjy.dc_renwugqdm2
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setDcRenwugqdm2(String dcRenwugqdm2) {
        this.dcRenwugqdm2 = dcRenwugqdm2 == null ? null : dcRenwugqdm2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.dc_renwugqxh
     *
     * @return the value of dc_zwjy.dc_renwugqxh
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public Integer getDcRenwugqxh() {
        return dcRenwugqxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.dc_renwugqxh
     *
     * @param dcRenwugqxh the value for dc_zwjy.dc_renwugqxh
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setDcRenwugqxh(Integer dcRenwugqxh) {
        this.dcRenwugqxh = dcRenwugqxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.zj_ywly
     *
     * @return the value of dc_zwjy.zj_ywly
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getZjYwly() {
        return zjYwly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.zj_ywly
     *
     * @param zjYwly the value for dc_zwjy.zj_ywly
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setZjYwly(String zjYwly) {
        this.zjYwly = zjYwly == null ? null : zjYwly.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.zj_lb
     *
     * @return the value of dc_zwjy.zj_lb
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getZjLb() {
        return zjLb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.zj_lb
     *
     * @param zjLb the value for dc_zwjy.zj_lb
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setZjLb(String zjLb) {
        this.zjLb = zjLb == null ? null : zjLb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.zj_name
     *
     * @return the value of dc_zwjy.zj_name
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getZjName() {
        return zjName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.zj_name
     *
     * @param zjName the value for dc_zwjy.zj_name
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setZjName(String zjName) {
        this.zjName = zjName == null ? null : zjName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.zj_ldxm
     *
     * @return the value of dc_zwjy.zj_ldxm
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getZjLdxm() {
        return zjLdxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.zj_ldxm
     *
     * @param zjLdxm the value for dc_zwjy.zj_ldxm
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setZjLdxm(String zjLdxm) {
        this.zjLdxm = zjLdxm == null ? null : zjLdxm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.zj_shidai
     *
     * @return the value of dc_zwjy.zj_shidai
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getZjShidai() {
        return zjShidai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.zj_shidai
     *
     * @param zjShidai the value for dc_zwjy.zj_shidai
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setZjShidai(String zjShidai) {
        this.zjShidai = zjShidai == null ? null : zjShidai.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.zj_neibubh
     *
     * @return the value of dc_zwjy.zj_neibubh
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getZjNeibubh() {
        return zjNeibubh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.zj_neibubh
     *
     * @param zjNeibubh the value for dc_zwjy.zj_neibubh
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setZjNeibubh(String zjNeibubh) {
        this.zjNeibubh = zjNeibubh == null ? null : zjNeibubh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.zj_jianyidw
     *
     * @return the value of dc_zwjy.zj_jianyidw
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getZjJianyidw() {
        return zjJianyidw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.zj_jianyidw
     *
     * @param zjJianyidw the value for dc_zwjy.zj_jianyidw
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setZjJianyidw(String zjJianyidw) {
        this.zjJianyidw = zjJianyidw == null ? null : zjJianyidw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.zj_jianyiywlb
     *
     * @return the value of dc_zwjy.zj_jianyiywlb
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getZjJianyiywlb() {
        return zjJianyiywlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.zj_jianyiywlb
     *
     * @param zjJianyiywlb the value for dc_zwjy.zj_jianyiywlb
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setZjJianyiywlb(String zjJianyiywlb) {
        this.zjJianyiywlb = zjJianyiywlb == null ? null : zjJianyiywlb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.zj_huowulb
     *
     * @return the value of dc_zwjy.zj_huowulb
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getZjHuowulb() {
        return zjHuowulb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.zj_huowulb
     *
     * @param zjHuowulb the value for dc_zwjy.zj_huowulb
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setZjHuowulb(String zjHuowulb) {
        this.zjHuowulb = zjHuowulb == null ? null : zjHuowulb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.zj_jizhu
     *
     * @return the value of dc_zwjy.zj_jizhu
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getZjJizhu() {
        return zjJizhu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.zj_jizhu
     *
     * @param zjJizhu the value for dc_zwjy.zj_jizhu
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setZjJizhu(String zjJizhu) {
        this.zjJizhu = zjJizhu == null ? null : zjJizhu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.zj_baocunxs
     *
     * @return the value of dc_zwjy.zj_baocunxs
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getZjBaocunxs() {
        return zjBaocunxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.zj_baocunxs
     *
     * @param zjBaocunxs the value for dc_zwjy.zj_baocunxs
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setZjBaocunxs(String zjBaocunxs) {
        this.zjBaocunxs = zjBaocunxs == null ? null : zjBaocunxs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.zj_laiyuan
     *
     * @return the value of dc_zwjy.zj_laiyuan
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getZjLaiyuan() {
        return zjLaiyuan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.zj_laiyuan
     *
     * @param zjLaiyuan the value for dc_zwjy.zj_laiyuan
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setZjLaiyuan(String zjLaiyuan) {
        this.zjLaiyuan = zjLaiyuan == null ? null : zjLaiyuan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.zj_laiyuangj
     *
     * @return the value of dc_zwjy.zj_laiyuangj
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getZjLaiyuangj() {
        return zjLaiyuangj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.zj_laiyuangj
     *
     * @param zjLaiyuangj the value for dc_zwjy.zj_laiyuangj
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setZjLaiyuangj(String zjLaiyuangj) {
        this.zjLaiyuangj = zjLaiyuangj == null ? null : zjLaiyuangj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.zj_ybl
     *
     * @return the value of dc_zwjy.zj_ybl
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public Integer getZjYbl() {
        return zjYbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.zj_ybl
     *
     * @param zjYbl the value for dc_zwjy.zj_ybl
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setZjYbl(Integer zjYbl) {
        this.zjYbl = zjYbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.zj_ybdanwei
     *
     * @return the value of dc_zwjy.zj_ybdanwei
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getZjYbdanwei() {
        return zjYbdanwei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.zj_ybdanwei
     *
     * @param zjYbdanwei the value for dc_zwjy.zj_ybdanwei
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setZjYbdanwei(String zjYbdanwei) {
        this.zjYbdanwei = zjYbdanwei == null ? null : zjYbdanwei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.zj_baocunzt
     *
     * @return the value of dc_zwjy.zj_baocunzt
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getZjBaocunzt() {
        return zjBaocunzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.zj_baocunzt
     *
     * @param zjBaocunzt the value for dc_zwjy.zj_baocunzt
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setZjBaocunzt(String zjBaocunzt) {
        this.zjBaocunzt = zjBaocunzt == null ? null : zjBaocunzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.zj_huodedd
     *
     * @return the value of dc_zwjy.zj_huodedd
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getZjHuodedd() {
        return zjHuodedd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.zj_huodedd
     *
     * @param zjHuodedd the value for dc_zwjy.zj_huodedd
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setZjHuodedd(String zjHuodedd) {
        this.zjHuodedd = zjHuodedd == null ? null : zjHuodedd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.zj_baocunwz
     *
     * @return the value of dc_zwjy.zj_baocunwz
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getZjBaocunwz() {
        return zjBaocunwz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.zj_baocunwz
     *
     * @param zjBaocunwz the value for dc_zwjy.zj_baocunwz
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setZjBaocunwz(String zjBaocunwz) {
        this.zjBaocunwz = zjBaocunwz == null ? null : zjBaocunwz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.zj_baocuntj
     *
     * @return the value of dc_zwjy.zj_baocuntj
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getZjBaocuntj() {
        return zjBaocuntj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.zj_baocuntj
     *
     * @param zjBaocuntj the value for dc_zwjy.zj_baocuntj
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setZjBaocuntj(String zjBaocuntj) {
        this.zjBaocuntj = zjBaocuntj == null ? null : zjBaocuntj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.zj_baocunsj
     *
     * @return the value of dc_zwjy.zj_baocunsj
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getZjBaocunsj() {
        return zjBaocunsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.zj_baocunsj
     *
     * @param zjBaocunsj the value for dc_zwjy.zj_baocunsj
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setZjBaocunsj(String zjBaocunsj) {
        this.zjBaocunsj = zjBaocunsj == null ? null : zjBaocunsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.zj_lianlr
     *
     * @return the value of dc_zwjy.zj_lianlr
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getZjLianlr() {
        return zjLianlr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.zj_lianlr
     *
     * @param zjLianlr the value for dc_zwjy.zj_lianlr
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setZjLianlr(String zjLianlr) {
        this.zjLianlr = zjLianlr == null ? null : zjLianlr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.zj_lianldh
     *
     * @return the value of dc_zwjy.zj_lianldh
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getZjLianldh() {
        return zjLianldh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.zj_lianldh
     *
     * @param zjLianldh the value for dc_zwjy.zj_lianldh
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setZjLianldh(String zjLianldh) {
        this.zjLianldh = zjLianldh == null ? null : zjLianldh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.zj_fuzeren
     *
     * @return the value of dc_zwjy.zj_fuzeren
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getZjFuzeren() {
        return zjFuzeren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.zj_fuzeren
     *
     * @param zjFuzeren the value for dc_zwjy.zj_fuzeren
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setZjFuzeren(String zjFuzeren) {
        this.zjFuzeren = zjFuzeren == null ? null : zjFuzeren.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.zj_fuzerendh
     *
     * @return the value of dc_zwjy.zj_fuzerendh
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getZjFuzerendh() {
        return zjFuzerendh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.zj_fuzerendh
     *
     * @param zjFuzerendh the value for dc_zwjy.zj_fuzerendh
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setZjFuzerendh(String zjFuzerendh) {
        this.zjFuzerendh = zjFuzerendh == null ? null : zjFuzerendh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.zj_by1
     *
     * @return the value of dc_zwjy.zj_by1
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getZjBy1() {
        return zjBy1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.zj_by1
     *
     * @param zjBy1 the value for dc_zwjy.zj_by1
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setZjBy1(String zjBy1) {
        this.zjBy1 = zjBy1 == null ? null : zjBy1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.zj_by2
     *
     * @return the value of dc_zwjy.zj_by2
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getZjBy2() {
        return zjBy2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.zj_by2
     *
     * @param zjBy2 the value for dc_zwjy.zj_by2
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setZjBy2(String zjBy2) {
        this.zjBy2 = zjBy2 == null ? null : zjBy2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_zwjy.zj_by3
     *
     * @return the value of dc_zwjy.zj_by3
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public String getZjBy3() {
        return zjBy3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_zwjy.zj_by3
     *
     * @param zjBy3 the value for dc_zwjy.zj_by3
     *
     * @mbg.generated Sat Jan 23 21:18:05 CST 2021
     */
    public void setZjBy3(String zjBy3) {
        this.zjBy3 = zjBy3 == null ? null : zjBy3.trim();
    }
}