package com.xsz.customs.model;

import java.util.ArrayList;
import java.util.List;

public class djLblxExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public djLblxExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDjlbDmIsNull() {
            addCriterion("djlb_dm is null");
            return (Criteria) this;
        }

        public Criteria andDjlbDmIsNotNull() {
            addCriterion("djlb_dm is not null");
            return (Criteria) this;
        }

        public Criteria andDjlbDmEqualTo(String value) {
            addCriterion("djlb_dm =", value, "djlbDm");
            return (Criteria) this;
        }

        public Criteria andDjlbDmNotEqualTo(String value) {
            addCriterion("djlb_dm <>", value, "djlbDm");
            return (Criteria) this;
        }

        public Criteria andDjlbDmGreaterThan(String value) {
            addCriterion("djlb_dm >", value, "djlbDm");
            return (Criteria) this;
        }

        public Criteria andDjlbDmGreaterThanOrEqualTo(String value) {
            addCriterion("djlb_dm >=", value, "djlbDm");
            return (Criteria) this;
        }

        public Criteria andDjlbDmLessThan(String value) {
            addCriterion("djlb_dm <", value, "djlbDm");
            return (Criteria) this;
        }

        public Criteria andDjlbDmLessThanOrEqualTo(String value) {
            addCriterion("djlb_dm <=", value, "djlbDm");
            return (Criteria) this;
        }

        public Criteria andDjlbDmLike(String value) {
            addCriterion("djlb_dm like", value, "djlbDm");
            return (Criteria) this;
        }

        public Criteria andDjlbDmNotLike(String value) {
            addCriterion("djlb_dm not like", value, "djlbDm");
            return (Criteria) this;
        }

        public Criteria andDjlbDmIn(List<String> values) {
            addCriterion("djlb_dm in", values, "djlbDm");
            return (Criteria) this;
        }

        public Criteria andDjlbDmNotIn(List<String> values) {
            addCriterion("djlb_dm not in", values, "djlbDm");
            return (Criteria) this;
        }

        public Criteria andDjlbDmBetween(String value1, String value2) {
            addCriterion("djlb_dm between", value1, value2, "djlbDm");
            return (Criteria) this;
        }

        public Criteria andDjlbDmNotBetween(String value1, String value2) {
            addCriterion("djlb_dm not between", value1, value2, "djlbDm");
            return (Criteria) this;
        }

        public Criteria andDjlbMcIsNull() {
            addCriterion("djlb_mc is null");
            return (Criteria) this;
        }

        public Criteria andDjlbMcIsNotNull() {
            addCriterion("djlb_mc is not null");
            return (Criteria) this;
        }

        public Criteria andDjlbMcEqualTo(String value) {
            addCriterion("djlb_mc =", value, "djlbMc");
            return (Criteria) this;
        }

        public Criteria andDjlbMcNotEqualTo(String value) {
            addCriterion("djlb_mc <>", value, "djlbMc");
            return (Criteria) this;
        }

        public Criteria andDjlbMcGreaterThan(String value) {
            addCriterion("djlb_mc >", value, "djlbMc");
            return (Criteria) this;
        }

        public Criteria andDjlbMcGreaterThanOrEqualTo(String value) {
            addCriterion("djlb_mc >=", value, "djlbMc");
            return (Criteria) this;
        }

        public Criteria andDjlbMcLessThan(String value) {
            addCriterion("djlb_mc <", value, "djlbMc");
            return (Criteria) this;
        }

        public Criteria andDjlbMcLessThanOrEqualTo(String value) {
            addCriterion("djlb_mc <=", value, "djlbMc");
            return (Criteria) this;
        }

        public Criteria andDjlbMcLike(String value) {
            addCriterion("djlb_mc like", value, "djlbMc");
            return (Criteria) this;
        }

        public Criteria andDjlbMcNotLike(String value) {
            addCriterion("djlb_mc not like", value, "djlbMc");
            return (Criteria) this;
        }

        public Criteria andDjlbMcIn(List<String> values) {
            addCriterion("djlb_mc in", values, "djlbMc");
            return (Criteria) this;
        }

        public Criteria andDjlbMcNotIn(List<String> values) {
            addCriterion("djlb_mc not in", values, "djlbMc");
            return (Criteria) this;
        }

        public Criteria andDjlbMcBetween(String value1, String value2) {
            addCriterion("djlb_mc between", value1, value2, "djlbMc");
            return (Criteria) this;
        }

        public Criteria andDjlbMcNotBetween(String value1, String value2) {
            addCriterion("djlb_mc not between", value1, value2, "djlbMc");
            return (Criteria) this;
        }

        public Criteria andDjlbBy1IsNull() {
            addCriterion("djlb_by1 is null");
            return (Criteria) this;
        }

        public Criteria andDjlbBy1IsNotNull() {
            addCriterion("djlb_by1 is not null");
            return (Criteria) this;
        }

        public Criteria andDjlbBy1EqualTo(String value) {
            addCriterion("djlb_by1 =", value, "djlbBy1");
            return (Criteria) this;
        }

        public Criteria andDjlbBy1NotEqualTo(String value) {
            addCriterion("djlb_by1 <>", value, "djlbBy1");
            return (Criteria) this;
        }

        public Criteria andDjlbBy1GreaterThan(String value) {
            addCriterion("djlb_by1 >", value, "djlbBy1");
            return (Criteria) this;
        }

        public Criteria andDjlbBy1GreaterThanOrEqualTo(String value) {
            addCriterion("djlb_by1 >=", value, "djlbBy1");
            return (Criteria) this;
        }

        public Criteria andDjlbBy1LessThan(String value) {
            addCriterion("djlb_by1 <", value, "djlbBy1");
            return (Criteria) this;
        }

        public Criteria andDjlbBy1LessThanOrEqualTo(String value) {
            addCriterion("djlb_by1 <=", value, "djlbBy1");
            return (Criteria) this;
        }

        public Criteria andDjlbBy1Like(String value) {
            addCriterion("djlb_by1 like", value, "djlbBy1");
            return (Criteria) this;
        }

        public Criteria andDjlbBy1NotLike(String value) {
            addCriterion("djlb_by1 not like", value, "djlbBy1");
            return (Criteria) this;
        }

        public Criteria andDjlbBy1In(List<String> values) {
            addCriterion("djlb_by1 in", values, "djlbBy1");
            return (Criteria) this;
        }

        public Criteria andDjlbBy1NotIn(List<String> values) {
            addCriterion("djlb_by1 not in", values, "djlbBy1");
            return (Criteria) this;
        }

        public Criteria andDjlbBy1Between(String value1, String value2) {
            addCriterion("djlb_by1 between", value1, value2, "djlbBy1");
            return (Criteria) this;
        }

        public Criteria andDjlbBy1NotBetween(String value1, String value2) {
            addCriterion("djlb_by1 not between", value1, value2, "djlbBy1");
            return (Criteria) this;
        }

        public Criteria andDjlbBy2IsNull() {
            addCriterion("djlb_by2 is null");
            return (Criteria) this;
        }

        public Criteria andDjlbBy2IsNotNull() {
            addCriterion("djlb_by2 is not null");
            return (Criteria) this;
        }

        public Criteria andDjlbBy2EqualTo(String value) {
            addCriterion("djlb_by2 =", value, "djlbBy2");
            return (Criteria) this;
        }

        public Criteria andDjlbBy2NotEqualTo(String value) {
            addCriterion("djlb_by2 <>", value, "djlbBy2");
            return (Criteria) this;
        }

        public Criteria andDjlbBy2GreaterThan(String value) {
            addCriterion("djlb_by2 >", value, "djlbBy2");
            return (Criteria) this;
        }

        public Criteria andDjlbBy2GreaterThanOrEqualTo(String value) {
            addCriterion("djlb_by2 >=", value, "djlbBy2");
            return (Criteria) this;
        }

        public Criteria andDjlbBy2LessThan(String value) {
            addCriterion("djlb_by2 <", value, "djlbBy2");
            return (Criteria) this;
        }

        public Criteria andDjlbBy2LessThanOrEqualTo(String value) {
            addCriterion("djlb_by2 <=", value, "djlbBy2");
            return (Criteria) this;
        }

        public Criteria andDjlbBy2Like(String value) {
            addCriterion("djlb_by2 like", value, "djlbBy2");
            return (Criteria) this;
        }

        public Criteria andDjlbBy2NotLike(String value) {
            addCriterion("djlb_by2 not like", value, "djlbBy2");
            return (Criteria) this;
        }

        public Criteria andDjlbBy2In(List<String> values) {
            addCriterion("djlb_by2 in", values, "djlbBy2");
            return (Criteria) this;
        }

        public Criteria andDjlbBy2NotIn(List<String> values) {
            addCriterion("djlb_by2 not in", values, "djlbBy2");
            return (Criteria) this;
        }

        public Criteria andDjlbBy2Between(String value1, String value2) {
            addCriterion("djlb_by2 between", value1, value2, "djlbBy2");
            return (Criteria) this;
        }

        public Criteria andDjlbBy2NotBetween(String value1, String value2) {
            addCriterion("djlb_by2 not between", value1, value2, "djlbBy2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dj_lblx
     *
     * @mbg.generated do_not_delete_during_merge Sun Jan 24 14:19:18 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}