package com.xsz.customs.model;

public class djLblx {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dj_lblx.Id
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dj_lblx.djlb_dm
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    private String djlbDm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dj_lblx.djlb_mc
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    private String djlbMc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dj_lblx.djlb_by1
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    private String djlbBy1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dj_lblx.djlb_by2
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    private String djlbBy2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dj_lblx.Id
     *
     * @return the value of dj_lblx.Id
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dj_lblx.Id
     *
     * @param id the value for dj_lblx.Id
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dj_lblx.djlb_dm
     *
     * @return the value of dj_lblx.djlb_dm
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public String getDjlbDm() {
        return djlbDm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dj_lblx.djlb_dm
     *
     * @param djlbDm the value for dj_lblx.djlb_dm
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public void setDjlbDm(String djlbDm) {
        this.djlbDm = djlbDm == null ? null : djlbDm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dj_lblx.djlb_mc
     *
     * @return the value of dj_lblx.djlb_mc
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public String getDjlbMc() {
        return djlbMc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dj_lblx.djlb_mc
     *
     * @param djlbMc the value for dj_lblx.djlb_mc
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public void setDjlbMc(String djlbMc) {
        this.djlbMc = djlbMc == null ? null : djlbMc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dj_lblx.djlb_by1
     *
     * @return the value of dj_lblx.djlb_by1
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public String getDjlbBy1() {
        return djlbBy1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dj_lblx.djlb_by1
     *
     * @param djlbBy1 the value for dj_lblx.djlb_by1
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public void setDjlbBy1(String djlbBy1) {
        this.djlbBy1 = djlbBy1 == null ? null : djlbBy1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dj_lblx.djlb_by2
     *
     * @return the value of dj_lblx.djlb_by2
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public String getDjlbBy2() {
        return djlbBy2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dj_lblx.djlb_by2
     *
     * @param djlbBy2 the value for dj_lblx.djlb_by2
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public void setDjlbBy2(String djlbBy2) {
        this.djlbBy2 = djlbBy2 == null ? null : djlbBy2.trim();
    }
}