package com.xsz.customs.model;

public class wjLblx {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_lblx.Id
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_lblx.wjlb_dm
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    private String wjlbDm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_lblx.wjlb_mc
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    private String wjlbMc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_lblx.wjlb_by1
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    private String wjlbBy1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_lblx.wjlb_by2
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    private String wjlbBy2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_lblx.Id
     *
     * @return the value of wj_lblx.Id
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_lblx.Id
     *
     * @param id the value for wj_lblx.Id
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_lblx.wjlb_dm
     *
     * @return the value of wj_lblx.wjlb_dm
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public String getWjlbDm() {
        return wjlbDm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_lblx.wjlb_dm
     *
     * @param wjlbDm the value for wj_lblx.wjlb_dm
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public void setWjlbDm(String wjlbDm) {
        this.wjlbDm = wjlbDm == null ? null : wjlbDm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_lblx.wjlb_mc
     *
     * @return the value of wj_lblx.wjlb_mc
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public String getWjlbMc() {
        return wjlbMc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_lblx.wjlb_mc
     *
     * @param wjlbMc the value for wj_lblx.wjlb_mc
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public void setWjlbMc(String wjlbMc) {
        this.wjlbMc = wjlbMc == null ? null : wjlbMc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_lblx.wjlb_by1
     *
     * @return the value of wj_lblx.wjlb_by1
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public String getWjlbBy1() {
        return wjlbBy1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_lblx.wjlb_by1
     *
     * @param wjlbBy1 the value for wj_lblx.wjlb_by1
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public void setWjlbBy1(String wjlbBy1) {
        this.wjlbBy1 = wjlbBy1 == null ? null : wjlbBy1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_lblx.wjlb_by2
     *
     * @return the value of wj_lblx.wjlb_by2
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public String getWjlbBy2() {
        return wjlbBy2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_lblx.wjlb_by2
     *
     * @param wjlbBy2 the value for wj_lblx.wjlb_by2
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public void setWjlbBy2(String wjlbBy2) {
        this.wjlbBy2 = wjlbBy2 == null ? null : wjlbBy2.trim();
    }
}