package com.xsz.customs.model;

import java.util.ArrayList;
import java.util.List;

public class wjLblxExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public wjLblxExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andWjlbDmIsNull() {
            addCriterion("wjlb_dm is null");
            return (Criteria) this;
        }

        public Criteria andWjlbDmIsNotNull() {
            addCriterion("wjlb_dm is not null");
            return (Criteria) this;
        }

        public Criteria andWjlbDmEqualTo(String value) {
            addCriterion("wjlb_dm =", value, "wjlbDm");
            return (Criteria) this;
        }

        public Criteria andWjlbDmNotEqualTo(String value) {
            addCriterion("wjlb_dm <>", value, "wjlbDm");
            return (Criteria) this;
        }

        public Criteria andWjlbDmGreaterThan(String value) {
            addCriterion("wjlb_dm >", value, "wjlbDm");
            return (Criteria) this;
        }

        public Criteria andWjlbDmGreaterThanOrEqualTo(String value) {
            addCriterion("wjlb_dm >=", value, "wjlbDm");
            return (Criteria) this;
        }

        public Criteria andWjlbDmLessThan(String value) {
            addCriterion("wjlb_dm <", value, "wjlbDm");
            return (Criteria) this;
        }

        public Criteria andWjlbDmLessThanOrEqualTo(String value) {
            addCriterion("wjlb_dm <=", value, "wjlbDm");
            return (Criteria) this;
        }

        public Criteria andWjlbDmLike(String value) {
            addCriterion("wjlb_dm like", value, "wjlbDm");
            return (Criteria) this;
        }

        public Criteria andWjlbDmNotLike(String value) {
            addCriterion("wjlb_dm not like", value, "wjlbDm");
            return (Criteria) this;
        }

        public Criteria andWjlbDmIn(List<String> values) {
            addCriterion("wjlb_dm in", values, "wjlbDm");
            return (Criteria) this;
        }

        public Criteria andWjlbDmNotIn(List<String> values) {
            addCriterion("wjlb_dm not in", values, "wjlbDm");
            return (Criteria) this;
        }

        public Criteria andWjlbDmBetween(String value1, String value2) {
            addCriterion("wjlb_dm between", value1, value2, "wjlbDm");
            return (Criteria) this;
        }

        public Criteria andWjlbDmNotBetween(String value1, String value2) {
            addCriterion("wjlb_dm not between", value1, value2, "wjlbDm");
            return (Criteria) this;
        }

        public Criteria andWjlbMcIsNull() {
            addCriterion("wjlb_mc is null");
            return (Criteria) this;
        }

        public Criteria andWjlbMcIsNotNull() {
            addCriterion("wjlb_mc is not null");
            return (Criteria) this;
        }

        public Criteria andWjlbMcEqualTo(String value) {
            addCriterion("wjlb_mc =", value, "wjlbMc");
            return (Criteria) this;
        }

        public Criteria andWjlbMcNotEqualTo(String value) {
            addCriterion("wjlb_mc <>", value, "wjlbMc");
            return (Criteria) this;
        }

        public Criteria andWjlbMcGreaterThan(String value) {
            addCriterion("wjlb_mc >", value, "wjlbMc");
            return (Criteria) this;
        }

        public Criteria andWjlbMcGreaterThanOrEqualTo(String value) {
            addCriterion("wjlb_mc >=", value, "wjlbMc");
            return (Criteria) this;
        }

        public Criteria andWjlbMcLessThan(String value) {
            addCriterion("wjlb_mc <", value, "wjlbMc");
            return (Criteria) this;
        }

        public Criteria andWjlbMcLessThanOrEqualTo(String value) {
            addCriterion("wjlb_mc <=", value, "wjlbMc");
            return (Criteria) this;
        }

        public Criteria andWjlbMcLike(String value) {
            addCriterion("wjlb_mc like", value, "wjlbMc");
            return (Criteria) this;
        }

        public Criteria andWjlbMcNotLike(String value) {
            addCriterion("wjlb_mc not like", value, "wjlbMc");
            return (Criteria) this;
        }

        public Criteria andWjlbMcIn(List<String> values) {
            addCriterion("wjlb_mc in", values, "wjlbMc");
            return (Criteria) this;
        }

        public Criteria andWjlbMcNotIn(List<String> values) {
            addCriterion("wjlb_mc not in", values, "wjlbMc");
            return (Criteria) this;
        }

        public Criteria andWjlbMcBetween(String value1, String value2) {
            addCriterion("wjlb_mc between", value1, value2, "wjlbMc");
            return (Criteria) this;
        }

        public Criteria andWjlbMcNotBetween(String value1, String value2) {
            addCriterion("wjlb_mc not between", value1, value2, "wjlbMc");
            return (Criteria) this;
        }

        public Criteria andWjlbBy1IsNull() {
            addCriterion("wjlb_by1 is null");
            return (Criteria) this;
        }

        public Criteria andWjlbBy1IsNotNull() {
            addCriterion("wjlb_by1 is not null");
            return (Criteria) this;
        }

        public Criteria andWjlbBy1EqualTo(String value) {
            addCriterion("wjlb_by1 =", value, "wjlbBy1");
            return (Criteria) this;
        }

        public Criteria andWjlbBy1NotEqualTo(String value) {
            addCriterion("wjlb_by1 <>", value, "wjlbBy1");
            return (Criteria) this;
        }

        public Criteria andWjlbBy1GreaterThan(String value) {
            addCriterion("wjlb_by1 >", value, "wjlbBy1");
            return (Criteria) this;
        }

        public Criteria andWjlbBy1GreaterThanOrEqualTo(String value) {
            addCriterion("wjlb_by1 >=", value, "wjlbBy1");
            return (Criteria) this;
        }

        public Criteria andWjlbBy1LessThan(String value) {
            addCriterion("wjlb_by1 <", value, "wjlbBy1");
            return (Criteria) this;
        }

        public Criteria andWjlbBy1LessThanOrEqualTo(String value) {
            addCriterion("wjlb_by1 <=", value, "wjlbBy1");
            return (Criteria) this;
        }

        public Criteria andWjlbBy1Like(String value) {
            addCriterion("wjlb_by1 like", value, "wjlbBy1");
            return (Criteria) this;
        }

        public Criteria andWjlbBy1NotLike(String value) {
            addCriterion("wjlb_by1 not like", value, "wjlbBy1");
            return (Criteria) this;
        }

        public Criteria andWjlbBy1In(List<String> values) {
            addCriterion("wjlb_by1 in", values, "wjlbBy1");
            return (Criteria) this;
        }

        public Criteria andWjlbBy1NotIn(List<String> values) {
            addCriterion("wjlb_by1 not in", values, "wjlbBy1");
            return (Criteria) this;
        }

        public Criteria andWjlbBy1Between(String value1, String value2) {
            addCriterion("wjlb_by1 between", value1, value2, "wjlbBy1");
            return (Criteria) this;
        }

        public Criteria andWjlbBy1NotBetween(String value1, String value2) {
            addCriterion("wjlb_by1 not between", value1, value2, "wjlbBy1");
            return (Criteria) this;
        }

        public Criteria andWjlbBy2IsNull() {
            addCriterion("wjlb_by2 is null");
            return (Criteria) this;
        }

        public Criteria andWjlbBy2IsNotNull() {
            addCriterion("wjlb_by2 is not null");
            return (Criteria) this;
        }

        public Criteria andWjlbBy2EqualTo(String value) {
            addCriterion("wjlb_by2 =", value, "wjlbBy2");
            return (Criteria) this;
        }

        public Criteria andWjlbBy2NotEqualTo(String value) {
            addCriterion("wjlb_by2 <>", value, "wjlbBy2");
            return (Criteria) this;
        }

        public Criteria andWjlbBy2GreaterThan(String value) {
            addCriterion("wjlb_by2 >", value, "wjlbBy2");
            return (Criteria) this;
        }

        public Criteria andWjlbBy2GreaterThanOrEqualTo(String value) {
            addCriterion("wjlb_by2 >=", value, "wjlbBy2");
            return (Criteria) this;
        }

        public Criteria andWjlbBy2LessThan(String value) {
            addCriterion("wjlb_by2 <", value, "wjlbBy2");
            return (Criteria) this;
        }

        public Criteria andWjlbBy2LessThanOrEqualTo(String value) {
            addCriterion("wjlb_by2 <=", value, "wjlbBy2");
            return (Criteria) this;
        }

        public Criteria andWjlbBy2Like(String value) {
            addCriterion("wjlb_by2 like", value, "wjlbBy2");
            return (Criteria) this;
        }

        public Criteria andWjlbBy2NotLike(String value) {
            addCriterion("wjlb_by2 not like", value, "wjlbBy2");
            return (Criteria) this;
        }

        public Criteria andWjlbBy2In(List<String> values) {
            addCriterion("wjlb_by2 in", values, "wjlbBy2");
            return (Criteria) this;
        }

        public Criteria andWjlbBy2NotIn(List<String> values) {
            addCriterion("wjlb_by2 not in", values, "wjlbBy2");
            return (Criteria) this;
        }

        public Criteria andWjlbBy2Between(String value1, String value2) {
            addCriterion("wjlb_by2 between", value1, value2, "wjlbBy2");
            return (Criteria) this;
        }

        public Criteria andWjlbBy2NotBetween(String value1, String value2) {
            addCriterion("wjlb_by2 not between", value1, value2, "wjlbBy2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wj_lblx
     *
     * @mbg.generated do_not_delete_during_merge Sun Jan 24 14:19:18 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wj_lblx
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}