package com.xsz.customs.model;

public class zjLblx {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zj_lblx.Id
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zj_lblx.zjlb_dm
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    private String zjlbDm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zj_lblx.zjlb_mc
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    private String zjlbMc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zj_lblx.zjlb_by1
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    private String zjlbBy1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zj_lblx.zjlb_by2
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    private String zjlbBy2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zj_lblx.Id
     *
     * @return the value of zj_lblx.Id
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zj_lblx.Id
     *
     * @param id the value for zj_lblx.Id
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zj_lblx.zjlb_dm
     *
     * @return the value of zj_lblx.zjlb_dm
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public String getZjlbDm() {
        return zjlbDm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zj_lblx.zjlb_dm
     *
     * @param zjlbDm the value for zj_lblx.zjlb_dm
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public void setZjlbDm(String zjlbDm) {
        this.zjlbDm = zjlbDm == null ? null : zjlbDm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zj_lblx.zjlb_mc
     *
     * @return the value of zj_lblx.zjlb_mc
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public String getZjlbMc() {
        return zjlbMc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zj_lblx.zjlb_mc
     *
     * @param zjlbMc the value for zj_lblx.zjlb_mc
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public void setZjlbMc(String zjlbMc) {
        this.zjlbMc = zjlbMc == null ? null : zjlbMc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zj_lblx.zjlb_by1
     *
     * @return the value of zj_lblx.zjlb_by1
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public String getZjlbBy1() {
        return zjlbBy1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zj_lblx.zjlb_by1
     *
     * @param zjlbBy1 the value for zj_lblx.zjlb_by1
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public void setZjlbBy1(String zjlbBy1) {
        this.zjlbBy1 = zjlbBy1 == null ? null : zjlbBy1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zj_lblx.zjlb_by2
     *
     * @return the value of zj_lblx.zjlb_by2
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public String getZjlbBy2() {
        return zjlbBy2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zj_lblx.zjlb_by2
     *
     * @param zjlbBy2 the value for zj_lblx.zjlb_by2
     *
     * @mbg.generated Sun Jan 24 14:19:18 CST 2021
     */
    public void setZjlbBy2(String zjlbBy2) {
        this.zjlbBy2 = zjlbBy2 == null ? null : zjlbBy2.trim();
    }
}